#
# SPDX-FileCopyrightText: Copyright (c) 2025-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata

# Register definitions
# Array definitions
NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX = ArrayMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX',
    base_address=0x184,
    stride=12,
    size=4
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_CREDIT_AVAILABLE = FieldMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_CREDIT_AVAILABLE',
    msb=26,
    lsb=26,
    register=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_CREDIT_AVAILABLE_FALSE = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_CREDIT_AVAILABLE_FALSE',
    value=0,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_CREDIT_AVAILABLE
)
NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_CREDIT_AVAILABLE_TRUE = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_CREDIT_AVAILABLE_TRUE',
    value=1,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_CREDIT_AVAILABLE
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_ERR = FieldMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_ERR',
    msb=25,
    lsb=25,
    register=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_ERR_FALSE = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_ERR_FALSE',
    value=0,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_ERR
)
NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_ERR_TRUE = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_ERR_TRUE',
    value=1,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_ERR
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_ENABLE = FieldMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_ENABLE',
    msb=30,
    lsb=30,
    register=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_ENABLE_DISABLED = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_ENABLE_DISABLED',
    value=0,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_ENABLE
)
NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_ENABLE_ENABLED = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_ENABLE_ENABLED',
    value=1,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_ENABLE
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_STATUS = FieldMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_STATUS',
    msb=31,
    lsb=31,
    register=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_STATUS_CLEARED = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_STATUS_CLEARED',
    value=0,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_STATUS
)
NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_STATUS_SET = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_STATUS_SET',
    value=1,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_STATUS
)
NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_STATUS_W1CLR = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_STATUS_W1CLR',
    value=1,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_INTR_STATUS
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_MESSAGE_SIZE = FieldMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_MESSAGE_SIZE',
    msb=19,
    lsb=0,
    register=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_MESSAGE_SIZE_INIT = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_MESSAGE_SIZE_INIT',
    value=0,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_MESSAGE_SIZE
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_MESSAGE_TRIGGER = FieldMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_MESSAGE_TRIGGER',
    msb=20,
    lsb=20,
    register=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_MESSAGE_TRIGGER_SET = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_MESSAGE_TRIGGER_SET',
    value=1,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_MESSAGE_TRIGGER
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_RECEIVE_READY = FieldMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_RECEIVE_READY',
    msb=24,
    lsb=24,
    register=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_RECEIVE_READY_FALSE = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_RECEIVE_READY_FALSE',
    value=0,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_RECEIVE_READY
)
NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_RECEIVE_READY_TRUE = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_RECEIVE_READY_TRUE',
    value=1,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_RECEIVEMBOX_RECEIVE_READY
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX = ArrayMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX',
    base_address=0x104,
    stride=12,
    size=4
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_ERR = FieldMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_ERR',
    msb=25,
    lsb=25,
    register=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_ERR_FALSE = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_ERR_FALSE',
    value=0,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_ERR
)
NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_ERR_TRUE = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_ERR_TRUE',
    value=1,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_ERR
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_ENABLE = FieldMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_ENABLE',
    msb=30,
    lsb=30,
    register=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_ENABLE_DISABLED = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_ENABLE_DISABLED',
    value=0,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_ENABLE
)
NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_ENABLE_ENABLED = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_ENABLE_ENABLED',
    value=1,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_ENABLE
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_STATUS = FieldMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_STATUS',
    msb=31,
    lsb=31,
    register=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_STATUS_CLEARED = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_STATUS_CLEARED',
    value=0,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_STATUS
)
NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_STATUS_SET = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_STATUS_SET',
    value=1,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_STATUS
)
NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_STATUS_W1CLR = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_STATUS_W1CLR',
    value=1,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_INTR_STATUS
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_MESSAGE_READY = FieldMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_MESSAGE_READY',
    msb=24,
    lsb=24,
    register=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_MESSAGE_READY_FALSE = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_MESSAGE_READY_FALSE',
    value=0,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_MESSAGE_READY
)
NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_MESSAGE_READY_TRUE = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_MESSAGE_READY_TRUE',
    value=1,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_MESSAGE_READY
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_MESSAGE_SIZE = FieldMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_MESSAGE_SIZE',
    msb=19,
    lsb=0,
    register=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX
)

NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_MESSAGE_SIZE_INIT = ValueMetadata(
    name='NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_MESSAGE_SIZE_INIT',
    value=0,
    field=NV_MNOC_ZB_PRI_MESSAGE_INFO_0_SENDMBOX_MESSAGE_SIZE
)

NV_MNOC_ZB_PRI_RDATA_0_SENDMBOX = ArrayMetadata(
    name='NV_MNOC_ZB_PRI_RDATA_0_SENDMBOX',
    base_address=0x108,
    stride=12,
    size=4
)

NV_MNOC_ZB_PRI_RDATA_0_SENDMBOX_RDATA = FieldMetadata(
    name='NV_MNOC_ZB_PRI_RDATA_0_SENDMBOX_RDATA',
    msb=31,
    lsb=0,
    register=NV_MNOC_ZB_PRI_RDATA_0_SENDMBOX
)

NV_MNOC_ZB_PRI_RDATA_0_SENDMBOX_RDATA_INIT = ValueMetadata(
    name='NV_MNOC_ZB_PRI_RDATA_0_SENDMBOX_RDATA_INIT',
    value=0,
    field=NV_MNOC_ZB_PRI_RDATA_0_SENDMBOX_RDATA
)

NV_MNOC_ZB_PRI_WDATA_0_RECEIVEMBOX = ArrayMetadata(
    name='NV_MNOC_ZB_PRI_WDATA_0_RECEIVEMBOX',
    base_address=0x188,
    stride=12,
    size=4
)

NV_MNOC_ZB_PRI_WDATA_0_RECEIVEMBOX_WDATA = FieldMetadata(
    name='NV_MNOC_ZB_PRI_WDATA_0_RECEIVEMBOX_WDATA',
    msb=31,
    lsb=0,
    register=NV_MNOC_ZB_PRI_WDATA_0_RECEIVEMBOX
)

