#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata


# Register definitions
NV_R_QSKWRMTD_PRIV_LEVEL_MASK = RegisterMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK',
    address=0x708
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION',
    msb=3,
    lsb=0,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_V_HEJWCNHK = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_V_HEJWCNHK',
    value=0,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED',
    value=15,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR',
    value=8,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0 = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0',
    msb=0,
    lsb=0,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE',
    value=0,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE',
    value=1,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1 = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1',
    msb=1,
    lsb=1,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE',
    value=0,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE',
    value=1,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2 = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2',
    msb=2,
    lsb=2,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE',
    value=0,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE',
    value=1,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3 = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3',
    msb=3,
    lsb=3,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE',
    value=0,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE',
    value=1,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_VIOLATION = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_VIOLATION',
    msb=8,
    lsb=8,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR',
    value=1,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_VIOLATION
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON',
    value=0,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_READ_VIOLATION
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_ENABLE = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_ENABLE',
    msb=31,
    lsb=12,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_GJCSBGNJ = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_GJCSBGNJ',
    value=1048575,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_ENABLE
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL',
    msb=10,
    lsb=10,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED',
    value=1,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED',
    value=0,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL',
    msb=11,
    lsb=11,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED',
    value=1,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED',
    value=0,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION',
    msb=7,
    lsb=4,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_HEJWCNHK = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_HEJWCNHK',
    value=0,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED',
    value=15,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR',
    value=8,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0 = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0',
    msb=4,
    lsb=4,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE',
    value=0,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE',
    value=1,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1 = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1',
    msb=5,
    lsb=5,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE',
    value=0,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE',
    value=1,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2 = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2',
    msb=6,
    lsb=6,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE',
    value=0,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE',
    value=1,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3 = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3',
    msb=7,
    lsb=7,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE',
    value=0,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE',
    value=1,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_VIOLATION = FieldMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_VIOLATION',
    msb=9,
    lsb=9,
    register=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR',
    value=1,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_VIOLATION
)
NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON = ValueMetadata(
    name='NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON',
    value=0,
    field=NV_R_QSKWRMTD_PRIV_LEVEL_MASK_WRITE_VIOLATION
)

NV_R_PUGRKSLI = RegisterMetadata(
    name='NV_R_PUGRKSLI',
    address=0xa5c
)

NV_R_PUGRKSLI_F_ZIGJNGSD = FieldMetadata(
    name='NV_R_PUGRKSLI_F_ZIGJNGSD',
    msb=31,
    lsb=18,
    register=NV_R_PUGRKSLI
)

NV_R_PUGRKSLI_F_ZIGJNGSD_V_VEOTFCME = ValueMetadata(
    name='NV_R_PUGRKSLI_F_ZIGJNGSD_V_VEOTFCME',
    value=2,
    field=NV_R_PUGRKSLI_F_ZIGJNGSD
)
NV_R_PUGRKSLI_F_ZIGJNGSD_V_PQHFCEZA = ValueMetadata(
    name='NV_R_PUGRKSLI_F_ZIGJNGSD_V_PQHFCEZA',
    value=4,
    field=NV_R_PUGRKSLI_F_ZIGJNGSD
)
NV_R_PUGRKSLI_F_ZIGJNGSD_V_APNIRFIU = ValueMetadata(
    name='NV_R_PUGRKSLI_F_ZIGJNGSD_V_APNIRFIU',
    value=1,
    field=NV_R_PUGRKSLI_F_ZIGJNGSD
)
NV_R_PUGRKSLI_F_ZIGJNGSD_V_IYYIPNIL = ValueMetadata(
    name='NV_R_PUGRKSLI_F_ZIGJNGSD_V_IYYIPNIL',
    value=32,
    field=NV_R_PUGRKSLI_F_ZIGJNGSD
)
NV_R_PUGRKSLI_F_ZIGJNGSD_V_GQHYEKHS = ValueMetadata(
    name='NV_R_PUGRKSLI_F_ZIGJNGSD_V_GQHYEKHS',
    value=0,
    field=NV_R_PUGRKSLI_F_ZIGJNGSD
)
NV_R_PUGRKSLI_F_ZIGJNGSD_V_LKCMWVYB = ValueMetadata(
    name='NV_R_PUGRKSLI_F_ZIGJNGSD_V_LKCMWVYB',
    value=64,
    field=NV_R_PUGRKSLI_F_ZIGJNGSD
)
NV_R_PUGRKSLI_F_ZIGJNGSD_V_CWKNFZSF = ValueMetadata(
    name='NV_R_PUGRKSLI_F_ZIGJNGSD_V_CWKNFZSF',
    value=256,
    field=NV_R_PUGRKSLI_F_ZIGJNGSD
)
NV_R_PUGRKSLI_F_ZIGJNGSD_V_FYFBGSXV = ValueMetadata(
    name='NV_R_PUGRKSLI_F_ZIGJNGSD_V_FYFBGSXV',
    value=512,
    field=NV_R_PUGRKSLI_F_ZIGJNGSD
)
NV_R_PUGRKSLI_F_ZIGJNGSD_V_BJZZNPLO = ValueMetadata(
    name='NV_R_PUGRKSLI_F_ZIGJNGSD_V_BJZZNPLO',
    value=1024,
    field=NV_R_PUGRKSLI_F_ZIGJNGSD
)
NV_R_PUGRKSLI_F_ZIGJNGSD_V_LGMXRMGJ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_ZIGJNGSD_V_LGMXRMGJ',
    value=16,
    field=NV_R_PUGRKSLI_F_ZIGJNGSD
)
NV_R_PUGRKSLI_F_ZIGJNGSD_V_HTSSWIVR = ValueMetadata(
    name='NV_R_PUGRKSLI_F_ZIGJNGSD_V_HTSSWIVR',
    value=128,
    field=NV_R_PUGRKSLI_F_ZIGJNGSD
)
NV_R_PUGRKSLI_F_ZIGJNGSD_V_MBHYMMGE = ValueMetadata(
    name='NV_R_PUGRKSLI_F_ZIGJNGSD_V_MBHYMMGE',
    value=8,
    field=NV_R_PUGRKSLI_F_ZIGJNGSD
)

NV_R_PUGRKSLI_F_XYTFAUPO = FieldMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO',
    msb=7,
    lsb=2,
    register=NV_R_PUGRKSLI
)

NV_R_PUGRKSLI_F_XYTFAUPO_V_NBBHKABK = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_NBBHKABK',
    value=15,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_EYIFGKJN = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_EYIFGKJN',
    value=11,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_OLSIEZWO = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_OLSIEZWO',
    value=7,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_BAZVOEMP = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_BAZVOEMP',
    value=12,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_MRBKMRRX = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_MRBKMRRX',
    value=0,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_QRGSYAKB = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_QRGSYAKB',
    value=1,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_NJRXRMFO = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_NJRXRMFO',
    value=9,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_HTMTSYUJ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_HTMTSYUJ',
    value=2,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_ETQYNJEQ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_ETQYNJEQ',
    value=14,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_UMNPPGGF = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_UMNPPGGF',
    value=8,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_VJAMCAKM = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_VJAMCAKM',
    value=5,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_LWUUJOAK = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_LWUUJOAK',
    value=3,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_JVYIISVB = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_JVYIISVB',
    value=13,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_BKKQEVMV = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_BKKQEVMV',
    value=10,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_RRBNHVRL = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_RRBNHVRL',
    value=6,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)
NV_R_PUGRKSLI_F_XYTFAUPO_V_ORXHJFZG = ValueMetadata(
    name='NV_R_PUGRKSLI_F_XYTFAUPO_V_ORXHJFZG',
    value=4,
    field=NV_R_PUGRKSLI_F_XYTFAUPO
)

NV_R_PUGRKSLI_F_VJFIQTOC = FieldMetadata(
    name='NV_R_PUGRKSLI_F_VJFIQTOC',
    msb=1,
    lsb=0,
    register=NV_R_PUGRKSLI
)

NV_R_PUGRKSLI_F_VJFIQTOC_V_WYKEPOMU = ValueMetadata(
    name='NV_R_PUGRKSLI_F_VJFIQTOC_V_WYKEPOMU',
    value=2,
    field=NV_R_PUGRKSLI_F_VJFIQTOC
)
NV_R_PUGRKSLI_F_VJFIQTOC_V_GQHYEKHS = ValueMetadata(
    name='NV_R_PUGRKSLI_F_VJFIQTOC_V_GQHYEKHS',
    value=0,
    field=NV_R_PUGRKSLI_F_VJFIQTOC
)
NV_R_PUGRKSLI_F_VJFIQTOC_V_PMBXFXYE = ValueMetadata(
    name='NV_R_PUGRKSLI_F_VJFIQTOC_V_PMBXFXYE',
    value=3,
    field=NV_R_PUGRKSLI_F_VJFIQTOC
)
NV_R_PUGRKSLI_F_VJFIQTOC_V_BKKWVRNJ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_VJFIQTOC_V_BKKWVRNJ',
    value=1,
    field=NV_R_PUGRKSLI_F_VJFIQTOC
)

NV_R_PUGRKSLI_F_SUTDGKZV = FieldMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV',
    msb=17,
    lsb=8,
    register=NV_R_PUGRKSLI
)

NV_R_PUGRKSLI_F_SUTDGKZV_V_SCXOWOHM = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_SCXOWOHM',
    value=163,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_NZVORJZX = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_NZVORJZX',
    value=169,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_PRYCRBOQ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_PRYCRBOQ',
    value=170,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_AHKMJFTF = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_AHKMJFTF',
    value=168,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_WUTFNUBJ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_WUTFNUBJ',
    value=172,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_SFTPQSDD = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_SFTPQSDD',
    value=173,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_MVEHWCUD = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_MVEHWCUD',
    value=174,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_CRDRSVNI = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_CRDRSVNI',
    value=171,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_TWHGPNUH = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_TWHGPNUH',
    value=166,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_OTTTYUPI = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_OTTTYUPI',
    value=165,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_BWWYQKIM = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_BWWYQKIM',
    value=164,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_IFABIVTW = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_IFABIVTW',
    value=167,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_DBFLYVKD = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_DBFLYVKD',
    value=178,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_XEPNQZPD = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_XEPNQZPD',
    value=433,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_YOFPSDEK = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_YOFPSDEK',
    value=434,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_MOWCQMVL = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_MOWCQMVL',
    value=432,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_HDKCBKOX = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_HDKCBKOX',
    value=480,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_YWDEEGHA = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_YWDEEGHA',
    value=96,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_CCBOYBWW = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_CCBOYBWW',
    value=97,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_TVBIMCDD = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_TVBIMCDD',
    value=32,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_VXWILAHZ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_VXWILAHZ',
    value=36,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_UQBWMDPG = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_UQBWMDPG',
    value=34,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_NOOOGGGN = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_NOOOGGGN',
    value=33,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_JEVMTONU = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_JEVMTONU',
    value=35,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_XZUTSZAD = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_XZUTSZAD',
    value=513,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_WTIFVCMT = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_WTIFVCMT',
    value=514,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_QMGPPWNL = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_QMGPPWNL',
    value=512,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_GKARRTWC = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_GKARRTWC',
    value=718,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_XEMDHFVS = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_XEMDHFVS',
    value=256,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_UGHAMJOW = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_UGHAMJOW',
    value=261,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_BQKNXOFP = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_BQKNXOFP',
    value=257,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_FVCCKDTF = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_FVCCKDTF',
    value=258,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_FMCFTAVL = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_FMCFTAVL',
    value=259,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_BPESLJXW = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_BPESLJXW',
    value=260,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_GQHYEKHS = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_GQHYEKHS',
    value=0,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_DEEXWMPF = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_DEEXWMPF',
    value=321,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_HFLSLQEZ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_HFLSLQEZ',
    value=485,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_ZSBJRXCE = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_ZSBJRXCE',
    value=487,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_VOSFJBFB = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_VOSFJBFB',
    value=488,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_RBDLASKV = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_RBDLASKV',
    value=483,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_OAPDQERP = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_OAPDQERP',
    value=484,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_LLLHMLPR = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_LLLHMLPR',
    value=486,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_UGKZFEZK = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_UGKZFEZK',
    value=489,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_DFCIPILU = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_DFCIPILU',
    value=481,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_FMMMBDMZ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_FMMMBDMZ',
    value=482,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_WQAJHMDT = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_WQAJHMDT',
    value=67,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_YKBKVOGH = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_YKBKVOGH',
    value=68,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_RDCISKTU = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_RDCISKTU',
    value=288,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_PPDTQJOR = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_PPDTQJOR',
    value=289,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_TDDLKBHM = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_TDDLKBHM',
    value=290,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_BZKAWIQM = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_BZKAWIQM',
    value=291,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_KFQJVZBU = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_KFQJVZBU',
    value=292,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_ZUJYHPVY = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_ZUJYHPVY',
    value=176,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_NDLMFGNT = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_NDLMFGNT',
    value=175,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_FCCUWZSF = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_FCCUWZSF',
    value=177,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_AGQHEMFX = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_AGQHEMFX',
    value=320,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_SJEXAPLH = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_SJEXAPLH',
    value=323,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_ILWICUYI = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_ILWICUYI',
    value=192,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_GYKABBEP = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_GYKABBEP',
    value=194,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_NVNRZGVG = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_NVNRZGVG',
    value=195,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_BVHXKTHD = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_BVHXKTHD',
    value=196,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_QGKVQJBL = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_QGKVQJBL',
    value=207,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_UOTRBPIY = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_UOTRBPIY',
    value=197,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_WJOLTBQJ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_WJOLTBQJ',
    value=206,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_HHAYAKCQ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_HHAYAKCQ',
    value=198,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_OJHWRSAM = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_OJHWRSAM',
    value=199,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_ZPXXAUJV = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_ZPXXAUJV',
    value=200,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_AOHSYOGB = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_AOHSYOGB',
    value=201,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_BAFYAJFY = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_BAFYAJFY',
    value=202,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_QVNCRASN = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_QVNCRASN',
    value=715,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_ICTOZDXS = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_ICTOZDXS',
    value=204,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_YUAIMTIB = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_YUAIMTIB',
    value=205,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_TSETAYSE = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_TSETAYSE',
    value=416,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_ZVJNSPDG = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_ZVJNSPDG',
    value=417,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_TRSJTFDQ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_TRSJTFDQ',
    value=418,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_ZLFAGMGK = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_ZLFAGMGK',
    value=322,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_CXWKFCIM = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_CXWKFCIM',
    value=162,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_WOYJALJW = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_WOYJALJW',
    value=227,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_VFFKASFO = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_VFFKASFO',
    value=237,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_JHSILSVE = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_JHSILSVE',
    value=235,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_RXFGTMDU = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_RXFGTMDU',
    value=233,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_DDCBVPAP = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_DDCBVPAP',
    value=232,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_RSIEBTOS = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_RSIEBTOS',
    value=231,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_KTGCNOZS = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_KTGCNOZS',
    value=230,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_WWJKEAIM = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_WWJKEAIM',
    value=234,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_YLZHCDFE = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_YLZHCDFE',
    value=239,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_QIQNJFDS = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_QIQNJFDS',
    value=236,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_XJUDFFOK = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_XJUDFFOK',
    value=226,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_RZETOFOC = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_RZETOFOC',
    value=228,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_JOHPSIZH = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_JOHPSIZH',
    value=229,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_NXXHLJDA = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_NXXHLJDA',
    value=866,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_YFECZSJO = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_YFECZSJO',
    value=864,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_OEFPRVDO = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_OEFPRVDO',
    value=265,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_SBXSXTEA = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_SBXSXTEA',
    value=867,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_TLHOXKYH = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_TLHOXKYH',
    value=1023,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_OUSJROMK = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_OUSJROMK',
    value=262,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_SISBGFJJ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_SISBGFJJ',
    value=353,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_ZOLEAUYB = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_ZOLEAUYB',
    value=352,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_DQRPNWOV = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_DQRPNWOV',
    value=132,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_OZWQTORA = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_OZWQTORA',
    value=389,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_FCSSUBUL = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_FCSSUBUL',
    value=385,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_GYSJGNFV = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_GYSJGNFV',
    value=384,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_BLUXHDRD = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_BLUXHDRD',
    value=387,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_EIMDFNBJ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_EIMDFNBJ',
    value=386,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_SFZDYTVM = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_SFZDYTVM',
    value=388,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_MNRRTRSN = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_MNRRTRSN',
    value=160,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_YROSDTUF = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_YROSDTUF',
    value=161,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_ZMMVZTCP = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_ZMMVZTCP',
    value=130,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_DIZYIOBO = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_DIZYIOBO',
    value=131,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_KIYBUQES = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_KIYBUQES',
    value=128,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_ZZKHFOWB = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_ZZKHFOWB',
    value=225,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_UVXOUBSI = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_UVXOUBSI',
    value=224,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_BJYXPVTS = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_BJYXPVTS',
    value=129,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_GHHKDGPG = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_GHHKDGPG',
    value=64,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_ZBNOYNLF = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_ZBNOYNLF',
    value=65,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_KKZSOSHD = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_KKZSOSHD',
    value=66,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_HWRUAGUL = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_HWRUAGUL',
    value=720,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_HTBMYAMS = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_HTBMYAMS',
    value=721,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_MZFDLOBX = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_MZFDLOBX',
    value=719,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_AUFORQKC = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_AUFORQKC',
    value=179,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_SMUFWUWY = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_SMUFWUWY',
    value=263,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_EZCQYVTB = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_EZCQYVTB',
    value=264,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_OGRARJMU = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_OGRARJMU',
    value=208,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)
NV_R_PUGRKSLI_F_SUTDGKZV_V_WYDVFZUZ = ValueMetadata(
    name='NV_R_PUGRKSLI_F_SUTDGKZV_V_WYDVFZUZ',
    value=868,
    field=NV_R_PUGRKSLI_F_SUTDGKZV
)

NV_R_FAQEKJAC = RegisterMetadata(
    name='NV_R_FAQEKJAC',
    address=0x788,
    priv_level_mask=NV_R_QSKWRMTD_PRIV_LEVEL_MASK
)

NV_R_FAQEKJAC_F_AUUPAXHZ = FieldMetadata(
    name='NV_R_FAQEKJAC_F_AUUPAXHZ',
    msb=7,
    lsb=7,
    register=NV_R_FAQEKJAC
)

NV_R_FAQEKJAC_F_AUUPAXHZ_V_TYLKUYOV = ValueMetadata(
    name='NV_R_FAQEKJAC_F_AUUPAXHZ_V_TYLKUYOV',
    value=1,
    field=NV_R_FAQEKJAC_F_AUUPAXHZ
)
NV_R_FAQEKJAC_F_AUUPAXHZ_V_KFONVPTU = ValueMetadata(
    name='NV_R_FAQEKJAC_F_AUUPAXHZ_V_KFONVPTU',
    value=0,
    field=NV_R_FAQEKJAC_F_AUUPAXHZ
)

NV_R_FAQEKJAC_F_REDTGIDZ = FieldMetadata(
    name='NV_R_FAQEKJAC_F_REDTGIDZ',
    msb=4,
    lsb=4,
    register=NV_R_FAQEKJAC
)

NV_R_FAQEKJAC_F_REDTGIDZ_FALSE = ValueMetadata(
    name='NV_R_FAQEKJAC_F_REDTGIDZ_FALSE',
    value=0,
    field=NV_R_FAQEKJAC_F_REDTGIDZ
)
NV_R_FAQEKJAC_F_REDTGIDZ_V_GQHYEKHS = ValueMetadata(
    name='NV_R_FAQEKJAC_F_REDTGIDZ_V_GQHYEKHS',
    value=1,
    field=NV_R_FAQEKJAC_F_REDTGIDZ
)
NV_R_FAQEKJAC_F_REDTGIDZ_TRUE = ValueMetadata(
    name='NV_R_FAQEKJAC_F_REDTGIDZ_TRUE',
    value=1,
    field=NV_R_FAQEKJAC_F_REDTGIDZ
)

NV_R_FAQEKJAC_F_QZQAGPDP = FieldMetadata(
    name='NV_R_FAQEKJAC_F_QZQAGPDP',
    msb=0,
    lsb=0,
    register=NV_R_FAQEKJAC
)

NV_R_FAQEKJAC_F_QZQAGPDP_FALSE = ValueMetadata(
    name='NV_R_FAQEKJAC_F_QZQAGPDP_FALSE',
    value=0,
    field=NV_R_FAQEKJAC_F_QZQAGPDP
)
NV_R_FAQEKJAC_F_QZQAGPDP_TRUE = ValueMetadata(
    name='NV_R_FAQEKJAC_F_QZQAGPDP_TRUE',
    value=1,
    field=NV_R_FAQEKJAC_F_QZQAGPDP
)

NV_R_FAQEKJAC_F_FWGUVILY = FieldMetadata(
    name='NV_R_FAQEKJAC_F_FWGUVILY',
    msb=10,
    lsb=8,
    register=NV_R_FAQEKJAC
)

NV_R_FAQEKJAC_F_FWGUVILY_V_HZZXAFDO = ValueMetadata(
    name='NV_R_FAQEKJAC_F_FWGUVILY_V_HZZXAFDO',
    value=4,
    field=NV_R_FAQEKJAC_F_FWGUVILY
)
NV_R_FAQEKJAC_F_FWGUVILY_V_WPYXITJB = ValueMetadata(
    name='NV_R_FAQEKJAC_F_FWGUVILY_V_WPYXITJB',
    value=3,
    field=NV_R_FAQEKJAC_F_FWGUVILY
)
NV_R_FAQEKJAC_F_FWGUVILY_V_GQHYEKHS = ValueMetadata(
    name='NV_R_FAQEKJAC_F_FWGUVILY_V_GQHYEKHS',
    value=0,
    field=NV_R_FAQEKJAC_F_FWGUVILY
)
NV_R_FAQEKJAC_F_FWGUVILY_V_BKKWVRNJ = ValueMetadata(
    name='NV_R_FAQEKJAC_F_FWGUVILY_V_BKKWVRNJ',
    value=1,
    field=NV_R_FAQEKJAC_F_FWGUVILY
)
NV_R_FAQEKJAC_F_FWGUVILY_V_UMSTQJQT = ValueMetadata(
    name='NV_R_FAQEKJAC_F_FWGUVILY_V_UMSTQJQT',
    value=2,
    field=NV_R_FAQEKJAC_F_FWGUVILY
)

NV_R_FAQEKJAC_F_WHRWJGMO = FieldMetadata(
    name='NV_R_FAQEKJAC_F_WHRWJGMO',
    msb=5,
    lsb=5,
    register=NV_R_FAQEKJAC
)

NV_R_FAQEKJAC_F_WHRWJGMO_V_GQHYEKHS = ValueMetadata(
    name='NV_R_FAQEKJAC_F_WHRWJGMO_V_GQHYEKHS',
    value=0,
    field=NV_R_FAQEKJAC_F_WHRWJGMO
)

NV_R_SKKDSWOZ = RegisterMetadata(
    name='NV_R_SKKDSWOZ',
    address=0x910
)

NV_R_SKKDSWOZ_F_PXIMDYUO = FieldMetadata(
    name='NV_R_SKKDSWOZ_F_PXIMDYUO',
    msb=30,
    lsb=0,
    register=NV_R_SKKDSWOZ
)

NV_R_SKKDSWOZ_F_PXIMDYUO_V_GQHYEKHS = ValueMetadata(
    name='NV_R_SKKDSWOZ_F_PXIMDYUO_V_GQHYEKHS',
    value=0,
    field=NV_R_SKKDSWOZ_F_PXIMDYUO
)

NV_R_SKKDSWOZ_VALID = FieldMetadata(
    name='NV_R_SKKDSWOZ_VALID',
    msb=31,
    lsb=31,
    register=NV_R_SKKDSWOZ
)

NV_R_SKKDSWOZ_VALID_FALSE = ValueMetadata(
    name='NV_R_SKKDSWOZ_VALID_FALSE',
    value=0,
    field=NV_R_SKKDSWOZ_VALID
)
NV_R_SKKDSWOZ_VALID_TRUE = ValueMetadata(
    name='NV_R_SKKDSWOZ_VALID_TRUE',
    value=1,
    field=NV_R_SKKDSWOZ_VALID
)

NV_R_PUDUKBYF = RegisterMetadata(
    name='NV_R_PUDUKBYF',
    address=0x794,
    debug_dump={'tags': ['intr_status'], 'path': 'nvlink.mse', 'samples': 1000}
)

NV_R_PUDUKBYF_F_AQFWRERE = FieldMetadata(
    name='NV_R_PUDUKBYF_F_AQFWRERE',
    msb=1,
    lsb=1,
    register=NV_R_PUDUKBYF
)

NV_R_PUDUKBYF_F_AQFWRERE_V_JMNURMPL = ValueMetadata(
    name='NV_R_PUDUKBYF_F_AQFWRERE_V_JMNURMPL',
    value=0,
    field=NV_R_PUDUKBYF_F_AQFWRERE
)

NV_R_PUDUKBYF_F_NQSKSSVT = FieldMetadata(
    name='NV_R_PUDUKBYF_F_NQSKSSVT',
    msb=1,
    lsb=1,
    register=NV_R_PUDUKBYF
)

NV_R_PUDUKBYF_F_NQSKSSVT_V_JMNURMPL = ValueMetadata(
    name='NV_R_PUDUKBYF_F_NQSKSSVT_V_JMNURMPL',
    value=0,
    field=NV_R_PUDUKBYF_F_NQSKSSVT
)

NV_R_PUDUKBYF_F_CBSZTSEY = FieldMetadata(
    name='NV_R_PUDUKBYF_F_CBSZTSEY',
    msb=2,
    lsb=2,
    register=NV_R_PUDUKBYF
)

NV_R_PUDUKBYF_F_CBSZTSEY_V_GQHYEKHS = ValueMetadata(
    name='NV_R_PUDUKBYF_F_CBSZTSEY_V_GQHYEKHS',
    value=0,
    field=NV_R_PUDUKBYF_F_CBSZTSEY
)

NV_R_PUDUKBYF_F_MAKIJQIB = FieldMetadata(
    name='NV_R_PUDUKBYF_F_MAKIJQIB',
    msb=0,
    lsb=0,
    register=NV_R_PUDUKBYF
)

NV_R_PUDUKBYF_F_MAKIJQIB_V_GQHYEKHS = ValueMetadata(
    name='NV_R_PUDUKBYF_F_MAKIJQIB_V_GQHYEKHS',
    value=0,
    field=NV_R_PUDUKBYF_F_MAKIJQIB
)

NV_R_PUDUKBYF_F_WXNDRGMV = FieldMetadata(
    name='NV_R_PUDUKBYF_F_WXNDRGMV',
    msb=2,
    lsb=2,
    register=NV_R_PUDUKBYF
)

NV_R_PUDUKBYF_F_WXNDRGMV_V_GQHYEKHS = ValueMetadata(
    name='NV_R_PUDUKBYF_F_WXNDRGMV_V_GQHYEKHS',
    value=0,
    field=NV_R_PUDUKBYF_F_WXNDRGMV
)

NV_R_PUDUKBYF_F_HGPEBRTD = FieldMetadata(
    name='NV_R_PUDUKBYF_F_HGPEBRTD',
    msb=4,
    lsb=4,
    register=NV_R_PUDUKBYF
)

NV_R_PUDUKBYF_F_HGPEBRTD_V_JMNURMPL = ValueMetadata(
    name='NV_R_PUDUKBYF_F_HGPEBRTD_V_JMNURMPL',
    value=0,
    field=NV_R_PUDUKBYF_F_HGPEBRTD
)

NV_R_PUDUKBYF_F_TTDEBOJC = FieldMetadata(
    name='NV_R_PUDUKBYF_F_TTDEBOJC',
    msb=5,
    lsb=5,
    register=NV_R_PUDUKBYF
)

NV_R_PUDUKBYF_F_TTDEBOJC_V_GQHYEKHS = ValueMetadata(
    name='NV_R_PUDUKBYF_F_TTDEBOJC_V_GQHYEKHS',
    value=0,
    field=NV_R_PUDUKBYF_F_TTDEBOJC
)

NV_R_PUDUKBYF_F_WXLVGPLS = FieldMetadata(
    name='NV_R_PUDUKBYF_F_WXLVGPLS',
    msb=3,
    lsb=3,
    register=NV_R_PUDUKBYF
)

NV_R_PUDUKBYF_F_WXLVGPLS_V_GQHYEKHS = ValueMetadata(
    name='NV_R_PUDUKBYF_F_WXLVGPLS_V_GQHYEKHS',
    value=0,
    field=NV_R_PUDUKBYF_F_WXLVGPLS
)

NV_R_PUDUKBYF_F_GZUNECFA = FieldMetadata(
    name='NV_R_PUDUKBYF_F_GZUNECFA',
    msb=0,
    lsb=0,
    register=NV_R_PUDUKBYF
)

NV_R_PUDUKBYF_F_GZUNECFA_V_GQHYEKHS = ValueMetadata(
    name='NV_R_PUDUKBYF_F_GZUNECFA_V_GQHYEKHS',
    value=0,
    field=NV_R_PUDUKBYF_F_GZUNECFA
)

NV_R_LJQBQIPV = RegisterMetadata(
    name='NV_R_LJQBQIPV',
    address=0x908
)

NV_R_LJQBQIPV_F_FMDCUIAD = FieldMetadata(
    name='NV_R_LJQBQIPV_F_FMDCUIAD',
    msb=31,
    lsb=0,
    register=NV_R_LJQBQIPV
)

NV_R_LJQBQIPV_F_FMDCUIAD_V_GQHYEKHS = ValueMetadata(
    name='NV_R_LJQBQIPV_F_FMDCUIAD_V_GQHYEKHS',
    value=0,
    field=NV_R_LJQBQIPV_F_FMDCUIAD
)

NV_R_GNWDBVUR = RegisterMetadata(
    name='NV_R_GNWDBVUR',
    address=0x90c
)

NV_R_GNWDBVUR_F_FMDCUIAD = FieldMetadata(
    name='NV_R_GNWDBVUR_F_FMDCUIAD',
    msb=31,
    lsb=0,
    register=NV_R_GNWDBVUR
)

NV_R_GNWDBVUR_F_FMDCUIAD_V_GQHYEKHS = ValueMetadata(
    name='NV_R_GNWDBVUR_F_FMDCUIAD_V_GQHYEKHS',
    value=0,
    field=NV_R_GNWDBVUR_F_FMDCUIAD
)

NV_R_KTYJSYOY = RegisterMetadata(
    name='NV_R_KTYJSYOY',
    address=0x904
)

NV_R_KTYJSYOY_F_IYSPMDKO = FieldMetadata(
    name='NV_R_KTYJSYOY_F_IYSPMDKO',
    msb=31,
    lsb=0,
    register=NV_R_KTYJSYOY
)

NV_R_KTYJSYOY_F_IYSPMDKO_V_GQHYEKHS = ValueMetadata(
    name='NV_R_KTYJSYOY_F_IYSPMDKO_V_GQHYEKHS',
    value=0,
    field=NV_R_KTYJSYOY_F_IYSPMDKO
)

NV_R_NPZOGJRZ = RegisterMetadata(
    name='NV_R_NPZOGJRZ',
    address=0x900
)

NV_R_NPZOGJRZ_F_PXIMDYUO = FieldMetadata(
    name='NV_R_NPZOGJRZ_F_PXIMDYUO',
    msb=29,
    lsb=0,
    register=NV_R_NPZOGJRZ
)

NV_R_NPZOGJRZ_F_PXIMDYUO_V_GQHYEKHS = ValueMetadata(
    name='NV_R_NPZOGJRZ_F_PXIMDYUO_V_GQHYEKHS',
    value=0,
    field=NV_R_NPZOGJRZ_F_PXIMDYUO
)

NV_R_NPZOGJRZ_VALID = FieldMetadata(
    name='NV_R_NPZOGJRZ_VALID',
    msb=31,
    lsb=31,
    register=NV_R_NPZOGJRZ
)

NV_R_NPZOGJRZ_VALID_FALSE = ValueMetadata(
    name='NV_R_NPZOGJRZ_VALID_FALSE',
    value=0,
    field=NV_R_NPZOGJRZ_VALID
)
NV_R_NPZOGJRZ_VALID_TRUE = ValueMetadata(
    name='NV_R_NPZOGJRZ_VALID_TRUE',
    value=1,
    field=NV_R_NPZOGJRZ_VALID
)

NV_R_NPZOGJRZ_WRITE = FieldMetadata(
    name='NV_R_NPZOGJRZ_WRITE',
    msb=30,
    lsb=30,
    register=NV_R_NPZOGJRZ
)

NV_R_NPZOGJRZ_WRITE_FALSE = ValueMetadata(
    name='NV_R_NPZOGJRZ_WRITE_FALSE',
    value=0,
    field=NV_R_NPZOGJRZ_WRITE
)
NV_R_NPZOGJRZ_WRITE_TRUE = ValueMetadata(
    name='NV_R_NPZOGJRZ_WRITE_TRUE',
    value=1,
    field=NV_R_NPZOGJRZ_WRITE
)

NV_R_YJYGJQJX = RegisterMetadata(
    name='NV_R_YJYGJQJX',
    address=0x7ec,
    debug_dump={'tags': ['pc'], 'path': 'nvlink.mse', 'samples': 1000, 'aggregation': 'histogram'}
)

NV_R_YJYGJQJX_F_MYDNDUNC = FieldMetadata(
    name='NV_R_YJYGJQJX_F_MYDNDUNC',
    msb=31,
    lsb=0,
    register=NV_R_YJYGJQJX
)

