#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata


# Register definitions
NV_R_GTKEAVOI_PRIV_LEVEL_MASK = RegisterMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK',
    address=0x8f43f0
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION',
    msb=3,
    lsb=0,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_V_HEJWCNHK = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_V_HEJWCNHK',
    value=0,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED',
    value=15,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL',
    value=8,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_V_ILPSMSOM = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_V_ILPSMSOM',
    value=12,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR',
    value=8,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0 = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0',
    msb=0,
    lsb=0,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE',
    value=0,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE',
    value=1,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1 = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1',
    msb=1,
    lsb=1,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE',
    value=0,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE',
    value=1,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2 = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2',
    msb=2,
    lsb=2,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE',
    value=0,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE',
    value=1,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3 = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3',
    msb=3,
    lsb=3,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE',
    value=0,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE',
    value=1,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_VIOLATION = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_VIOLATION',
    msb=8,
    lsb=8,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR',
    value=1,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_VIOLATION
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON',
    value=0,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_READ_VIOLATION
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_ENABLE = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_ENABLE',
    msb=31,
    lsb=12,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_GJCSBGNJ = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_GJCSBGNJ',
    value=1048575,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_ENABLE
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL',
    msb=10,
    lsb=10,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED',
    value=1,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED',
    value=0,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL',
    msb=11,
    lsb=11,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED',
    value=1,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED',
    value=0,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION',
    msb=7,
    lsb=4,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_HEJWCNHK = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_HEJWCNHK',
    value=0,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED',
    value=15,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL',
    value=8,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_ILPSMSOM = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_ILPSMSOM',
    value=12,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR',
    value=8,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0 = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0',
    msb=4,
    lsb=4,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE',
    value=0,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE',
    value=1,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1 = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1',
    msb=5,
    lsb=5,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE',
    value=0,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE',
    value=1,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2 = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2',
    msb=6,
    lsb=6,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE',
    value=0,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE',
    value=1,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3 = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3',
    msb=7,
    lsb=7,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE',
    value=0,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE',
    value=1,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_VIOLATION = FieldMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_VIOLATION',
    msb=9,
    lsb=9,
    register=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR',
    value=1,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_VIOLATION
)
NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON = ValueMetadata(
    name='NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON',
    value=0,
    field=NV_R_GTKEAVOI_PRIV_LEVEL_MASK_WRITE_VIOLATION
)

NV_R_ONLNKJIA = RegisterMetadata(
    name='NV_R_ONLNKJIA',
    address=0x8f5130,
    debug_dump={'tags': ['error'], 'interesting': {'rule': 'nonzero', 'reason': 'error status nonzero'}}
)

NV_R_ONLNKJIA_F_PXCBEXUQ = FieldMetadata(
    name='NV_R_ONLNKJIA_F_PXCBEXUQ',
    msb=8,
    lsb=8,
    register=NV_R_ONLNKJIA
)

NV_R_ONLNKJIA_F_PXCBEXUQ_V_ACRDDIMM = ValueMetadata(
    name='NV_R_ONLNKJIA_F_PXCBEXUQ_V_ACRDDIMM',
    value=1,
    field=NV_R_ONLNKJIA_F_PXCBEXUQ
)
NV_R_ONLNKJIA_F_PXCBEXUQ_FALSE = ValueMetadata(
    name='NV_R_ONLNKJIA_F_PXCBEXUQ_FALSE',
    value=0,
    field=NV_R_ONLNKJIA_F_PXCBEXUQ
)
NV_R_ONLNKJIA_F_PXCBEXUQ_TRUE = ValueMetadata(
    name='NV_R_ONLNKJIA_F_PXCBEXUQ_TRUE',
    value=1,
    field=NV_R_ONLNKJIA_F_PXCBEXUQ
)

NV_R_ONLNKJIA_F_IXCWUGWK = FieldMetadata(
    name='NV_R_ONLNKJIA_F_IXCWUGWK',
    msb=12,
    lsb=12,
    register=NV_R_ONLNKJIA
)

NV_R_ONLNKJIA_F_IXCWUGWK_V_ACRDDIMM = ValueMetadata(
    name='NV_R_ONLNKJIA_F_IXCWUGWK_V_ACRDDIMM',
    value=1,
    field=NV_R_ONLNKJIA_F_IXCWUGWK
)
NV_R_ONLNKJIA_F_IXCWUGWK_FALSE = ValueMetadata(
    name='NV_R_ONLNKJIA_F_IXCWUGWK_FALSE',
    value=0,
    field=NV_R_ONLNKJIA_F_IXCWUGWK
)
NV_R_ONLNKJIA_F_IXCWUGWK_TRUE = ValueMetadata(
    name='NV_R_ONLNKJIA_F_IXCWUGWK_TRUE',
    value=1,
    field=NV_R_ONLNKJIA_F_IXCWUGWK
)

NV_R_ONLNKJIA_F_VTCPIJDF = FieldMetadata(
    name='NV_R_ONLNKJIA_F_VTCPIJDF',
    msb=10,
    lsb=10,
    register=NV_R_ONLNKJIA
)

NV_R_ONLNKJIA_F_VTCPIJDF_V_ACRDDIMM = ValueMetadata(
    name='NV_R_ONLNKJIA_F_VTCPIJDF_V_ACRDDIMM',
    value=1,
    field=NV_R_ONLNKJIA_F_VTCPIJDF
)
NV_R_ONLNKJIA_F_VTCPIJDF_FALSE = ValueMetadata(
    name='NV_R_ONLNKJIA_F_VTCPIJDF_FALSE',
    value=0,
    field=NV_R_ONLNKJIA_F_VTCPIJDF
)
NV_R_ONLNKJIA_F_VTCPIJDF_TRUE = ValueMetadata(
    name='NV_R_ONLNKJIA_F_VTCPIJDF_TRUE',
    value=1,
    field=NV_R_ONLNKJIA_F_VTCPIJDF
)

NV_R_ONLNKJIA_F_JECCSHZH = FieldMetadata(
    name='NV_R_ONLNKJIA_F_JECCSHZH',
    msb=11,
    lsb=11,
    register=NV_R_ONLNKJIA
)

NV_R_ONLNKJIA_F_JECCSHZH_V_ACRDDIMM = ValueMetadata(
    name='NV_R_ONLNKJIA_F_JECCSHZH_V_ACRDDIMM',
    value=1,
    field=NV_R_ONLNKJIA_F_JECCSHZH
)
NV_R_ONLNKJIA_F_JECCSHZH_FALSE = ValueMetadata(
    name='NV_R_ONLNKJIA_F_JECCSHZH_FALSE',
    value=0,
    field=NV_R_ONLNKJIA_F_JECCSHZH
)
NV_R_ONLNKJIA_F_JECCSHZH_TRUE = ValueMetadata(
    name='NV_R_ONLNKJIA_F_JECCSHZH_TRUE',
    value=1,
    field=NV_R_ONLNKJIA_F_JECCSHZH
)

NV_R_ONLNKJIA_F_SLJISBLK = FieldMetadata(
    name='NV_R_ONLNKJIA_F_SLJISBLK',
    msb=0,
    lsb=0,
    register=NV_R_ONLNKJIA
)

NV_R_ONLNKJIA_F_SLJISBLK_V_ACRDDIMM = ValueMetadata(
    name='NV_R_ONLNKJIA_F_SLJISBLK_V_ACRDDIMM',
    value=1,
    field=NV_R_ONLNKJIA_F_SLJISBLK
)
NV_R_ONLNKJIA_F_SLJISBLK_FALSE = ValueMetadata(
    name='NV_R_ONLNKJIA_F_SLJISBLK_FALSE',
    value=0,
    field=NV_R_ONLNKJIA_F_SLJISBLK
)
NV_R_ONLNKJIA_F_SLJISBLK_TRUE = ValueMetadata(
    name='NV_R_ONLNKJIA_F_SLJISBLK_TRUE',
    value=1,
    field=NV_R_ONLNKJIA_F_SLJISBLK
)

NV_R_ONLNKJIA_F_BZCZRXGZ = FieldMetadata(
    name='NV_R_ONLNKJIA_F_BZCZRXGZ',
    msb=9,
    lsb=9,
    register=NV_R_ONLNKJIA
)

NV_R_ONLNKJIA_F_BZCZRXGZ_V_ACRDDIMM = ValueMetadata(
    name='NV_R_ONLNKJIA_F_BZCZRXGZ_V_ACRDDIMM',
    value=1,
    field=NV_R_ONLNKJIA_F_BZCZRXGZ
)
NV_R_ONLNKJIA_F_BZCZRXGZ_FALSE = ValueMetadata(
    name='NV_R_ONLNKJIA_F_BZCZRXGZ_FALSE',
    value=0,
    field=NV_R_ONLNKJIA_F_BZCZRXGZ
)
NV_R_ONLNKJIA_F_BZCZRXGZ_TRUE = ValueMetadata(
    name='NV_R_ONLNKJIA_F_BZCZRXGZ_TRUE',
    value=1,
    field=NV_R_ONLNKJIA_F_BZCZRXGZ
)

NV_R_CIFAYWIO = RegisterMetadata(
    name='NV_R_CIFAYWIO',
    address=0x8f66b4
)

NV_R_CIFAYWIO_F_OJYQBJXU = FieldMetadata(
    name='NV_R_CIFAYWIO_F_OJYQBJXU',
    msb=23,
    lsb=0,
    register=NV_R_CIFAYWIO
)

NV_R_CIFAYWIO_F_XFMUTNQZ = FieldMetadata(
    name='NV_R_CIFAYWIO_F_XFMUTNQZ',
    msb=15,
    lsb=0,
    register=NV_R_CIFAYWIO
)

NV_R_CIFAYWIO_F_JGDYKRTC = FieldMetadata(
    name='NV_R_CIFAYWIO_F_JGDYKRTC',
    msb=23,
    lsb=20,
    register=NV_R_CIFAYWIO
)

NV_R_CIFAYWIO_F_JGDYKRTC_V_WCVPXXHE = ValueMetadata(
    name='NV_R_CIFAYWIO_F_JGDYKRTC_V_WCVPXXHE',
    value=7,
    field=NV_R_CIFAYWIO_F_JGDYKRTC
)
NV_R_CIFAYWIO_F_JGDYKRTC_V_PNYOQAQM = ValueMetadata(
    name='NV_R_CIFAYWIO_F_JGDYKRTC_V_PNYOQAQM',
    value=3,
    field=NV_R_CIFAYWIO_F_JGDYKRTC
)
NV_R_CIFAYWIO_F_JGDYKRTC_V_KDIWUXVJ = ValueMetadata(
    name='NV_R_CIFAYWIO_F_JGDYKRTC_V_KDIWUXVJ',
    value=1,
    field=NV_R_CIFAYWIO_F_JGDYKRTC
)
NV_R_CIFAYWIO_F_JGDYKRTC_V_AIDLSZMJ = ValueMetadata(
    name='NV_R_CIFAYWIO_F_JGDYKRTC_V_AIDLSZMJ',
    value=6,
    field=NV_R_CIFAYWIO_F_JGDYKRTC
)
NV_R_CIFAYWIO_F_JGDYKRTC_V_VUSAYYPI = ValueMetadata(
    name='NV_R_CIFAYWIO_F_JGDYKRTC_V_VUSAYYPI',
    value=0,
    field=NV_R_CIFAYWIO_F_JGDYKRTC
)
NV_R_CIFAYWIO_F_JGDYKRTC_V_MZYWYLOG = ValueMetadata(
    name='NV_R_CIFAYWIO_F_JGDYKRTC_V_MZYWYLOG',
    value=2,
    field=NV_R_CIFAYWIO_F_JGDYKRTC
)
NV_R_CIFAYWIO_F_JGDYKRTC_V_EVNHGWNF = ValueMetadata(
    name='NV_R_CIFAYWIO_F_JGDYKRTC_V_EVNHGWNF',
    value=4,
    field=NV_R_CIFAYWIO_F_JGDYKRTC
)
NV_R_CIFAYWIO_F_JGDYKRTC_V_AONAKNFV = ValueMetadata(
    name='NV_R_CIFAYWIO_F_JGDYKRTC_V_AONAKNFV',
    value=5,
    field=NV_R_CIFAYWIO_F_JGDYKRTC
)

NV_R_WFOBMKJT = RegisterMetadata(
    name='NV_R_WFOBMKJT',
    address=0x8f66b8,
    debug_dump={'tags': ['error', 'ecc'], 'interesting': {'rule': 'nonzero', 'reason': 'ECC status nonzero'}}
)

NV_R_WFOBMKJT_F_CTBCFRUB = FieldMetadata(
    name='NV_R_WFOBMKJT_F_CTBCFRUB',
    msb=15,
    lsb=0,
    register=NV_R_WFOBMKJT
)

NV_R_WFOBMKJT_F_CTBCFRUB_V_GQHYEKHS = ValueMetadata(
    name='NV_R_WFOBMKJT_F_CTBCFRUB_V_GQHYEKHS',
    value=0,
    field=NV_R_WFOBMKJT_F_CTBCFRUB
)

NV_R_WFOBMKJT_F_QVYAARWP = FieldMetadata(
    name='NV_R_WFOBMKJT_F_QVYAARWP',
    msb=31,
    lsb=16,
    register=NV_R_WFOBMKJT
)

NV_R_WFOBMKJT_F_QVYAARWP_V_GQHYEKHS = ValueMetadata(
    name='NV_R_WFOBMKJT_F_QVYAARWP_V_GQHYEKHS',
    value=0,
    field=NV_R_WFOBMKJT_F_QVYAARWP
)

NV_R_BDFKBNSI = RegisterMetadata(
    name='NV_R_BDFKBNSI',
    address=0x8f66b0,
    debug_dump={'tags': ['error', 'ecc'], 'interesting': {'rule': 'nonzero', 'reason': 'ECC status nonzero'}}
)

NV_R_BDFKBNSI_F_MXXPKPJR = FieldMetadata(
    name='NV_R_BDFKBNSI_F_MXXPKPJR',
    msb=7,
    lsb=7,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_MXXPKPJR_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_MXXPKPJR_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_MXXPKPJR
)
NV_R_BDFKBNSI_F_MXXPKPJR_V_BYFONLES = ValueMetadata(
    name='NV_R_BDFKBNSI_F_MXXPKPJR_V_BYFONLES',
    value=1,
    field=NV_R_BDFKBNSI_F_MXXPKPJR
)
NV_R_BDFKBNSI_F_MXXPKPJR_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_MXXPKPJR_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_MXXPKPJR
)

NV_R_BDFKBNSI_F_LNUAVCHH = FieldMetadata(
    name='NV_R_BDFKBNSI_F_LNUAVCHH',
    msb=3,
    lsb=3,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_LNUAVCHH_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_LNUAVCHH_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_LNUAVCHH
)
NV_R_BDFKBNSI_F_LNUAVCHH_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_LNUAVCHH_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_LNUAVCHH
)
NV_R_BDFKBNSI_F_LNUAVCHH_V_PIUJQBKV = ValueMetadata(
    name='NV_R_BDFKBNSI_F_LNUAVCHH_V_PIUJQBKV',
    value=1,
    field=NV_R_BDFKBNSI_F_LNUAVCHH
)

NV_R_BDFKBNSI_F_YRPERXJI = FieldMetadata(
    name='NV_R_BDFKBNSI_F_YRPERXJI',
    msb=1,
    lsb=1,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_YRPERXJI_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_YRPERXJI_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_YRPERXJI
)
NV_R_BDFKBNSI_F_YRPERXJI_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_YRPERXJI_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_YRPERXJI
)
NV_R_BDFKBNSI_F_YRPERXJI_V_PIUJQBKV = ValueMetadata(
    name='NV_R_BDFKBNSI_F_YRPERXJI_V_PIUJQBKV',
    value=1,
    field=NV_R_BDFKBNSI_F_YRPERXJI
)

NV_R_BDFKBNSI_F_JMCISOGY = FieldMetadata(
    name='NV_R_BDFKBNSI_F_JMCISOGY',
    msb=6,
    lsb=6,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_JMCISOGY_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_JMCISOGY_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_JMCISOGY
)
NV_R_BDFKBNSI_F_JMCISOGY_V_BYFONLES = ValueMetadata(
    name='NV_R_BDFKBNSI_F_JMCISOGY_V_BYFONLES',
    value=1,
    field=NV_R_BDFKBNSI_F_JMCISOGY
)
NV_R_BDFKBNSI_F_JMCISOGY_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_JMCISOGY_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_JMCISOGY
)

NV_R_BDFKBNSI_F_JLLZSLAE = FieldMetadata(
    name='NV_R_BDFKBNSI_F_JLLZSLAE',
    msb=0,
    lsb=0,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_JLLZSLAE_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_JLLZSLAE_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_JLLZSLAE
)
NV_R_BDFKBNSI_F_JLLZSLAE_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_JLLZSLAE_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_JLLZSLAE
)
NV_R_BDFKBNSI_F_JLLZSLAE_V_PIUJQBKV = ValueMetadata(
    name='NV_R_BDFKBNSI_F_JLLZSLAE_V_PIUJQBKV',
    value=1,
    field=NV_R_BDFKBNSI_F_JLLZSLAE
)

NV_R_BDFKBNSI_F_YZFIWFYH = FieldMetadata(
    name='NV_R_BDFKBNSI_F_YZFIWFYH',
    msb=2,
    lsb=2,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_YZFIWFYH_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_YZFIWFYH_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_YZFIWFYH
)
NV_R_BDFKBNSI_F_YZFIWFYH_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_YZFIWFYH_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_YZFIWFYH
)
NV_R_BDFKBNSI_F_YZFIWFYH_V_PIUJQBKV = ValueMetadata(
    name='NV_R_BDFKBNSI_F_YZFIWFYH_V_PIUJQBKV',
    value=1,
    field=NV_R_BDFKBNSI_F_YZFIWFYH
)

NV_R_BDFKBNSI_F_HEPGGPHE = FieldMetadata(
    name='NV_R_BDFKBNSI_F_HEPGGPHE',
    msb=4,
    lsb=4,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_HEPGGPHE_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_HEPGGPHE_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_HEPGGPHE
)
NV_R_BDFKBNSI_F_HEPGGPHE_V_BYFONLES = ValueMetadata(
    name='NV_R_BDFKBNSI_F_HEPGGPHE_V_BYFONLES',
    value=1,
    field=NV_R_BDFKBNSI_F_HEPGGPHE
)
NV_R_BDFKBNSI_F_HEPGGPHE_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_HEPGGPHE_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_HEPGGPHE
)

NV_R_BDFKBNSI_F_FAKIWWMP = FieldMetadata(
    name='NV_R_BDFKBNSI_F_FAKIWWMP',
    msb=5,
    lsb=5,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_FAKIWWMP_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_FAKIWWMP_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_FAKIWWMP
)
NV_R_BDFKBNSI_F_FAKIWWMP_V_BYFONLES = ValueMetadata(
    name='NV_R_BDFKBNSI_F_FAKIWWMP_V_BYFONLES',
    value=1,
    field=NV_R_BDFKBNSI_F_FAKIWWMP
)
NV_R_BDFKBNSI_F_FAKIWWMP_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_FAKIWWMP_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_FAKIWWMP
)

NV_R_BDFKBNSI_F_OJXVVOEC = FieldMetadata(
    name='NV_R_BDFKBNSI_F_OJXVVOEC',
    msb=16,
    lsb=16,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_OJXVVOEC_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_OJXVVOEC_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_OJXVVOEC
)
NV_R_BDFKBNSI_F_OJXVVOEC_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_OJXVVOEC_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_OJXVVOEC
)
NV_R_BDFKBNSI_F_OJXVVOEC_V_PIUJQBKV = ValueMetadata(
    name='NV_R_BDFKBNSI_F_OJXVVOEC_V_PIUJQBKV',
    value=1,
    field=NV_R_BDFKBNSI_F_OJXVVOEC
)

NV_R_BDFKBNSI_F_VEOHPHHB = FieldMetadata(
    name='NV_R_BDFKBNSI_F_VEOHPHHB',
    msb=17,
    lsb=17,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_VEOHPHHB_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_VEOHPHHB_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_VEOHPHHB
)
NV_R_BDFKBNSI_F_VEOHPHHB_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_VEOHPHHB_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_VEOHPHHB
)
NV_R_BDFKBNSI_F_VEOHPHHB_V_PIUJQBKV = ValueMetadata(
    name='NV_R_BDFKBNSI_F_VEOHPHHB_V_PIUJQBKV',
    value=1,
    field=NV_R_BDFKBNSI_F_VEOHPHHB
)

NV_R_BDFKBNSI_F_KVYOKDXN = FieldMetadata(
    name='NV_R_BDFKBNSI_F_KVYOKDXN',
    msb=31,
    lsb=31,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_KVYOKDXN_V_GQHYEKHS = ValueMetadata(
    name='NV_R_BDFKBNSI_F_KVYOKDXN_V_GQHYEKHS',
    value=0,
    field=NV_R_BDFKBNSI_F_KVYOKDXN
)
NV_R_BDFKBNSI_F_KVYOKDXN_V_CIHFEZTE = ValueMetadata(
    name='NV_R_BDFKBNSI_F_KVYOKDXN_V_CIHFEZTE',
    value=1,
    field=NV_R_BDFKBNSI_F_KVYOKDXN
)

NV_R_BDFKBNSI_F_GCVXAKOX = FieldMetadata(
    name='NV_R_BDFKBNSI_F_GCVXAKOX',
    msb=15,
    lsb=15,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_GCVXAKOX_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_GCVXAKOX_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_GCVXAKOX
)
NV_R_BDFKBNSI_F_GCVXAKOX_V_BYFONLES = ValueMetadata(
    name='NV_R_BDFKBNSI_F_GCVXAKOX_V_BYFONLES',
    value=1,
    field=NV_R_BDFKBNSI_F_GCVXAKOX
)
NV_R_BDFKBNSI_F_GCVXAKOX_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_GCVXAKOX_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_GCVXAKOX
)

NV_R_BDFKBNSI_F_YYABRASA = FieldMetadata(
    name='NV_R_BDFKBNSI_F_YYABRASA',
    msb=11,
    lsb=11,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_YYABRASA_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_YYABRASA_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_YYABRASA
)
NV_R_BDFKBNSI_F_YYABRASA_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_YYABRASA_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_YYABRASA
)
NV_R_BDFKBNSI_F_YYABRASA_V_PIUJQBKV = ValueMetadata(
    name='NV_R_BDFKBNSI_F_YYABRASA_V_PIUJQBKV',
    value=1,
    field=NV_R_BDFKBNSI_F_YYABRASA
)

NV_R_BDFKBNSI_F_MFLONDNB = FieldMetadata(
    name='NV_R_BDFKBNSI_F_MFLONDNB',
    msb=9,
    lsb=9,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_MFLONDNB_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_MFLONDNB_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_MFLONDNB
)
NV_R_BDFKBNSI_F_MFLONDNB_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_MFLONDNB_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_MFLONDNB
)
NV_R_BDFKBNSI_F_MFLONDNB_V_PIUJQBKV = ValueMetadata(
    name='NV_R_BDFKBNSI_F_MFLONDNB_V_PIUJQBKV',
    value=1,
    field=NV_R_BDFKBNSI_F_MFLONDNB
)

NV_R_BDFKBNSI_F_ZOVMXOOA = FieldMetadata(
    name='NV_R_BDFKBNSI_F_ZOVMXOOA',
    msb=14,
    lsb=14,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_ZOVMXOOA_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_ZOVMXOOA_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_ZOVMXOOA
)
NV_R_BDFKBNSI_F_ZOVMXOOA_V_BYFONLES = ValueMetadata(
    name='NV_R_BDFKBNSI_F_ZOVMXOOA_V_BYFONLES',
    value=1,
    field=NV_R_BDFKBNSI_F_ZOVMXOOA
)
NV_R_BDFKBNSI_F_ZOVMXOOA_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_ZOVMXOOA_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_ZOVMXOOA
)

NV_R_BDFKBNSI_F_VYVKXHMZ = FieldMetadata(
    name='NV_R_BDFKBNSI_F_VYVKXHMZ',
    msb=8,
    lsb=8,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_VYVKXHMZ_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_VYVKXHMZ_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_VYVKXHMZ
)
NV_R_BDFKBNSI_F_VYVKXHMZ_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_VYVKXHMZ_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_VYVKXHMZ
)
NV_R_BDFKBNSI_F_VYVKXHMZ_V_PIUJQBKV = ValueMetadata(
    name='NV_R_BDFKBNSI_F_VYVKXHMZ_V_PIUJQBKV',
    value=1,
    field=NV_R_BDFKBNSI_F_VYVKXHMZ
)

NV_R_BDFKBNSI_F_EPICIITL = FieldMetadata(
    name='NV_R_BDFKBNSI_F_EPICIITL',
    msb=10,
    lsb=10,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_EPICIITL_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_EPICIITL_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_EPICIITL
)
NV_R_BDFKBNSI_F_EPICIITL_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_EPICIITL_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_EPICIITL
)
NV_R_BDFKBNSI_F_EPICIITL_V_PIUJQBKV = ValueMetadata(
    name='NV_R_BDFKBNSI_F_EPICIITL_V_PIUJQBKV',
    value=1,
    field=NV_R_BDFKBNSI_F_EPICIITL
)

NV_R_BDFKBNSI_F_JAAGIRNF = FieldMetadata(
    name='NV_R_BDFKBNSI_F_JAAGIRNF',
    msb=12,
    lsb=12,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_JAAGIRNF_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_JAAGIRNF_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_JAAGIRNF
)
NV_R_BDFKBNSI_F_JAAGIRNF_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_JAAGIRNF_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_JAAGIRNF
)
NV_R_BDFKBNSI_F_JAAGIRNF_V_PIUJQBKV = ValueMetadata(
    name='NV_R_BDFKBNSI_F_JAAGIRNF_V_PIUJQBKV',
    value=1,
    field=NV_R_BDFKBNSI_F_JAAGIRNF
)

NV_R_BDFKBNSI_F_JOVMXNLA = FieldMetadata(
    name='NV_R_BDFKBNSI_F_JOVMXNLA',
    msb=13,
    lsb=13,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_JOVMXNLA_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_JOVMXNLA_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_JOVMXNLA
)
NV_R_BDFKBNSI_F_JOVMXNLA_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_JOVMXNLA_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_JOVMXNLA
)
NV_R_BDFKBNSI_F_JOVMXNLA_V_PIUJQBKV = ValueMetadata(
    name='NV_R_BDFKBNSI_F_JOVMXNLA_V_PIUJQBKV',
    value=1,
    field=NV_R_BDFKBNSI_F_JOVMXNLA
)

NV_R_BDFKBNSI_F_WQYWMRVP = FieldMetadata(
    name='NV_R_BDFKBNSI_F_WQYWMRVP',
    msb=18,
    lsb=18,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_WQYWMRVP_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_WQYWMRVP_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_WQYWMRVP
)
NV_R_BDFKBNSI_F_WQYWMRVP_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_WQYWMRVP_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_WQYWMRVP
)
NV_R_BDFKBNSI_F_WQYWMRVP_V_PIUJQBKV = ValueMetadata(
    name='NV_R_BDFKBNSI_F_WQYWMRVP_V_PIUJQBKV',
    value=1,
    field=NV_R_BDFKBNSI_F_WQYWMRVP
)

NV_R_BDFKBNSI_F_MLEOLJIS = FieldMetadata(
    name='NV_R_BDFKBNSI_F_MLEOLJIS',
    msb=19,
    lsb=19,
    register=NV_R_BDFKBNSI
)

NV_R_BDFKBNSI_F_MLEOLJIS_V_ACRDDIMM = ValueMetadata(
    name='NV_R_BDFKBNSI_F_MLEOLJIS_V_ACRDDIMM',
    value=1,
    field=NV_R_BDFKBNSI_F_MLEOLJIS
)
NV_R_BDFKBNSI_F_MLEOLJIS_V_DOGBFDTH = ValueMetadata(
    name='NV_R_BDFKBNSI_F_MLEOLJIS_V_DOGBFDTH',
    value=0,
    field=NV_R_BDFKBNSI_F_MLEOLJIS
)
NV_R_BDFKBNSI_F_MLEOLJIS_V_PIUJQBKV = ValueMetadata(
    name='NV_R_BDFKBNSI_F_MLEOLJIS_V_PIUJQBKV',
    value=1,
    field=NV_R_BDFKBNSI_F_MLEOLJIS
)

NV_R_KXXXIBKB = RegisterMetadata(
    name='NV_R_KXXXIBKB',
    address=0x8f66bc,
    debug_dump={'tags': ['error', 'ecc'], 'interesting': {'rule': 'nonzero', 'reason': 'ECC status nonzero'}}
)

NV_R_KXXXIBKB_F_CTBCFRUB = FieldMetadata(
    name='NV_R_KXXXIBKB_F_CTBCFRUB',
    msb=15,
    lsb=0,
    register=NV_R_KXXXIBKB
)

NV_R_KXXXIBKB_F_CTBCFRUB_V_GQHYEKHS = ValueMetadata(
    name='NV_R_KXXXIBKB_F_CTBCFRUB_V_GQHYEKHS',
    value=0,
    field=NV_R_KXXXIBKB_F_CTBCFRUB
)

NV_R_KXXXIBKB_F_QVYAARWP = FieldMetadata(
    name='NV_R_KXXXIBKB_F_QVYAARWP',
    msb=31,
    lsb=16,
    register=NV_R_KXXXIBKB
)

NV_R_KXXXIBKB_F_QVYAARWP_V_GQHYEKHS = ValueMetadata(
    name='NV_R_KXXXIBKB_F_QVYAARWP_V_GQHYEKHS',
    value=0,
    field=NV_R_KXXXIBKB_F_QVYAARWP
)

NV_R_BFHTWTPV = RegisterMetadata(
    name='NV_R_BFHTWTPV',
    address=0x8f5700,
    debug_dump={'tags': ['error'], 'interesting': {'rule': 'nonzero', 'reason': 'error status nonzero'}}
)

NV_R_BFHTWTPV_F_XSITITWP = FieldMetadata(
    name='NV_R_BFHTWTPV_F_XSITITWP',
    msb=5,
    lsb=5,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_XSITITWP_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_XSITITWP_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_XSITITWP
)
NV_R_BFHTWTPV_F_XSITITWP_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_XSITITWP_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_XSITITWP
)

NV_R_BFHTWTPV_F_NTFGMFRV = FieldMetadata(
    name='NV_R_BFHTWTPV_F_NTFGMFRV',
    msb=3,
    lsb=3,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_NTFGMFRV_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_NTFGMFRV_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_NTFGMFRV
)
NV_R_BFHTWTPV_F_NTFGMFRV_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_NTFGMFRV_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_NTFGMFRV
)

NV_R_BFHTWTPV_F_ERDYHKGJ = FieldMetadata(
    name='NV_R_BFHTWTPV_F_ERDYHKGJ',
    msb=16,
    lsb=16,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_ERDYHKGJ_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_ERDYHKGJ_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_ERDYHKGJ
)
NV_R_BFHTWTPV_F_ERDYHKGJ_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_ERDYHKGJ_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_ERDYHKGJ
)

NV_R_BFHTWTPV_F_XYSQFRPO = FieldMetadata(
    name='NV_R_BFHTWTPV_F_XYSQFRPO',
    msb=17,
    lsb=17,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_XYSQFRPO_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_XYSQFRPO_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_XYSQFRPO
)
NV_R_BFHTWTPV_F_XYSQFRPO_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_XYSQFRPO_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_XYSQFRPO
)

NV_R_BFHTWTPV_F_WKWRATQY = FieldMetadata(
    name='NV_R_BFHTWTPV_F_WKWRATQY',
    msb=18,
    lsb=18,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_WKWRATQY_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_WKWRATQY_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_WKWRATQY
)
NV_R_BFHTWTPV_F_WKWRATQY_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_WKWRATQY_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_WKWRATQY
)

NV_R_BFHTWTPV_F_MOZMIYSP = FieldMetadata(
    name='NV_R_BFHTWTPV_F_MOZMIYSP',
    msb=19,
    lsb=19,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_MOZMIYSP_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_MOZMIYSP_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_MOZMIYSP
)
NV_R_BFHTWTPV_F_MOZMIYSP_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_MOZMIYSP_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_MOZMIYSP
)

NV_R_BFHTWTPV_F_WBEEKQHD = FieldMetadata(
    name='NV_R_BFHTWTPV_F_WBEEKQHD',
    msb=20,
    lsb=20,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_WBEEKQHD_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_WBEEKQHD_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_WBEEKQHD
)
NV_R_BFHTWTPV_F_WBEEKQHD_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_WBEEKQHD_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_WBEEKQHD
)

NV_R_BFHTWTPV_F_ICTIMCRO = FieldMetadata(
    name='NV_R_BFHTWTPV_F_ICTIMCRO',
    msb=21,
    lsb=21,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_ICTIMCRO_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_ICTIMCRO_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_ICTIMCRO
)
NV_R_BFHTWTPV_F_ICTIMCRO_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_ICTIMCRO_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_ICTIMCRO
)

NV_R_BFHTWTPV_F_RUWZQWRJ = FieldMetadata(
    name='NV_R_BFHTWTPV_F_RUWZQWRJ',
    msb=22,
    lsb=22,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_RUWZQWRJ_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_RUWZQWRJ_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_RUWZQWRJ
)
NV_R_BFHTWTPV_F_RUWZQWRJ_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_RUWZQWRJ_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_RUWZQWRJ
)

NV_R_BFHTWTPV_F_YXYIKXGL = FieldMetadata(
    name='NV_R_BFHTWTPV_F_YXYIKXGL',
    msb=23,
    lsb=23,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_YXYIKXGL_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_YXYIKXGL_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_YXYIKXGL
)
NV_R_BFHTWTPV_F_YXYIKXGL_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_YXYIKXGL_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_YXYIKXGL
)

NV_R_BFHTWTPV_F_OZEFPLWY = FieldMetadata(
    name='NV_R_BFHTWTPV_F_OZEFPLWY',
    msb=11,
    lsb=11,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_OZEFPLWY_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_OZEFPLWY_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_OZEFPLWY
)
NV_R_BFHTWTPV_F_OZEFPLWY_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_OZEFPLWY_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_OZEFPLWY
)

NV_R_BFHTWTPV_F_DYUSITHC = FieldMetadata(
    name='NV_R_BFHTWTPV_F_DYUSITHC',
    msb=0,
    lsb=0,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_DYUSITHC_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_DYUSITHC_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_DYUSITHC
)
NV_R_BFHTWTPV_F_DYUSITHC_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_DYUSITHC_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_DYUSITHC
)

NV_R_BFHTWTPV_F_RDNJIHYP = FieldMetadata(
    name='NV_R_BFHTWTPV_F_RDNJIHYP',
    msb=4,
    lsb=4,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_RDNJIHYP_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_RDNJIHYP_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_RDNJIHYP
)
NV_R_BFHTWTPV_F_RDNJIHYP_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_RDNJIHYP_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_RDNJIHYP
)

NV_R_BFHTWTPV_F_WEPURKBS = FieldMetadata(
    name='NV_R_BFHTWTPV_F_WEPURKBS',
    msb=2,
    lsb=2,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_WEPURKBS_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_WEPURKBS_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_WEPURKBS
)
NV_R_BFHTWTPV_F_WEPURKBS_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_WEPURKBS_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_WEPURKBS
)

NV_R_BFHTWTPV_F_FEEUZQIV = FieldMetadata(
    name='NV_R_BFHTWTPV_F_FEEUZQIV',
    msb=12,
    lsb=12,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_FEEUZQIV_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_FEEUZQIV_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_FEEUZQIV
)
NV_R_BFHTWTPV_F_FEEUZQIV_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_FEEUZQIV_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_FEEUZQIV
)

NV_R_BFHTWTPV_F_BYZDKTIS = FieldMetadata(
    name='NV_R_BFHTWTPV_F_BYZDKTIS',
    msb=7,
    lsb=7,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_BYZDKTIS_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_BYZDKTIS_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_BYZDKTIS
)
NV_R_BFHTWTPV_F_BYZDKTIS_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_BYZDKTIS_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_BYZDKTIS
)

NV_R_BFHTWTPV_F_KVZRLISQ = FieldMetadata(
    name='NV_R_BFHTWTPV_F_KVZRLISQ',
    msb=1,
    lsb=1,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_KVZRLISQ_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_KVZRLISQ_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_KVZRLISQ
)
NV_R_BFHTWTPV_F_KVZRLISQ_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_KVZRLISQ_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_KVZRLISQ
)

NV_R_BFHTWTPV_F_OHMYUUQB = FieldMetadata(
    name='NV_R_BFHTWTPV_F_OHMYUUQB',
    msb=6,
    lsb=6,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_OHMYUUQB_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_OHMYUUQB_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_OHMYUUQB
)
NV_R_BFHTWTPV_F_OHMYUUQB_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_OHMYUUQB_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_OHMYUUQB
)

NV_R_BFHTWTPV_F_EIKVWFOG = FieldMetadata(
    name='NV_R_BFHTWTPV_F_EIKVWFOG',
    msb=9,
    lsb=9,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_EIKVWFOG_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_EIKVWFOG_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_EIKVWFOG
)
NV_R_BFHTWTPV_F_EIKVWFOG_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_EIKVWFOG_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_EIKVWFOG
)

NV_R_BFHTWTPV_F_FYAHGRZR = FieldMetadata(
    name='NV_R_BFHTWTPV_F_FYAHGRZR',
    msb=8,
    lsb=8,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_FYAHGRZR_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_FYAHGRZR_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_FYAHGRZR
)
NV_R_BFHTWTPV_F_FYAHGRZR_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_FYAHGRZR_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_FYAHGRZR
)

NV_R_BFHTWTPV_F_BUIAEGFB = FieldMetadata(
    name='NV_R_BFHTWTPV_F_BUIAEGFB',
    msb=10,
    lsb=10,
    register=NV_R_BFHTWTPV
)

NV_R_BFHTWTPV_F_BUIAEGFB_V_SGMWIISS = ValueMetadata(
    name='NV_R_BFHTWTPV_F_BUIAEGFB_V_SGMWIISS',
    value=1,
    field=NV_R_BFHTWTPV_F_BUIAEGFB
)
NV_R_BFHTWTPV_F_BUIAEGFB_V_IMCKYHSN = ValueMetadata(
    name='NV_R_BFHTWTPV_F_BUIAEGFB_V_IMCKYHSN',
    value=0,
    field=NV_R_BFHTWTPV_F_BUIAEGFB
)

# Array definitions
NV_A_CKXFHFKS = ArrayMetadata(
    name='NV_A_CKXFHFKS',
    base_address=0x8f4300,
    stride=4,
    size=4,
    priv_level_mask=NV_R_GTKEAVOI_PRIV_LEVEL_MASK
)

NV_A_CKXFHFKS_F_FDJGTZTF = FieldMetadata(
    name='NV_A_CKXFHFKS_F_FDJGTZTF',
    msb=31,
    lsb=0,
    register=NV_A_CKXFHFKS
)

NV_A_CKXFHFKS_F_FDJGTZTF_V_GQHYEKHS = ValueMetadata(
    name='NV_A_CKXFHFKS_F_FDJGTZTF_V_GQHYEKHS',
    value=0,
    field=NV_A_CKXFHFKS_F_FDJGTZTF
)

