#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata


# Registers identical to gh100
from gpu.regs.gh100.therm_int import (
    NV_R_TZTTQTID_PRIV_LEVEL_MASK,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_PROTECTION,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_VIOLATION,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_SOURCE_ENABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_GJCSBGNJ,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_KKROYSLS,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_DLGZKMIW,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_ZANIRCEF,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_VIOLATION,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR,
    NV_R_TZTTQTID_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_V_ILPSMSOM,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_VIOLATION,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_SOURCE_ENABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_GJCSBGNJ,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_AJRBNDOV,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_ILPSMSOM,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_CTENPQZZ,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_VIOLATION,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR,
    NV_R_ZTCGGDUZ_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON,
    NV_THERM_I2CS_SCRATCH,
    NV_THERM_I2CS_SCRATCH_DATA,
    NV_THERM_I2CS_SCRATCH_DATA_INIT,
    NV_A_ISMWAHNU,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION_V_ILPSMSOM,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_VIOLATION,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_SOURCE_ENABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_GJCSBGNJ,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_ILPSMSOM,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_VIOLATION,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR,
    NV_A_WWTUILKV_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON,
    NV_A_ISMWAHNU_F_FDJGTZTF,
    NV_A_ISMWAHNU_F_FDJGTZTF_V_GQHYEKHS,
    NV_A_UHFGJUJP,
    NV_A_UHFGJUJP_F_FDJGTZTF,
    NV_A_UHFGJUJP_F_FDJGTZTF_V_GQHYEKHS,
)

# Register definitions
NV_R_NRELBYZA = RegisterMetadata(
    name='NV_R_NRELBYZA',
    address=0x20120,
    priv_level_mask=NV_R_TZTTQTID_PRIV_LEVEL_MASK
)

NV_R_NRELBYZA_F_QVFZOXLJ = FieldMetadata(
    name='NV_R_NRELBYZA_F_QVFZOXLJ',
    msb=30,
    lsb=0,
    register=NV_R_NRELBYZA
)

NV_R_NRELBYZA_F_QVFZOXLJ_V_GQHYEKHS = ValueMetadata(
    name='NV_R_NRELBYZA_F_QVFZOXLJ_V_GQHYEKHS',
    value=0,
    field=NV_R_NRELBYZA_F_QVFZOXLJ
)

NV_R_NRELBYZA_F_LFGRYOZH = FieldMetadata(
    name='NV_R_NRELBYZA_F_LFGRYOZH',
    msb=31,
    lsb=31,
    register=NV_R_NRELBYZA
)

NV_R_NRELBYZA_F_LFGRYOZH_FALSE = ValueMetadata(
    name='NV_R_NRELBYZA_F_LFGRYOZH_FALSE',
    value=0,
    field=NV_R_NRELBYZA_F_LFGRYOZH
)
NV_R_NRELBYZA_F_LFGRYOZH_TRUE = ValueMetadata(
    name='NV_R_NRELBYZA_F_LFGRYOZH_TRUE',
    value=1,
    field=NV_R_NRELBYZA_F_LFGRYOZH
)

