#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata

# Registers identical to gr100
from gpu.regs.gr100.top_zb import (
    NV_PTOP_ZB_DEVICE_INFO,
    NV_PTOP_ZB_DEVICE_INFO_CFG,
    NV_PTOP_ZB_DEVICE_INFO_CFG_MAX_DEVICES,
    NV_PTOP_ZB_DEVICE_INFO_CFG_MAX_DEVICES_INIT,
    NV_PTOP_ZB_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE,
    NV_PTOP_ZB_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE_INIT,
    NV_PTOP_ZB_DEVICE_INFO_CFG_NUM_ROWS,
    NV_PTOP_ZB_DEVICE_INFO_CFG_NUM_ROWS_INIT,
    NV_PTOP_ZB_DEVICE_INFO_DEV_DEVICE_BROADCAST_PRI_BASE,
    NV_PTOP_ZB_DEVICE_INFO_DEV_DEVICE_ENTRY_EXTRA,
    NV_PTOP_ZB_DEVICE_INFO_DEV_DEVICE_ENTRY_EXTRA_0,
    NV_PTOP_ZB_DEVICE_INFO_DEV_DEVICE_ENTRY_EXTRA_1,
    NV_PTOP_ZB_DEVICE_INFO_DEV_DEVICE_ENTRY_EXTRA_2,
    NV_PTOP_ZB_DEVICE_INFO_DEV_DEVICE_ENTRY_EXTRA_3_OR_MORE,
    NV_PTOP_ZB_DEVICE_INFO_DEV_DEVICE_ENTRY_FORMAT,
    NV_PTOP_ZB_DEVICE_INFO_DEV_DEVICE_ENTRY_FORMAT_BROADCAST,
    NV_PTOP_ZB_DEVICE_INFO_DEV_DEVICE_ENTRY_FORMAT_ENGINE,
    NV_PTOP_ZB_DEVICE_INFO_DEV_DEVICE_PRI_BASE,
    NV_PTOP_ZB_DEVICE_INFO_DEV_FAULT_ID,
    NV_PTOP_ZB_DEVICE_INFO_DEV_FAULT_ID_INVALID,
    NV_PTOP_ZB_DEVICE_INFO_DEV_GIN_TARGET_ID,
    NV_PTOP_ZB_DEVICE_INFO_DEV_GIN_TARGET_ID_INVALID,
    NV_PTOP_ZB_DEVICE_INFO_DEV_INSTANCE_ID,
    NV_PTOP_ZB_DEVICE_INFO_DEV_RLENG_ID,
    NV_PTOP_ZB_DEVICE_INFO_DEV_RSVD,
    NV_PTOP_ZB_DEVICE_INFO_DEV_RSVD_VALUE,
    NV_PTOP_ZB_DEVICE_INFO_DEV_RUNLIST_PRI_BASE,
    NV_PTOP_ZB_DEVICE_INFO_DEV_TYPE_ENUM,
    NV_PTOP_ZB_DEVICE_INFO_DEV_TYPE_ENUM_FBHUB,
    NV_PTOP_ZB_DEVICE_INFO_DEV_TYPE_ENUM_FBPA,
    NV_PTOP_ZB_DEVICE_INFO_DEV_TYPE_ENUM_FBPA_CLKS,
    NV_PTOP_ZB_DEVICE_INFO_DEV_TYPE_ENUM_HSHUB,
    NV_PTOP_ZB_DEVICE_INFO_DEV_TYPE_ENUM_HSHUBMMU,
    NV_PTOP_ZB_DEVICE_INFO_DEV_TYPE_ENUM_HUBMMU,
    NV_PTOP_ZB_DEVICE_INFO_DEV_TYPE_ENUM_L2SLICE,
    NV_PTOP_ZB_DEVICE_INFO_DEV_TYPE_ENUM_LTC,
    NV_PTOP_ZB_DEVICE_INFO_DEV_TYPE_ENUM_NVLPW,
    NV_PTOP_ZB_DEVICE_INFO_DEV_TYPE_ENUM_SYSLTC,
    NV_PTOP_ZB_DEVICE_INFO_ROW_VALUE,
    NV_PTOP_ZB_DEVICE_INFO_ROW_VALUE_INVALID,
    NV_PTOP_ZB_NEXT_PTOP_PRI_BASE,
    NV_PTOP_ZB_NEXT_PTOP_PRI_BASE_VALUE,
    NV_PTOP_ZB_NEXT_PTOP_PRI_BASE_VALUE_NULL,
    NV_PTOP_ZB_NEXT_PTOP_PRI_BASE_VALUE_UGD0,
)

