#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata


# Registers identical to gb100
from gpu.regs.gb100.gsp_int import (
    NV_R_UTAXXXPZ,
    NV_R_UTAXXXPZ_F_XSITITWP,
    NV_R_UTAXXXPZ_F_XSITITWP_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_XSITITWP_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_NTFGMFRV,
    NV_R_UTAXXXPZ_F_NTFGMFRV_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_NTFGMFRV_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_ERDYHKGJ,
    NV_R_UTAXXXPZ_F_ERDYHKGJ_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_ERDYHKGJ_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_XYSQFRPO,
    NV_R_UTAXXXPZ_F_XYSQFRPO_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_XYSQFRPO_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_WKWRATQY,
    NV_R_UTAXXXPZ_F_WKWRATQY_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_WKWRATQY_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_MOZMIYSP,
    NV_R_UTAXXXPZ_F_MOZMIYSP_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_MOZMIYSP_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_WBEEKQHD,
    NV_R_UTAXXXPZ_F_WBEEKQHD_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_WBEEKQHD_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_ICTIMCRO,
    NV_R_UTAXXXPZ_F_ICTIMCRO_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_ICTIMCRO_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_RUWZQWRJ,
    NV_R_UTAXXXPZ_F_RUWZQWRJ_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_RUWZQWRJ_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_YXYIKXGL,
    NV_R_UTAXXXPZ_F_YXYIKXGL_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_YXYIKXGL_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_OZEFPLWY,
    NV_R_UTAXXXPZ_F_OZEFPLWY_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_OZEFPLWY_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_DYUSITHC,
    NV_R_UTAXXXPZ_F_DYUSITHC_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_DYUSITHC_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_RDNJIHYP,
    NV_R_UTAXXXPZ_F_RDNJIHYP_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_RDNJIHYP_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_WEPURKBS,
    NV_R_UTAXXXPZ_F_WEPURKBS_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_WEPURKBS_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_FEEUZQIV,
    NV_R_UTAXXXPZ_F_FEEUZQIV_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_FEEUZQIV_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_BYZDKTIS,
    NV_R_UTAXXXPZ_F_BYZDKTIS_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_BYZDKTIS_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_KVZRLISQ,
    NV_R_UTAXXXPZ_F_KVZRLISQ_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_KVZRLISQ_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_OHMYUUQB,
    NV_R_UTAXXXPZ_F_OHMYUUQB_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_OHMYUUQB_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_EIKVWFOG,
    NV_R_UTAXXXPZ_F_EIKVWFOG_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_EIKVWFOG_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_FYAHGRZR,
    NV_R_UTAXXXPZ_F_FYAHGRZR_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_FYAHGRZR_V_IMCKYHSN,
    NV_R_UTAXXXPZ_F_BUIAEGFB,
    NV_R_UTAXXXPZ_F_BUIAEGFB_V_SGMWIISS,
    NV_R_UTAXXXPZ_F_BUIAEGFB_V_IMCKYHSN,
)

# Registers identical to gh100
from gpu.regs.gh100.gsp_int import (
    NV_R_YXCJNNGA,
    NV_R_YXCJNNGA_F_PXCBEXUQ,
    NV_R_YXCJNNGA_F_PXCBEXUQ_V_ACRDDIMM,
    NV_R_YXCJNNGA_F_PXCBEXUQ_FALSE,
    NV_R_YXCJNNGA_F_PXCBEXUQ_TRUE,
    NV_R_YXCJNNGA_F_IXCWUGWK,
    NV_R_YXCJNNGA_F_IXCWUGWK_V_ACRDDIMM,
    NV_R_YXCJNNGA_F_IXCWUGWK_FALSE,
    NV_R_YXCJNNGA_F_IXCWUGWK_TRUE,
    NV_R_YXCJNNGA_F_VTCPIJDF,
    NV_R_YXCJNNGA_F_VTCPIJDF_V_ACRDDIMM,
    NV_R_YXCJNNGA_F_VTCPIJDF_FALSE,
    NV_R_YXCJNNGA_F_VTCPIJDF_TRUE,
    NV_R_YXCJNNGA_F_JECCSHZH,
    NV_R_YXCJNNGA_F_JECCSHZH_V_ACRDDIMM,
    NV_R_YXCJNNGA_F_JECCSHZH_FALSE,
    NV_R_YXCJNNGA_F_JECCSHZH_TRUE,
    NV_R_YXCJNNGA_F_SLJISBLK,
    NV_R_YXCJNNGA_F_SLJISBLK_V_ACRDDIMM,
    NV_R_YXCJNNGA_F_SLJISBLK_FALSE,
    NV_R_YXCJNNGA_F_SLJISBLK_TRUE,
    NV_R_YXCJNNGA_F_BZCZRXGZ,
    NV_R_YXCJNNGA_F_BZCZRXGZ_V_ACRDDIMM,
    NV_R_YXCJNNGA_F_BZCZRXGZ_FALSE,
    NV_R_YXCJNNGA_F_BZCZRXGZ_TRUE,
)

