#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata


# Registers identical to gb100
from gpu.regs.gb100.ir_int import (
    NV_R_VNICEGYY,
    NV_R_VNICEGYY_F_AUUPAXHZ,
    NV_R_VNICEGYY_F_AUUPAXHZ_V_ZRRJKDVX,
    NV_R_VNICEGYY_F_REDTGIDZ,
    NV_R_VNICEGYY_F_REDTGIDZ_V_ZRRJKDVX,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK_READ_PROTECTION,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK_READ_PROTECTION_V_ZRRJKDVX,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK_READ_VIOLATION,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK_READ_VIOLATION_V_ZRRJKDVX,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK_SOURCE_ENABLE,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_ZRRJKDVX,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_V_ZRRJKDVX,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_V_ZRRJKDVX,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK_WRITE_PROTECTION,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_ZRRJKDVX,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK_WRITE_VIOLATION,
    NV_R_NSSUPEIW_PRIV_LEVEL_MASK_WRITE_VIOLATION_V_ZRRJKDVX,
    NV_R_VNICEGYY_F_QZQAGPDP,
    NV_R_VNICEGYY_F_QZQAGPDP_V_ZRRJKDVX,
    NV_R_VNICEGYY_F_FWGUVILY,
    NV_R_VNICEGYY_F_FWGUVILY_V_ZRRJKDVX,
    NV_R_VNICEGYY_F_WHRWJGMO,
    NV_R_VNICEGYY_F_WHRWJGMO_V_ZRRJKDVX,
    NV_R_TTGMCXQP,
    NV_R_TTGMCXQP_F_PXIMDYUO,
    NV_R_TTGMCXQP_F_PXIMDYUO_V_ZRRJKDVX,
    NV_R_TTGMCXQP_VALID,
    NV_R_TTGMCXQP_VALID_V_ZRRJKDVX,
    NV_R_STSPSEPZ,
    NV_R_STSPSEPZ_F_AQFWRERE,
    NV_R_STSPSEPZ_F_AQFWRERE_V_ZRRJKDVX,
    NV_R_STSPSEPZ_F_WXNDRGMV,
    NV_R_STSPSEPZ_F_WXNDRGMV_V_ZRRJKDVX,
    NV_R_STSPSEPZ_F_HGPEBRTD,
    NV_R_STSPSEPZ_F_HGPEBRTD_V_ZRRJKDVX,
    NV_R_STSPSEPZ_F_TTDEBOJC,
    NV_R_STSPSEPZ_F_TTDEBOJC_V_ZRRJKDVX,
    NV_R_STSPSEPZ_F_WXLVGPLS,
    NV_R_STSPSEPZ_F_WXLVGPLS_V_ZRRJKDVX,
    NV_R_STSPSEPZ_F_GZUNECFA,
    NV_R_STSPSEPZ_F_GZUNECFA_V_ZRRJKDVX,
    NV_R_LJHTJOLZ,
    NV_R_LJHTJOLZ_F_FMDCUIAD,
    NV_R_LJHTJOLZ_F_FMDCUIAD_V_ZRRJKDVX,
    NV_R_WOHJOTQL,
    NV_R_WOHJOTQL_F_FMDCUIAD,
    NV_R_WOHJOTQL_F_FMDCUIAD_V_ZRRJKDVX,
    NV_R_PCBTKNXJ,
    NV_R_PCBTKNXJ_F_IYSPMDKO,
    NV_R_PCBTKNXJ_F_IYSPMDKO_V_ZRRJKDVX,
    NV_R_KDYBKKQJ,
    NV_R_KDYBKKQJ_F_PXIMDYUO,
    NV_R_KDYBKKQJ_F_PXIMDYUO_V_ZRRJKDVX,
    NV_R_KDYBKKQJ_VALID,
    NV_R_KDYBKKQJ_VALID_V_ZRRJKDVX,
    NV_R_KDYBKKQJ_WRITE,
    NV_R_KDYBKKQJ_WRITE_V_ZRRJKDVX,
    NV_R_ELPQHXVO,
    NV_R_ELPQHXVO_F_MYDNDUNC,
    NV_R_YPVCNZDM,
    NV_R_YPVCNZDM_F_AUUPAXHZ,
    NV_R_YPVCNZDM_F_AUUPAXHZ_V_ZRRJKDVX,
    NV_R_YPVCNZDM_F_REDTGIDZ,
    NV_R_YPVCNZDM_F_REDTGIDZ_V_ZRRJKDVX,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK_READ_PROTECTION,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK_READ_PROTECTION_V_ZRRJKDVX,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK_READ_VIOLATION,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK_READ_VIOLATION_V_ZRRJKDVX,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK_SOURCE_ENABLE,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_ZRRJKDVX,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_V_ZRRJKDVX,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_V_ZRRJKDVX,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK_WRITE_PROTECTION,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_ZRRJKDVX,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK_WRITE_VIOLATION,
    NV_R_XQNYUKHU_PRIV_LEVEL_MASK_WRITE_VIOLATION_V_ZRRJKDVX,
    NV_R_YPVCNZDM_F_QZQAGPDP,
    NV_R_YPVCNZDM_F_QZQAGPDP_V_ZRRJKDVX,
    NV_R_YPVCNZDM_F_FWGUVILY,
    NV_R_YPVCNZDM_F_FWGUVILY_V_ZRRJKDVX,
    NV_R_YPVCNZDM_F_WHRWJGMO,
    NV_R_YPVCNZDM_F_WHRWJGMO_V_ZRRJKDVX,
    NV_R_QTXXHYWI,
    NV_R_QTXXHYWI_F_PXIMDYUO,
    NV_R_QTXXHYWI_F_PXIMDYUO_V_ZRRJKDVX,
    NV_R_QTXXHYWI_VALID,
    NV_R_QTXXHYWI_VALID_V_ZRRJKDVX,
    NV_R_FSWWCPCY,
    NV_R_FSWWCPCY_F_AQFWRERE,
    NV_R_FSWWCPCY_F_AQFWRERE_V_ZRRJKDVX,
    NV_R_FSWWCPCY_F_WXNDRGMV,
    NV_R_FSWWCPCY_F_WXNDRGMV_V_ZRRJKDVX,
    NV_R_FSWWCPCY_F_HGPEBRTD,
    NV_R_FSWWCPCY_F_HGPEBRTD_V_ZRRJKDVX,
    NV_R_FSWWCPCY_F_TTDEBOJC,
    NV_R_FSWWCPCY_F_TTDEBOJC_V_ZRRJKDVX,
    NV_R_FSWWCPCY_F_WXLVGPLS,
    NV_R_FSWWCPCY_F_WXLVGPLS_V_ZRRJKDVX,
    NV_R_FSWWCPCY_F_GZUNECFA,
    NV_R_FSWWCPCY_F_GZUNECFA_V_ZRRJKDVX,
    NV_R_VTBTRZNA,
    NV_R_VTBTRZNA_F_FMDCUIAD,
    NV_R_VTBTRZNA_F_FMDCUIAD_V_ZRRJKDVX,
    NV_R_IZYKEUUL,
    NV_R_IZYKEUUL_F_FMDCUIAD,
    NV_R_IZYKEUUL_F_FMDCUIAD_V_ZRRJKDVX,
    NV_R_YRXCKMBR,
    NV_R_YRXCKMBR_F_IYSPMDKO,
    NV_R_YRXCKMBR_F_IYSPMDKO_V_ZRRJKDVX,
    NV_R_BILYNUIP,
    NV_R_BILYNUIP_F_PXIMDYUO,
    NV_R_BILYNUIP_F_PXIMDYUO_V_ZRRJKDVX,
    NV_R_BILYNUIP_VALID,
    NV_R_BILYNUIP_VALID_V_ZRRJKDVX,
    NV_R_BILYNUIP_WRITE,
    NV_R_BILYNUIP_WRITE_V_ZRRJKDVX,
    NV_R_UJFQYDOQ,
    NV_R_UJFQYDOQ_F_MYDNDUNC,
    NV_R_RWEJDRRM,
    NV_R_RWEJDRRM_F_AUUPAXHZ,
    NV_R_RWEJDRRM_F_AUUPAXHZ_V_ZRRJKDVX,
    NV_R_RWEJDRRM_F_REDTGIDZ,
    NV_R_RWEJDRRM_F_REDTGIDZ_V_ZRRJKDVX,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK_READ_PROTECTION,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK_READ_PROTECTION_V_ZRRJKDVX,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK_READ_VIOLATION,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK_READ_VIOLATION_V_ZRRJKDVX,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK_SOURCE_ENABLE,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_ZRRJKDVX,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_V_ZRRJKDVX,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_V_ZRRJKDVX,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK_WRITE_PROTECTION,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_ZRRJKDVX,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK_WRITE_VIOLATION,
    NV_R_UWDZGSFU_PRIV_LEVEL_MASK_WRITE_VIOLATION_V_ZRRJKDVX,
    NV_R_RWEJDRRM_F_QZQAGPDP,
    NV_R_RWEJDRRM_F_QZQAGPDP_V_ZRRJKDVX,
    NV_R_RWEJDRRM_F_FWGUVILY,
    NV_R_RWEJDRRM_F_FWGUVILY_V_ZRRJKDVX,
    NV_R_RWEJDRRM_F_WHRWJGMO,
    NV_R_RWEJDRRM_F_WHRWJGMO_V_ZRRJKDVX,
    NV_R_DJCICOEA,
    NV_R_DJCICOEA_F_PXIMDYUO,
    NV_R_DJCICOEA_F_PXIMDYUO_V_ZRRJKDVX,
    NV_R_DJCICOEA_VALID,
    NV_R_DJCICOEA_VALID_V_ZRRJKDVX,
    NV_R_ZOWCMTPS,
    NV_R_ZOWCMTPS_F_AQFWRERE,
    NV_R_ZOWCMTPS_F_AQFWRERE_V_ZRRJKDVX,
    NV_R_ZOWCMTPS_F_WXNDRGMV,
    NV_R_ZOWCMTPS_F_WXNDRGMV_V_ZRRJKDVX,
    NV_R_ZOWCMTPS_F_HGPEBRTD,
    NV_R_ZOWCMTPS_F_HGPEBRTD_V_ZRRJKDVX,
    NV_R_ZOWCMTPS_F_TTDEBOJC,
    NV_R_ZOWCMTPS_F_TTDEBOJC_V_ZRRJKDVX,
    NV_R_ZOWCMTPS_F_WXLVGPLS,
    NV_R_ZOWCMTPS_F_WXLVGPLS_V_ZRRJKDVX,
    NV_R_ZOWCMTPS_F_GZUNECFA,
    NV_R_ZOWCMTPS_F_GZUNECFA_V_ZRRJKDVX,
    NV_R_FDUWOCYR,
    NV_R_FDUWOCYR_F_FMDCUIAD,
    NV_R_FDUWOCYR_F_FMDCUIAD_V_ZRRJKDVX,
    NV_R_NYNKFBPK,
    NV_R_NYNKFBPK_F_FMDCUIAD,
    NV_R_NYNKFBPK_F_FMDCUIAD_V_ZRRJKDVX,
    NV_R_KIYCHXFK,
    NV_R_KIYCHXFK_F_IYSPMDKO,
    NV_R_KIYCHXFK_F_IYSPMDKO_V_ZRRJKDVX,
    NV_R_UPLZCDYK,
    NV_R_UPLZCDYK_F_PXIMDYUO,
    NV_R_UPLZCDYK_F_PXIMDYUO_V_ZRRJKDVX,
    NV_R_UPLZCDYK_VALID,
    NV_R_UPLZCDYK_VALID_V_ZRRJKDVX,
    NV_R_UPLZCDYK_WRITE,
    NV_R_UPLZCDYK_WRITE_V_ZRRJKDVX,
    NV_R_MCDKKRBG,
    NV_R_MCDKKRBG_F_MYDNDUNC,
    NV_R_LQUNLRMR,
    NV_R_LQUNLRMR_F_AUUPAXHZ,
    NV_R_LQUNLRMR_F_AUUPAXHZ_V_ZRRJKDVX,
    NV_R_LQUNLRMR_F_REDTGIDZ,
    NV_R_LQUNLRMR_F_REDTGIDZ_V_ZRRJKDVX,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK_READ_PROTECTION,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK_READ_PROTECTION_V_ZRRJKDVX,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK_READ_VIOLATION,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK_READ_VIOLATION_V_ZRRJKDVX,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK_SOURCE_ENABLE,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_ZRRJKDVX,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_V_ZRRJKDVX,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_V_ZRRJKDVX,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK_WRITE_PROTECTION,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_ZRRJKDVX,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK_WRITE_VIOLATION,
    NV_R_TCVDBRXJ_PRIV_LEVEL_MASK_WRITE_VIOLATION_V_ZRRJKDVX,
    NV_R_LQUNLRMR_F_QZQAGPDP,
    NV_R_LQUNLRMR_F_QZQAGPDP_V_ZRRJKDVX,
    NV_R_LQUNLRMR_F_FWGUVILY,
    NV_R_LQUNLRMR_F_FWGUVILY_V_ZRRJKDVX,
    NV_R_LQUNLRMR_F_WHRWJGMO,
    NV_R_LQUNLRMR_F_WHRWJGMO_V_ZRRJKDVX,
    NV_R_VXGWAHOX,
    NV_R_VXGWAHOX_F_PXIMDYUO,
    NV_R_VXGWAHOX_F_PXIMDYUO_V_ZRRJKDVX,
    NV_R_VXGWAHOX_VALID,
    NV_R_VXGWAHOX_VALID_V_ZRRJKDVX,
    NV_R_IJJCEDMT,
    NV_R_IJJCEDMT_F_AQFWRERE,
    NV_R_IJJCEDMT_F_AQFWRERE_V_ZRRJKDVX,
    NV_R_IJJCEDMT_F_WXNDRGMV,
    NV_R_IJJCEDMT_F_WXNDRGMV_V_ZRRJKDVX,
    NV_R_IJJCEDMT_F_HGPEBRTD,
    NV_R_IJJCEDMT_F_HGPEBRTD_V_ZRRJKDVX,
    NV_R_IJJCEDMT_F_TTDEBOJC,
    NV_R_IJJCEDMT_F_TTDEBOJC_V_ZRRJKDVX,
    NV_R_IJJCEDMT_F_WXLVGPLS,
    NV_R_IJJCEDMT_F_WXLVGPLS_V_ZRRJKDVX,
    NV_R_IJJCEDMT_F_GZUNECFA,
    NV_R_IJJCEDMT_F_GZUNECFA_V_ZRRJKDVX,
    NV_R_DDWJOZIG,
    NV_R_DDWJOZIG_F_FMDCUIAD,
    NV_R_DDWJOZIG_F_FMDCUIAD_V_ZRRJKDVX,
    NV_R_GUZPRMLE,
    NV_R_GUZPRMLE_F_FMDCUIAD,
    NV_R_GUZPRMLE_F_FMDCUIAD_V_ZRRJKDVX,
    NV_R_LEDITTSI,
    NV_R_LEDITTSI_F_IYSPMDKO,
    NV_R_LEDITTSI_F_IYSPMDKO_V_ZRRJKDVX,
    NV_R_BVEDRQNP,
    NV_R_BVEDRQNP_F_PXIMDYUO,
    NV_R_BVEDRQNP_F_PXIMDYUO_V_ZRRJKDVX,
    NV_R_BVEDRQNP_VALID,
    NV_R_BVEDRQNP_VALID_V_ZRRJKDVX,
    NV_R_BVEDRQNP_WRITE,
    NV_R_BVEDRQNP_WRITE_V_ZRRJKDVX,
    NV_R_XOATKXOJ,
    NV_R_XOATKXOJ_F_MYDNDUNC,
)

# Register definitions
NV_R_TYAFUCNG_PRIV_LEVEL_MASK = RegisterMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK',
    address=0x8708
)

NV_R_TYAFUCNG_PRIV_LEVEL_MASK_READ_PROTECTION = FieldMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK_READ_PROTECTION',
    msb=3,
    lsb=0,
    register=NV_R_TYAFUCNG_PRIV_LEVEL_MASK
)

NV_R_TYAFUCNG_PRIV_LEVEL_MASK_READ_PROTECTION_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK_READ_PROTECTION_V_ZRRJKDVX',
    value=15,
    field=NV_R_TYAFUCNG_PRIV_LEVEL_MASK_READ_PROTECTION
)

NV_R_TYAFUCNG_PRIV_LEVEL_MASK_READ_VIOLATION = FieldMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK_READ_VIOLATION',
    msb=8,
    lsb=8,
    register=NV_R_TYAFUCNG_PRIV_LEVEL_MASK
)

NV_R_TYAFUCNG_PRIV_LEVEL_MASK_READ_VIOLATION_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK_READ_VIOLATION_V_ZRRJKDVX',
    value=1,
    field=NV_R_TYAFUCNG_PRIV_LEVEL_MASK_READ_VIOLATION
)

NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_ENABLE = FieldMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_ENABLE',
    msb=31,
    lsb=12,
    register=NV_R_TYAFUCNG_PRIV_LEVEL_MASK
)

NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_ZRRJKDVX',
    value=1048575,
    field=NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_ENABLE
)

NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL = FieldMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL',
    msb=10,
    lsb=10,
    register=NV_R_TYAFUCNG_PRIV_LEVEL_MASK
)

NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_V_ZRRJKDVX',
    value=1,
    field=NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)

NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL = FieldMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL',
    msb=11,
    lsb=11,
    register=NV_R_TYAFUCNG_PRIV_LEVEL_MASK
)

NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_V_ZRRJKDVX',
    value=1,
    field=NV_R_TYAFUCNG_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)

NV_R_TYAFUCNG_PRIV_LEVEL_MASK_WRITE_PROTECTION = FieldMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK_WRITE_PROTECTION',
    msb=7,
    lsb=4,
    register=NV_R_TYAFUCNG_PRIV_LEVEL_MASK
)

NV_R_TYAFUCNG_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_ZRRJKDVX',
    value=15,
    field=NV_R_TYAFUCNG_PRIV_LEVEL_MASK_WRITE_PROTECTION
)

NV_R_TYAFUCNG_PRIV_LEVEL_MASK_WRITE_VIOLATION = FieldMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK_WRITE_VIOLATION',
    msb=9,
    lsb=9,
    register=NV_R_TYAFUCNG_PRIV_LEVEL_MASK
)

NV_R_TYAFUCNG_PRIV_LEVEL_MASK_WRITE_VIOLATION_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_TYAFUCNG_PRIV_LEVEL_MASK_WRITE_VIOLATION_V_ZRRJKDVX',
    value=1,
    field=NV_R_TYAFUCNG_PRIV_LEVEL_MASK_WRITE_VIOLATION
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK = RegisterMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK',
    address=0xa708
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK_READ_PROTECTION = FieldMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK_READ_PROTECTION',
    msb=3,
    lsb=0,
    register=NV_R_WKQJAUAF_PRIV_LEVEL_MASK
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK_READ_PROTECTION_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK_READ_PROTECTION_V_ZRRJKDVX',
    value=15,
    field=NV_R_WKQJAUAF_PRIV_LEVEL_MASK_READ_PROTECTION
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK_READ_VIOLATION = FieldMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK_READ_VIOLATION',
    msb=8,
    lsb=8,
    register=NV_R_WKQJAUAF_PRIV_LEVEL_MASK
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK_READ_VIOLATION_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK_READ_VIOLATION_V_ZRRJKDVX',
    value=1,
    field=NV_R_WKQJAUAF_PRIV_LEVEL_MASK_READ_VIOLATION
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_ENABLE = FieldMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_ENABLE',
    msb=31,
    lsb=12,
    register=NV_R_WKQJAUAF_PRIV_LEVEL_MASK
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_ZRRJKDVX',
    value=1048575,
    field=NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_ENABLE
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL = FieldMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL',
    msb=10,
    lsb=10,
    register=NV_R_WKQJAUAF_PRIV_LEVEL_MASK
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_V_ZRRJKDVX',
    value=1,
    field=NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL = FieldMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL',
    msb=11,
    lsb=11,
    register=NV_R_WKQJAUAF_PRIV_LEVEL_MASK
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_V_ZRRJKDVX',
    value=1,
    field=NV_R_WKQJAUAF_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK_WRITE_PROTECTION = FieldMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK_WRITE_PROTECTION',
    msb=7,
    lsb=4,
    register=NV_R_WKQJAUAF_PRIV_LEVEL_MASK
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_ZRRJKDVX',
    value=15,
    field=NV_R_WKQJAUAF_PRIV_LEVEL_MASK_WRITE_PROTECTION
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK_WRITE_VIOLATION = FieldMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK_WRITE_VIOLATION',
    msb=9,
    lsb=9,
    register=NV_R_WKQJAUAF_PRIV_LEVEL_MASK
)

NV_R_WKQJAUAF_PRIV_LEVEL_MASK_WRITE_VIOLATION_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_WKQJAUAF_PRIV_LEVEL_MASK_WRITE_VIOLATION_V_ZRRJKDVX',
    value=1,
    field=NV_R_WKQJAUAF_PRIV_LEVEL_MASK_WRITE_VIOLATION
)

NV_R_MVKKROXA = RegisterMetadata(
    name='NV_R_MVKKROXA',
    address=0x8788
)

NV_R_MVKKROXA_F_AUUPAXHZ = FieldMetadata(
    name='NV_R_MVKKROXA_F_AUUPAXHZ',
    msb=7,
    lsb=7,
    register=NV_R_MVKKROXA
)

NV_R_MVKKROXA_F_AUUPAXHZ_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_MVKKROXA_F_AUUPAXHZ_V_ZRRJKDVX',
    value=0,
    field=NV_R_MVKKROXA_F_AUUPAXHZ
)

NV_R_MVKKROXA_F_REDTGIDZ = FieldMetadata(
    name='NV_R_MVKKROXA_F_REDTGIDZ',
    msb=4,
    lsb=4,
    register=NV_R_MVKKROXA
)

NV_R_MVKKROXA_F_REDTGIDZ_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_MVKKROXA_F_REDTGIDZ_V_ZRRJKDVX',
    value=1,
    field=NV_R_MVKKROXA_F_REDTGIDZ
)

NV_R_MVKKROXA_F_QZQAGPDP = FieldMetadata(
    name='NV_R_MVKKROXA_F_QZQAGPDP',
    msb=0,
    lsb=0,
    register=NV_R_MVKKROXA
)

NV_R_MVKKROXA_F_QZQAGPDP_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_MVKKROXA_F_QZQAGPDP_V_ZRRJKDVX',
    value=0,
    field=NV_R_MVKKROXA_F_QZQAGPDP
)

NV_R_MVKKROXA_F_FWGUVILY = FieldMetadata(
    name='NV_R_MVKKROXA_F_FWGUVILY',
    msb=10,
    lsb=8,
    register=NV_R_MVKKROXA
)

NV_R_MVKKROXA_F_FWGUVILY_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_MVKKROXA_F_FWGUVILY_V_ZRRJKDVX',
    value=0,
    field=NV_R_MVKKROXA_F_FWGUVILY
)

NV_R_MVKKROXA_F_WHRWJGMO = FieldMetadata(
    name='NV_R_MVKKROXA_F_WHRWJGMO',
    msb=5,
    lsb=5,
    register=NV_R_MVKKROXA
)

NV_R_MVKKROXA_F_WHRWJGMO_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_MVKKROXA_F_WHRWJGMO_V_ZRRJKDVX',
    value=0,
    field=NV_R_MVKKROXA_F_WHRWJGMO
)

NV_R_SAPXVIFO = RegisterMetadata(
    name='NV_R_SAPXVIFO',
    address=0x8830
)

NV_R_SAPXVIFO_F_PXIMDYUO = FieldMetadata(
    name='NV_R_SAPXVIFO_F_PXIMDYUO',
    msb=30,
    lsb=0,
    register=NV_R_SAPXVIFO
)

NV_R_SAPXVIFO_F_PXIMDYUO_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_SAPXVIFO_F_PXIMDYUO_V_ZRRJKDVX',
    value=0,
    field=NV_R_SAPXVIFO_F_PXIMDYUO
)

NV_R_SAPXVIFO_VALID = FieldMetadata(
    name='NV_R_SAPXVIFO_VALID',
    msb=31,
    lsb=31,
    register=NV_R_SAPXVIFO
)

NV_R_SAPXVIFO_VALID_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_SAPXVIFO_VALID_V_ZRRJKDVX',
    value=0,
    field=NV_R_SAPXVIFO_VALID
)

NV_R_PDRATIOR = RegisterMetadata(
    name='NV_R_PDRATIOR',
    address=0x8794,
    debug_dump={'tags': ['intr_status'], 'path': 'nvlink.netir', 'samples': 1000}
)

NV_R_PDRATIOR_F_AQFWRERE = FieldMetadata(
    name='NV_R_PDRATIOR_F_AQFWRERE',
    msb=1,
    lsb=1,
    register=NV_R_PDRATIOR
)

NV_R_PDRATIOR_F_AQFWRERE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_PDRATIOR_F_AQFWRERE_V_ZRRJKDVX',
    value=0,
    field=NV_R_PDRATIOR_F_AQFWRERE
)

NV_R_PDRATIOR_F_WXNDRGMV = FieldMetadata(
    name='NV_R_PDRATIOR_F_WXNDRGMV',
    msb=2,
    lsb=2,
    register=NV_R_PDRATIOR
)

NV_R_PDRATIOR_F_WXNDRGMV_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_PDRATIOR_F_WXNDRGMV_V_ZRRJKDVX',
    value=0,
    field=NV_R_PDRATIOR_F_WXNDRGMV
)

NV_R_PDRATIOR_F_HGPEBRTD = FieldMetadata(
    name='NV_R_PDRATIOR_F_HGPEBRTD',
    msb=4,
    lsb=4,
    register=NV_R_PDRATIOR
)

NV_R_PDRATIOR_F_HGPEBRTD_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_PDRATIOR_F_HGPEBRTD_V_ZRRJKDVX',
    value=0,
    field=NV_R_PDRATIOR_F_HGPEBRTD
)

NV_R_PDRATIOR_F_TTDEBOJC = FieldMetadata(
    name='NV_R_PDRATIOR_F_TTDEBOJC',
    msb=5,
    lsb=5,
    register=NV_R_PDRATIOR
)

NV_R_PDRATIOR_F_TTDEBOJC_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_PDRATIOR_F_TTDEBOJC_V_ZRRJKDVX',
    value=0,
    field=NV_R_PDRATIOR_F_TTDEBOJC
)

NV_R_PDRATIOR_F_WXLVGPLS = FieldMetadata(
    name='NV_R_PDRATIOR_F_WXLVGPLS',
    msb=3,
    lsb=3,
    register=NV_R_PDRATIOR
)

NV_R_PDRATIOR_F_WXLVGPLS_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_PDRATIOR_F_WXLVGPLS_V_ZRRJKDVX',
    value=0,
    field=NV_R_PDRATIOR_F_WXLVGPLS
)

NV_R_PDRATIOR_F_GZUNECFA = FieldMetadata(
    name='NV_R_PDRATIOR_F_GZUNECFA',
    msb=0,
    lsb=0,
    register=NV_R_PDRATIOR
)

NV_R_PDRATIOR_F_GZUNECFA_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_PDRATIOR_F_GZUNECFA_V_ZRRJKDVX',
    value=0,
    field=NV_R_PDRATIOR_F_GZUNECFA
)

NV_R_KONYZFGB = RegisterMetadata(
    name='NV_R_KONYZFGB',
    address=0x8828
)

NV_R_KONYZFGB_F_FMDCUIAD = FieldMetadata(
    name='NV_R_KONYZFGB_F_FMDCUIAD',
    msb=31,
    lsb=0,
    register=NV_R_KONYZFGB
)

NV_R_KONYZFGB_F_FMDCUIAD_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_KONYZFGB_F_FMDCUIAD_V_ZRRJKDVX',
    value=0,
    field=NV_R_KONYZFGB_F_FMDCUIAD
)

NV_R_JIOHSZWU = RegisterMetadata(
    name='NV_R_JIOHSZWU',
    address=0x882c
)

NV_R_JIOHSZWU_F_FMDCUIAD = FieldMetadata(
    name='NV_R_JIOHSZWU_F_FMDCUIAD',
    msb=31,
    lsb=0,
    register=NV_R_JIOHSZWU
)

NV_R_JIOHSZWU_F_FMDCUIAD_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_JIOHSZWU_F_FMDCUIAD_V_ZRRJKDVX',
    value=0,
    field=NV_R_JIOHSZWU_F_FMDCUIAD
)

NV_R_OVDITTQP = RegisterMetadata(
    name='NV_R_OVDITTQP',
    address=0x8824
)

NV_R_OVDITTQP_F_IYSPMDKO = FieldMetadata(
    name='NV_R_OVDITTQP_F_IYSPMDKO',
    msb=31,
    lsb=0,
    register=NV_R_OVDITTQP
)

NV_R_OVDITTQP_F_IYSPMDKO_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_OVDITTQP_F_IYSPMDKO_V_ZRRJKDVX',
    value=0,
    field=NV_R_OVDITTQP_F_IYSPMDKO
)

NV_R_ZLBXNLOT = RegisterMetadata(
    name='NV_R_ZLBXNLOT',
    address=0x8820
)

NV_R_ZLBXNLOT_F_PXIMDYUO = FieldMetadata(
    name='NV_R_ZLBXNLOT_F_PXIMDYUO',
    msb=29,
    lsb=0,
    register=NV_R_ZLBXNLOT
)

NV_R_ZLBXNLOT_F_PXIMDYUO_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_ZLBXNLOT_F_PXIMDYUO_V_ZRRJKDVX',
    value=0,
    field=NV_R_ZLBXNLOT_F_PXIMDYUO
)

NV_R_ZLBXNLOT_VALID = FieldMetadata(
    name='NV_R_ZLBXNLOT_VALID',
    msb=31,
    lsb=31,
    register=NV_R_ZLBXNLOT
)

NV_R_ZLBXNLOT_VALID_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_ZLBXNLOT_VALID_V_ZRRJKDVX',
    value=0,
    field=NV_R_ZLBXNLOT_VALID
)

NV_R_ZLBXNLOT_WRITE = FieldMetadata(
    name='NV_R_ZLBXNLOT_WRITE',
    msb=30,
    lsb=30,
    register=NV_R_ZLBXNLOT
)

NV_R_ZLBXNLOT_WRITE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_ZLBXNLOT_WRITE_V_ZRRJKDVX',
    value=0,
    field=NV_R_ZLBXNLOT_WRITE
)

NV_R_EPVOKKLE = RegisterMetadata(
    name='NV_R_EPVOKKLE',
    address=0x87ec,
    debug_dump={'tags': ['pc'], 'path': 'nvlink.netir', 'samples': 1000, 'aggregation': 'histogram'}
)

NV_R_EPVOKKLE_F_MYDNDUNC = FieldMetadata(
    name='NV_R_EPVOKKLE_F_MYDNDUNC',
    msb=31,
    lsb=0,
    register=NV_R_EPVOKKLE
)

NV_R_HUUBRVFL = RegisterMetadata(
    name='NV_R_HUUBRVFL',
    address=0xa788
)

NV_R_HUUBRVFL_F_AUUPAXHZ = FieldMetadata(
    name='NV_R_HUUBRVFL_F_AUUPAXHZ',
    msb=7,
    lsb=7,
    register=NV_R_HUUBRVFL
)

NV_R_HUUBRVFL_F_AUUPAXHZ_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_HUUBRVFL_F_AUUPAXHZ_V_ZRRJKDVX',
    value=0,
    field=NV_R_HUUBRVFL_F_AUUPAXHZ
)

NV_R_HUUBRVFL_F_REDTGIDZ = FieldMetadata(
    name='NV_R_HUUBRVFL_F_REDTGIDZ',
    msb=4,
    lsb=4,
    register=NV_R_HUUBRVFL
)

NV_R_HUUBRVFL_F_REDTGIDZ_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_HUUBRVFL_F_REDTGIDZ_V_ZRRJKDVX',
    value=1,
    field=NV_R_HUUBRVFL_F_REDTGIDZ
)

NV_R_HUUBRVFL_F_QZQAGPDP = FieldMetadata(
    name='NV_R_HUUBRVFL_F_QZQAGPDP',
    msb=0,
    lsb=0,
    register=NV_R_HUUBRVFL
)

NV_R_HUUBRVFL_F_QZQAGPDP_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_HUUBRVFL_F_QZQAGPDP_V_ZRRJKDVX',
    value=0,
    field=NV_R_HUUBRVFL_F_QZQAGPDP
)

NV_R_HUUBRVFL_F_FWGUVILY = FieldMetadata(
    name='NV_R_HUUBRVFL_F_FWGUVILY',
    msb=10,
    lsb=8,
    register=NV_R_HUUBRVFL
)

NV_R_HUUBRVFL_F_FWGUVILY_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_HUUBRVFL_F_FWGUVILY_V_ZRRJKDVX',
    value=0,
    field=NV_R_HUUBRVFL_F_FWGUVILY
)

NV_R_HUUBRVFL_F_WHRWJGMO = FieldMetadata(
    name='NV_R_HUUBRVFL_F_WHRWJGMO',
    msb=5,
    lsb=5,
    register=NV_R_HUUBRVFL
)

NV_R_HUUBRVFL_F_WHRWJGMO_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_HUUBRVFL_F_WHRWJGMO_V_ZRRJKDVX',
    value=0,
    field=NV_R_HUUBRVFL_F_WHRWJGMO
)

NV_R_BNAKUSMA = RegisterMetadata(
    name='NV_R_BNAKUSMA',
    address=0xa830
)

NV_R_BNAKUSMA_F_PXIMDYUO = FieldMetadata(
    name='NV_R_BNAKUSMA_F_PXIMDYUO',
    msb=30,
    lsb=0,
    register=NV_R_BNAKUSMA
)

NV_R_BNAKUSMA_F_PXIMDYUO_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_BNAKUSMA_F_PXIMDYUO_V_ZRRJKDVX',
    value=0,
    field=NV_R_BNAKUSMA_F_PXIMDYUO
)

NV_R_BNAKUSMA_VALID = FieldMetadata(
    name='NV_R_BNAKUSMA_VALID',
    msb=31,
    lsb=31,
    register=NV_R_BNAKUSMA
)

NV_R_BNAKUSMA_VALID_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_BNAKUSMA_VALID_V_ZRRJKDVX',
    value=0,
    field=NV_R_BNAKUSMA_VALID
)

NV_R_ZPOQIYBX = RegisterMetadata(
    name='NV_R_ZPOQIYBX',
    address=0xa794,
    debug_dump={'tags': ['intr_status'], 'path': 'nvlink.netir', 'samples': 1000}
)

NV_R_ZPOQIYBX_F_AQFWRERE = FieldMetadata(
    name='NV_R_ZPOQIYBX_F_AQFWRERE',
    msb=1,
    lsb=1,
    register=NV_R_ZPOQIYBX
)

NV_R_ZPOQIYBX_F_AQFWRERE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_ZPOQIYBX_F_AQFWRERE_V_ZRRJKDVX',
    value=0,
    field=NV_R_ZPOQIYBX_F_AQFWRERE
)

NV_R_ZPOQIYBX_F_WXNDRGMV = FieldMetadata(
    name='NV_R_ZPOQIYBX_F_WXNDRGMV',
    msb=2,
    lsb=2,
    register=NV_R_ZPOQIYBX
)

NV_R_ZPOQIYBX_F_WXNDRGMV_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_ZPOQIYBX_F_WXNDRGMV_V_ZRRJKDVX',
    value=0,
    field=NV_R_ZPOQIYBX_F_WXNDRGMV
)

NV_R_ZPOQIYBX_F_HGPEBRTD = FieldMetadata(
    name='NV_R_ZPOQIYBX_F_HGPEBRTD',
    msb=4,
    lsb=4,
    register=NV_R_ZPOQIYBX
)

NV_R_ZPOQIYBX_F_HGPEBRTD_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_ZPOQIYBX_F_HGPEBRTD_V_ZRRJKDVX',
    value=0,
    field=NV_R_ZPOQIYBX_F_HGPEBRTD
)

NV_R_ZPOQIYBX_F_TTDEBOJC = FieldMetadata(
    name='NV_R_ZPOQIYBX_F_TTDEBOJC',
    msb=5,
    lsb=5,
    register=NV_R_ZPOQIYBX
)

NV_R_ZPOQIYBX_F_TTDEBOJC_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_ZPOQIYBX_F_TTDEBOJC_V_ZRRJKDVX',
    value=0,
    field=NV_R_ZPOQIYBX_F_TTDEBOJC
)

NV_R_ZPOQIYBX_F_WXLVGPLS = FieldMetadata(
    name='NV_R_ZPOQIYBX_F_WXLVGPLS',
    msb=3,
    lsb=3,
    register=NV_R_ZPOQIYBX
)

NV_R_ZPOQIYBX_F_WXLVGPLS_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_ZPOQIYBX_F_WXLVGPLS_V_ZRRJKDVX',
    value=0,
    field=NV_R_ZPOQIYBX_F_WXLVGPLS
)

NV_R_ZPOQIYBX_F_GZUNECFA = FieldMetadata(
    name='NV_R_ZPOQIYBX_F_GZUNECFA',
    msb=0,
    lsb=0,
    register=NV_R_ZPOQIYBX
)

NV_R_ZPOQIYBX_F_GZUNECFA_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_ZPOQIYBX_F_GZUNECFA_V_ZRRJKDVX',
    value=0,
    field=NV_R_ZPOQIYBX_F_GZUNECFA
)

NV_R_SXXDEJIO = RegisterMetadata(
    name='NV_R_SXXDEJIO',
    address=0xa828
)

NV_R_SXXDEJIO_F_FMDCUIAD = FieldMetadata(
    name='NV_R_SXXDEJIO_F_FMDCUIAD',
    msb=31,
    lsb=0,
    register=NV_R_SXXDEJIO
)

NV_R_SXXDEJIO_F_FMDCUIAD_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_SXXDEJIO_F_FMDCUIAD_V_ZRRJKDVX',
    value=0,
    field=NV_R_SXXDEJIO_F_FMDCUIAD
)

NV_R_BCFRZLFO = RegisterMetadata(
    name='NV_R_BCFRZLFO',
    address=0xa82c
)

NV_R_BCFRZLFO_F_FMDCUIAD = FieldMetadata(
    name='NV_R_BCFRZLFO_F_FMDCUIAD',
    msb=31,
    lsb=0,
    register=NV_R_BCFRZLFO
)

NV_R_BCFRZLFO_F_FMDCUIAD_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_BCFRZLFO_F_FMDCUIAD_V_ZRRJKDVX',
    value=0,
    field=NV_R_BCFRZLFO_F_FMDCUIAD
)

NV_R_PHHEWYIF = RegisterMetadata(
    name='NV_R_PHHEWYIF',
    address=0xa824
)

NV_R_PHHEWYIF_F_IYSPMDKO = FieldMetadata(
    name='NV_R_PHHEWYIF_F_IYSPMDKO',
    msb=31,
    lsb=0,
    register=NV_R_PHHEWYIF
)

NV_R_PHHEWYIF_F_IYSPMDKO_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_PHHEWYIF_F_IYSPMDKO_V_ZRRJKDVX',
    value=0,
    field=NV_R_PHHEWYIF_F_IYSPMDKO
)

NV_R_HKRDLYGC = RegisterMetadata(
    name='NV_R_HKRDLYGC',
    address=0xa820
)

NV_R_HKRDLYGC_F_PXIMDYUO = FieldMetadata(
    name='NV_R_HKRDLYGC_F_PXIMDYUO',
    msb=29,
    lsb=0,
    register=NV_R_HKRDLYGC
)

NV_R_HKRDLYGC_F_PXIMDYUO_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_HKRDLYGC_F_PXIMDYUO_V_ZRRJKDVX',
    value=0,
    field=NV_R_HKRDLYGC_F_PXIMDYUO
)

NV_R_HKRDLYGC_VALID = FieldMetadata(
    name='NV_R_HKRDLYGC_VALID',
    msb=31,
    lsb=31,
    register=NV_R_HKRDLYGC
)

NV_R_HKRDLYGC_VALID_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_HKRDLYGC_VALID_V_ZRRJKDVX',
    value=0,
    field=NV_R_HKRDLYGC_VALID
)

NV_R_HKRDLYGC_WRITE = FieldMetadata(
    name='NV_R_HKRDLYGC_WRITE',
    msb=30,
    lsb=30,
    register=NV_R_HKRDLYGC
)

NV_R_HKRDLYGC_WRITE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_HKRDLYGC_WRITE_V_ZRRJKDVX',
    value=0,
    field=NV_R_HKRDLYGC_WRITE
)

NV_R_HRJDXBPZ = RegisterMetadata(
    name='NV_R_HRJDXBPZ',
    address=0xa7ec,
    debug_dump={'tags': ['pc'], 'path': 'nvlink.netir', 'samples': 1000, 'aggregation': 'histogram'}
)

NV_R_HRJDXBPZ_F_MYDNDUNC = FieldMetadata(
    name='NV_R_HRJDXBPZ_F_MYDNDUNC',
    msb=31,
    lsb=0,
    register=NV_R_HRJDXBPZ
)

