#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata


# Registers identical to gb100
from gpu.regs.gb100.top_int import (
    NV_R_XUCNPTBX,
    NV_R_GQVBSDVG,
    NV_R_JTQKSVDA,
    NV_R_RDNJPILZ,
    NV_R_UDJLVDHF,
    NV_R_SZHFIVFO,
    NV_R_FEBLKDFN,
    NV_R_QHESAHFP,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_VIOLATION,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_YVMXOYBP,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_VIOLATION,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON,
)

# Registers identical to gb202
from gpu.regs.gb202.top_int import (
    NV_R_CUYACIFH,
    NV_R_CUYACIFH_VALUE,
    NV_R_CUYACIFH_VALUE_V_ZRRJKDVX,
    NV_R_SXKEOIBW,
    NV_R_SXKEOIBW_VALUE,
    NV_R_SXKEOIBW_VALUE_V_ZRRJKDVX,
    NV_R_AFPSKUZI,
    NV_R_AFPSKUZI_VALUE,
    NV_R_AFPSKUZI_VALUE_V_ZRRJKDVX,
    NV_R_HMQJWADN,
    NV_R_HMQJWADN_VALUE,
    NV_R_HMQJWADN_VALUE_V_ZRRJKDVX,
    NV_R_WTQAYGOT,
    NV_R_WTQAYGOT_VALUE,
    NV_R_WTQAYGOT_VALUE_V_ZRRJKDVX,
    NV_R_MALHPZWJ,
    NV_R_MALHPZWJ_VALUE,
    NV_R_MALHPZWJ_VALUE_V_ZRRJKDVX,
    NV_R_JVHVALTL,
    NV_R_JVHVALTL_VALUE,
    NV_R_JVHVALTL_VALUE_V_ZRRJKDVX,
    NV_R_GMOCCARV,
    NV_R_GMOCCARV_VALUE,
    NV_R_GMOCCARV_VALUE_V_ZRRJKDVX,
    NV_R_RLGXXLDD,
    NV_R_RLGXXLDD_VALUE,
    NV_R_RLGXXLDD_VALUE_V_ZRRJKDVX,
    NV_R_MGENATIB,
    NV_R_MGENATIB_VALUE,
    NV_R_MGENATIB_VALUE_V_ZRRJKDVX,
    NV_R_FXMSYJMF,
    NV_R_FXMSYJMF_VALUE,
    NV_R_FXMSYJMF_VALUE_V_ZRRJKDVX,
    NV_R_QIDNGOVJ,
    NV_R_QIDNGOVJ_VALUE,
    NV_R_QIDNGOVJ_VALUE_V_ZRRJKDVX,
    NV_R_UKNWXHHW,
    NV_R_UKNWXHHW_VALUE,
    NV_R_UKNWXHHW_VALUE_V_ZRRJKDVX,
    NV_R_MUMMKQCM,
    NV_R_MUMMKQCM_VALUE,
    NV_R_MUMMKQCM_VALUE_V_ZRRJKDVX,
    NV_R_ZNEWYGRA,
    NV_R_ZNEWYGRA_VALUE,
    NV_R_ZNEWYGRA_VALUE_V_ZRRJKDVX,
    NV_R_KYKLMRFE,
    NV_R_KYKLMRFE_VALUE,
    NV_R_KYKLMRFE_VALUE_V_ZRRJKDVX,
    NV_R_TWHJUYMI,
    NV_R_TWHJUYMI_VALUE,
    NV_R_TWHJUYMI_VALUE_V_ZRRJKDVX,
    NV_R_KMZTDFMK,
    NV_R_KMZTDFMK_VALUE,
    NV_R_KMZTDFMK_VALUE_V_ZRRJKDVX,
    NV_R_VNLAJASY,
    NV_R_VNLAJASY_VALUE,
    NV_R_VNLAJASY_VALUE_V_ZRRJKDVX,
    NV_R_LMSCCKQD,
    NV_R_LMSCCKQD_VALUE,
    NV_R_LMSCCKQD_VALUE_V_ZRRJKDVX,
    NV_R_UTWVFXBK,
    NV_R_UTWVFXBK_VALUE,
    NV_R_UTWVFXBK_VALUE_V_ZRRJKDVX,
    NV_R_HTYAWCIU,
    NV_R_HTYAWCIU_VALUE,
    NV_R_HTYAWCIU_VALUE_V_ZRRJKDVX,
)

# Registers identical to gh100
from gpu.regs.gh100.top_int import (
    NV_R_PWZXFNWW,
    NV_R_PWZXFNWW_F_SDHCEVQG,
    NV_R_PWZXFNWW_F_SDHCEVQG_V_ZRRJKDVX,
    NV_R_PWZXFNWW_F_SDHCEVQG_V_GQHYEKHS,
    NV_R_ZEZRECZW,
    NV_R_ZEZRECZW_VALUE,
    NV_R_ZEZRECZW_VALUE_V_ZRRJKDVX,
)

# Register definitions
NV_R_VZBTKBHD_PRIV_LEVEL_MASK = RegisterMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK',
    address=0x224f4
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION',
    msb=3,
    lsb=0,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED',
    value=15,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL',
    value=15,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR',
    value=8,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0 = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0',
    msb=0,
    lsb=0,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE',
    value=0,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE',
    value=1,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1 = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1',
    msb=1,
    lsb=1,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE',
    value=0,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE',
    value=1,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2 = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2',
    msb=2,
    lsb=2,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE',
    value=0,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE',
    value=1,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3 = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3',
    msb=3,
    lsb=3,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE',
    value=0,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE',
    value=1,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_VIOLATION = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_VIOLATION',
    msb=8,
    lsb=8,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR',
    value=1,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_VIOLATION
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON',
    value=0,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_VIOLATION
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_ENABLE = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_ENABLE',
    msb=31,
    lsb=12,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_KRGKDGXO = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_KRGKDGXO',
    value=2112,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_ENABLE
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL',
    msb=10,
    lsb=10,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED',
    value=1,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED',
    value=0,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL',
    msb=11,
    lsb=11,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED',
    value=1,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED',
    value=0,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION',
    msb=7,
    lsb=4,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED',
    value=15,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL',
    value=8,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR',
    value=8,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0 = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0',
    msb=4,
    lsb=4,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE',
    value=0,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE',
    value=1,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1 = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1',
    msb=5,
    lsb=5,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE',
    value=0,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE',
    value=1,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2 = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2',
    msb=6,
    lsb=6,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE',
    value=0,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE',
    value=1,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3 = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3',
    msb=7,
    lsb=7,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE',
    value=0,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE',
    value=1,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_VIOLATION = FieldMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_VIOLATION',
    msb=9,
    lsb=9,
    register=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR',
    value=1,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_VIOLATION
)
NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON = ValueMetadata(
    name='NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON',
    value=0,
    field=NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_VIOLATION
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK = RegisterMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK',
    address=0x22404
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION',
    msb=3,
    lsb=0,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED',
    value=15,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL',
    value=15,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR',
    value=8,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0',
    msb=0,
    lsb=0,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1',
    msb=1,
    lsb=1,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2',
    msb=2,
    lsb=2,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3',
    msb=3,
    lsb=3,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION',
    msb=8,
    lsb=8,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_ENABLE = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_ENABLE',
    msb=31,
    lsb=12,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_YVMXOYBP = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_YVMXOYBP',
    value=1048575,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_ENABLE
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL',
    msb=10,
    lsb=10,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL',
    msb=11,
    lsb=11,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION',
    msb=7,
    lsb=4,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED',
    value=15,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL',
    value=15,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR',
    value=8,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0',
    msb=4,
    lsb=4,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1',
    msb=5,
    lsb=5,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2',
    msb=6,
    lsb=6,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3',
    msb=7,
    lsb=7,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION',
    msb=9,
    lsb=9,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION
)

NV_PTOP_DEVICE_INFO_CFG = RegisterMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG',
    address=0x224fc,
    priv_level_mask=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES',
    msb=15,
    lsb=4,
    register=NV_PTOP_DEVICE_INFO_CFG
)

NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES_INIT = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES_INIT',
    value=272,
    field=NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES
)

NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE',
    msb=19,
    lsb=16,
    register=NV_PTOP_DEVICE_INFO_CFG
)

NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE_INIT = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE_INIT',
    value=3,
    field=NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE
)

NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS',
    msb=31,
    lsb=20,
    register=NV_PTOP_DEVICE_INFO_CFG
)

NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS_INIT = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS_INIT',
    value=635,
    field=NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS
)

NV_R_PDFAHZGR = RegisterMetadata(
    name='NV_R_PDFAHZGR',
    address=0x224f0
)

NV_R_PDFAHZGR_F_CZRFXHNC = FieldMetadata(
    name='NV_R_PDFAHZGR_F_CZRFXHNC',
    msb=16,
    lsb=16,
    register=NV_R_PDFAHZGR
)

NV_R_PDFAHZGR_F_CZRFXHNC_V_QTKSVURH = ValueMetadata(
    name='NV_R_PDFAHZGR_F_CZRFXHNC_V_QTKSVURH',
    value=0,
    field=NV_R_PDFAHZGR_F_CZRFXHNC
)
NV_R_PDFAHZGR_F_CZRFXHNC_V_SKNFIXFF = ValueMetadata(
    name='NV_R_PDFAHZGR_F_CZRFXHNC_V_SKNFIXFF',
    value=1,
    field=NV_R_PDFAHZGR_F_CZRFXHNC
)

NV_R_PDFAHZGR_F_JGDYKRTC = FieldMetadata(
    name='NV_R_PDFAHZGR_F_JGDYKRTC',
    msb=1,
    lsb=0,
    register=NV_R_PDFAHZGR
)

NV_R_PDFAHZGR_F_JGDYKRTC_V_AFGYJNEO = ValueMetadata(
    name='NV_R_PDFAHZGR_F_JGDYKRTC_V_AFGYJNEO',
    value=1,
    field=NV_R_PDFAHZGR_F_JGDYKRTC
)
NV_R_PDFAHZGR_F_JGDYKRTC_V_BUAUXLOJ = ValueMetadata(
    name='NV_R_PDFAHZGR_F_JGDYKRTC_V_BUAUXLOJ',
    value=2,
    field=NV_R_PDFAHZGR_F_JGDYKRTC
)
NV_R_PDFAHZGR_F_JGDYKRTC_V_QZNIXSNR = ValueMetadata(
    name='NV_R_PDFAHZGR_F_JGDYKRTC_V_QZNIXSNR',
    value=0,
    field=NV_R_PDFAHZGR_F_JGDYKRTC
)

NV_R_ZUPOMPFW = RegisterMetadata(
    name='NV_R_ZUPOMPFW',
    address=0x22484
)

NV_R_ZUPOMPFW_VALUE = FieldMetadata(
    name='NV_R_ZUPOMPFW_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_ZUPOMPFW
)

NV_R_ZUPOMPFW_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_ZUPOMPFW_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_ZUPOMPFW_VALUE
)

# Array definitions
NV_A_KOIOESYK = ArrayMetadata(
    name='NV_A_KOIOESYK',
    base_address=0x22800,
    stride=4,
    size=222,
    priv_level_mask=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_A_KOIOESYK_DEV_DEVICE_BROADCAST_PRI_BASE = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_DEVICE_BROADCAST_PRI_BASE',
    msb=95,
    lsb=66,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_DEVICE_ENTRY_EXTRA = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_DEVICE_ENTRY_EXTRA',
    msb=33,
    lsb=32,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_DEVICE_ENTRY_EXTRA_V_MYYBDNJR = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_DEVICE_ENTRY_EXTRA_V_MYYBDNJR',
    value=0,
    field=NV_A_KOIOESYK_DEV_DEVICE_ENTRY_EXTRA
)
NV_A_KOIOESYK_DEV_DEVICE_ENTRY_EXTRA_V_UTEHBTJA = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_DEVICE_ENTRY_EXTRA_V_UTEHBTJA',
    value=1,
    field=NV_A_KOIOESYK_DEV_DEVICE_ENTRY_EXTRA
)
NV_A_KOIOESYK_DEV_DEVICE_ENTRY_EXTRA_V_LKHJGBTQ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_DEVICE_ENTRY_EXTRA_V_LKHJGBTQ',
    value=2,
    field=NV_A_KOIOESYK_DEV_DEVICE_ENTRY_EXTRA
)
NV_A_KOIOESYK_DEV_DEVICE_ENTRY_EXTRA_V_AZJLLVVI = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_DEVICE_ENTRY_EXTRA_V_AZJLLVVI',
    value=3,
    field=NV_A_KOIOESYK_DEV_DEVICE_ENTRY_EXTRA
)

NV_A_KOIOESYK_DEV_DEVICE_ENTRY_FORMAT = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_DEVICE_ENTRY_FORMAT',
    msb=64,
    lsb=64,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_DEVICE_ENTRY_FORMAT_V_XRNBWDLO = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_DEVICE_ENTRY_FORMAT_V_XRNBWDLO',
    value=0,
    field=NV_A_KOIOESYK_DEV_DEVICE_ENTRY_FORMAT
)
NV_A_KOIOESYK_DEV_DEVICE_ENTRY_FORMAT_V_AAWMOUEA = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_DEVICE_ENTRY_FORMAT_V_AAWMOUEA',
    value=1,
    field=NV_A_KOIOESYK_DEV_DEVICE_ENTRY_FORMAT
)

NV_A_KOIOESYK_DEV_DEVICE_PRI_BASE = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_DEVICE_PRI_BASE',
    msb=63,
    lsb=34,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_FAULT_ID = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_FAULT_ID',
    msb=11,
    lsb=0,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_FAULT_ID_INVALID = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_FAULT_ID_INVALID',
    value=0,
    field=NV_A_KOIOESYK_DEV_FAULT_ID
)

NV_A_KOIOESYK_DEV_GIN_TARGET_ID = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_GIN_TARGET_ID',
    msb=16,
    lsb=12,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_GIN_TARGET_ID_INVALID = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_GIN_TARGET_ID_INVALID',
    value=31,
    field=NV_A_KOIOESYK_DEV_GIN_TARGET_ID
)

NV_A_KOIOESYK_DEV_INSTANCE_ID = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_INSTANCE_ID',
    msb=24,
    lsb=17,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_RLENG_ID = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_RLENG_ID',
    msb=67,
    lsb=66,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_RSVD = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_RSVD',
    msb=65,
    lsb=65,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_RSVD_VALUE = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_RSVD_VALUE',
    value=0,
    field=NV_A_KOIOESYK_DEV_RSVD
)

NV_A_KOIOESYK_DEV_RUNLIST_PRI_BASE = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_RUNLIST_PRI_BASE',
    msb=95,
    lsb=68,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_TYPE_ENUM = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM',
    msb=31,
    lsb=25,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_TYPE_ENUM_V_HCWXSYBM = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_HCWXSYBM',
    value=43,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_RVLKEJWH = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_RVLKEJWH',
    value=25,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ZFTDRKPW = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ZFTDRKPW',
    value=47,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_CZFXNUUF = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_CZFXNUUF',
    value=64,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_HMOVKBYF = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_HMOVKBYF',
    value=33,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_FSQGVUMX = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_FSQGVUMX',
    value=78,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ESQECSMQ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ESQECSMQ',
    value=55,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BYUPLPQF = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BYUPLPQF',
    value=87,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_LPREGITL = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_LPREGITL',
    value=69,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_DKSQOGZB = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_DKSQOGZB',
    value=63,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_AUMDBSXC = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_AUMDBSXC',
    value=27,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_JLEWMCBH = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_JLEWMCBH',
    value=84,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_UUPOQUVQ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_UUPOQUVQ',
    value=81,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_TWZFQXII = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_TWZFQXII',
    value=85,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_EDYSWBTK = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_EDYSWBTK',
    value=71,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_UOZWLQWO = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_UOZWLQWO',
    value=23,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_UDSNKUFQ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_UDSNKUFQ',
    value=26,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_LXZKRGMA = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_LXZKRGMA',
    value=34,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_TCNOOWJU = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_TCNOOWJU',
    value=41,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_PZLHMKFG = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_PZLHMKFG',
    value=30,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ICDPTQHG = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ICDPTQHG',
    value=76,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_MMYFGKPS = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_MMYFGKPS',
    value=70,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_GOCSCMKA = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_GOCSCMKA',
    value=0,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_LWBHHXKA = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_LWBHHXKA',
    value=20,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_WTHDKXVG = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_WTHDKXVG',
    value=57,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_GFNCQPKZ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_GFNCQPKZ',
    value=56,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ULTEJTQR = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ULTEJTQR',
    value=73,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_YPWVVQTV = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_YPWVVQTV',
    value=24,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_KKNDLMWG = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_KKNDLMWG',
    value=32,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_WVIQLUWD = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_WVIQLUWD',
    value=53,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_EHKYSREA = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_EHKYSREA',
    value=18,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_FZGTLDMH = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_FZGTLDMH',
    value=74,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_HPADJAUZ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_HPADJAUZ',
    value=75,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_LXGHDGQH = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_LXGHDGQH',
    value=54,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_JJKKDWDQ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_JJKKDWDQ',
    value=44,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_UHWAZRER = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_UHWAZRER',
    value=83,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ADOFRLBI = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ADOFRLBI',
    value=19,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_YHXUPSGP = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_YHXUPSGP',
    value=82,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_WUUBOBZK = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_WUUBOBZK',
    value=68,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_KUIVBHDV = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_KUIVBHDV',
    value=67,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_JPNCPYGI = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_JPNCPYGI',
    value=58,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_STKTDZMV = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_STKTDZMV',
    value=59,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_GIUXYEQN = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_GIUXYEQN',
    value=16,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_NVYOLSKM = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_NVYOLSKM',
    value=14,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_NIPQQHPC = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_NIPQQHPC',
    value=21,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_DMQZBYEC = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_DMQZBYEC',
    value=29,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_EBBCMTRV = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_EBBCMTRV',
    value=72,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_EFTKKQKC = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_EFTKKQKC',
    value=28,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BTTVDGGR = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BTTVDGGR',
    value=65,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BNYIUTBN = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BNYIUTBN',
    value=22,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_CJLFIBAN = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_CJLFIBAN',
    value=86,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BBVOGXOS = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BBVOGXOS',
    value=51,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_FWRPESEF = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_FWRPESEF',
    value=80,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_RYWEOWVQ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_RYWEOWVQ',
    value=46,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_YKLTYEHD = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_YKLTYEHD',
    value=50,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_KKZDHCFZ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_KKZDHCFZ',
    value=35,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_HHBOOTBJ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_HHBOOTBJ',
    value=88,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_VNQBIHKN = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_VNQBIHKN',
    value=39,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_MFPBDEFG = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_MFPBDEFG',
    value=38,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BGCAQFFS = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BGCAQFFS',
    value=52,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_MDOERWXC = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_MDOERWXC',
    value=42,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BHATVHAV = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BHATVHAV',
    value=79,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_NSDPVTAV = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_NSDPVTAV',
    value=13,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_AIWIVARW = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_AIWIVARW',
    value=40,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_JKGYEQWV = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_JKGYEQWV',
    value=62,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ATROBEKO = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ATROBEKO',
    value=48,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_MYUKYXBZ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_MYUKYXBZ',
    value=49,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_QJZABYTD = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_QJZABYTD',
    value=66,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_WJJRMTCR = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_WJJRMTCR',
    value=36,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_YMDFXFXY = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_YMDFXFXY',
    value=37,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_SUSAAJOW = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_SUSAAJOW',
    value=31,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_VVTHCAUP = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_VVTHCAUP',
    value=77,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ZWVVJCGH = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ZWVVJCGH',
    value=60,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_OFTXTTMK = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_OFTXTTMK',
    value=61,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_TTMFZHQP = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_TTMFZHQP',
    value=45,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)

NV_A_KOIOESYK_ROW_VALUE = FieldMetadata(
    name='NV_A_KOIOESYK_ROW_VALUE',
    msb=31,
    lsb=0,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_ROW_VALUE_INVALID = ValueMetadata(
    name='NV_A_KOIOESYK_ROW_VALUE_INVALID',
    value=0,
    field=NV_A_KOIOESYK_ROW_VALUE
)

NV_A_BNPIJHKK = ArrayMetadata(
    name='NV_A_BNPIJHKK',
    base_address=0x22000,
    stride=4,
    size=128,
    priv_level_mask=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_A_BNPIJHKK_VALUE = FieldMetadata(
    name='NV_A_BNPIJHKK_VALUE',
    msb=7,
    lsb=0,
    register=NV_A_BNPIJHKK
)

NV_A_BNPIJHKK_VALUE_INVALID = ValueMetadata(
    name='NV_A_BNPIJHKK_VALUE_INVALID',
    value=0,
    field=NV_A_BNPIJHKK_VALUE
)

