#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata


# Register definitions
# Array definitions
NV_A_TNXIWRPK_PRIV_LEVEL_MASK = ArrayMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK',
    base_address=0x10445c,
    stride=128,
    size=8
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION',
    msb=3,
    lsb=0,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_V_HEJWCNHK = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_V_HEJWCNHK',
    value=0,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED',
    value=15,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL',
    value=15,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0 = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0',
    msb=0,
    lsb=0,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE',
    value=0,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE',
    value=1,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1 = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1',
    msb=1,
    lsb=1,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE',
    value=0,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE',
    value=1,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2 = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2',
    msb=2,
    lsb=2,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE',
    value=0,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE',
    value=1,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3 = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3',
    msb=3,
    lsb=3,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE',
    value=0,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE',
    value=1,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_VIOLATION = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_VIOLATION',
    msb=8,
    lsb=8,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR',
    value=1,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_VIOLATION
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON',
    value=0,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_READ_VIOLATION
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_ENABLE = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_ENABLE',
    msb=31,
    lsb=12,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_GJCSBGNJ = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_GJCSBGNJ',
    value=1048575,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_ENABLE
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL',
    msb=10,
    lsb=10,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED',
    value=1,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED',
    value=0,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL',
    msb=11,
    lsb=11,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED',
    value=1,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED',
    value=0,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION',
    msb=7,
    lsb=4,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_HEJWCNHK = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_HEJWCNHK',
    value=0,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED',
    value=15,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL',
    value=15,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0 = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0',
    msb=4,
    lsb=4,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE',
    value=0,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE',
    value=1,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1 = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1',
    msb=5,
    lsb=5,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE',
    value=0,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE',
    value=1,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2 = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2',
    msb=6,
    lsb=6,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE',
    value=0,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE',
    value=1,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3 = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3',
    msb=7,
    lsb=7,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE',
    value=0,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE',
    value=1,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_VIOLATION = FieldMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_VIOLATION',
    msb=9,
    lsb=9,
    register=NV_A_TNXIWRPK_PRIV_LEVEL_MASK
)

NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR',
    value=1,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_VIOLATION
)
NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON = ValueMetadata(
    name='NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON',
    value=0,
    field=NV_A_TNXIWRPK_PRIV_LEVEL_MASK_WRITE_VIOLATION
)

NV_A_HMCKRIXL = ArrayMetadata(
    name='NV_A_HMCKRIXL',
    base_address=0x104410,
    stride=128,
    size=8,
    debug_dump={'tags': ['error'], 'interesting': {'rule': 'nonzero', 'reason': 'error status nonzero'}}
)

NV_A_HMCKRIXL_F_BOYIABCQ = FieldMetadata(
    name='NV_A_HMCKRIXL_F_BOYIABCQ',
    msb=0,
    lsb=0,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_BOYIABCQ_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_BOYIABCQ_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_BOYIABCQ
)
NV_A_HMCKRIXL_F_BOYIABCQ_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_BOYIABCQ_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_BOYIABCQ
)
NV_A_HMCKRIXL_F_BOYIABCQ_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_BOYIABCQ_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_BOYIABCQ
)

NV_A_HMCKRIXL_F_TCHXARKA = FieldMetadata(
    name='NV_A_HMCKRIXL_F_TCHXARKA',
    msb=8,
    lsb=8,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_TCHXARKA_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_TCHXARKA_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_TCHXARKA
)
NV_A_HMCKRIXL_F_TCHXARKA_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_TCHXARKA_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_TCHXARKA
)
NV_A_HMCKRIXL_F_TCHXARKA_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_TCHXARKA_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_TCHXARKA
)

NV_A_HMCKRIXL_F_FJOZPSMG = FieldMetadata(
    name='NV_A_HMCKRIXL_F_FJOZPSMG',
    msb=13,
    lsb=13,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_FJOZPSMG_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_FJOZPSMG_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_FJOZPSMG
)
NV_A_HMCKRIXL_F_FJOZPSMG_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_FJOZPSMG_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_FJOZPSMG
)
NV_A_HMCKRIXL_F_FJOZPSMG_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_FJOZPSMG_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_FJOZPSMG
)

NV_A_HMCKRIXL_F_FBOVXDLN = FieldMetadata(
    name='NV_A_HMCKRIXL_F_FBOVXDLN',
    msb=11,
    lsb=11,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_FBOVXDLN_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_FBOVXDLN_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_FBOVXDLN
)
NV_A_HMCKRIXL_F_FBOVXDLN_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_FBOVXDLN_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_FBOVXDLN
)
NV_A_HMCKRIXL_F_FBOVXDLN_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_FBOVXDLN_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_FBOVXDLN
)

NV_A_HMCKRIXL_F_ICHKDUTC = FieldMetadata(
    name='NV_A_HMCKRIXL_F_ICHKDUTC',
    msb=12,
    lsb=12,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_ICHKDUTC_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_ICHKDUTC_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_ICHKDUTC
)
NV_A_HMCKRIXL_F_ICHKDUTC_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_ICHKDUTC_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_ICHKDUTC
)
NV_A_HMCKRIXL_F_ICHKDUTC_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_ICHKDUTC_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_ICHKDUTC
)

NV_A_HMCKRIXL_F_PWDNGUNU = FieldMetadata(
    name='NV_A_HMCKRIXL_F_PWDNGUNU',
    msb=9,
    lsb=9,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_PWDNGUNU_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_PWDNGUNU_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_PWDNGUNU
)
NV_A_HMCKRIXL_F_PWDNGUNU_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_PWDNGUNU_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_PWDNGUNU
)
NV_A_HMCKRIXL_F_PWDNGUNU_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_PWDNGUNU_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_PWDNGUNU
)

NV_A_HMCKRIXL_F_MHVECWYQ = FieldMetadata(
    name='NV_A_HMCKRIXL_F_MHVECWYQ',
    msb=19,
    lsb=19,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_MHVECWYQ_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_MHVECWYQ_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_MHVECWYQ
)
NV_A_HMCKRIXL_F_MHVECWYQ_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_MHVECWYQ_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_MHVECWYQ
)
NV_A_HMCKRIXL_F_MHVECWYQ_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_MHVECWYQ_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_MHVECWYQ
)

NV_A_HMCKRIXL_F_NKJHXKYG = FieldMetadata(
    name='NV_A_HMCKRIXL_F_NKJHXKYG',
    msb=18,
    lsb=18,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_NKJHXKYG_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_NKJHXKYG_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_NKJHXKYG
)
NV_A_HMCKRIXL_F_NKJHXKYG_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_NKJHXKYG_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_NKJHXKYG
)
NV_A_HMCKRIXL_F_NKJHXKYG_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_NKJHXKYG_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_NKJHXKYG
)

NV_A_HMCKRIXL_F_IFRPMDEO = FieldMetadata(
    name='NV_A_HMCKRIXL_F_IFRPMDEO',
    msb=17,
    lsb=17,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_IFRPMDEO_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_IFRPMDEO_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_IFRPMDEO
)
NV_A_HMCKRIXL_F_IFRPMDEO_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_IFRPMDEO_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_IFRPMDEO
)
NV_A_HMCKRIXL_F_IFRPMDEO_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_IFRPMDEO_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_IFRPMDEO
)

NV_A_HMCKRIXL_F_FPHBMHHA = FieldMetadata(
    name='NV_A_HMCKRIXL_F_FPHBMHHA',
    msb=16,
    lsb=16,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_FPHBMHHA_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_FPHBMHHA_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_FPHBMHHA
)
NV_A_HMCKRIXL_F_FPHBMHHA_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_FPHBMHHA_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_FPHBMHHA
)
NV_A_HMCKRIXL_F_FPHBMHHA_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_FPHBMHHA_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_FPHBMHHA
)

NV_A_HMCKRIXL_F_XVXHDYCK = FieldMetadata(
    name='NV_A_HMCKRIXL_F_XVXHDYCK',
    msb=15,
    lsb=15,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_XVXHDYCK_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_XVXHDYCK_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_XVXHDYCK
)
NV_A_HMCKRIXL_F_XVXHDYCK_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_XVXHDYCK_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_XVXHDYCK
)
NV_A_HMCKRIXL_F_XVXHDYCK_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_XVXHDYCK_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_XVXHDYCK
)

NV_A_HMCKRIXL_F_IAHBLQWH = FieldMetadata(
    name='NV_A_HMCKRIXL_F_IAHBLQWH',
    msb=14,
    lsb=14,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_IAHBLQWH_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_IAHBLQWH_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_IAHBLQWH
)
NV_A_HMCKRIXL_F_IAHBLQWH_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_IAHBLQWH_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_IAHBLQWH
)
NV_A_HMCKRIXL_F_IAHBLQWH_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_IAHBLQWH_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_IAHBLQWH
)

NV_A_HMCKRIXL_F_CIDOFHZI = FieldMetadata(
    name='NV_A_HMCKRIXL_F_CIDOFHZI',
    msb=5,
    lsb=5,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_CIDOFHZI_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_CIDOFHZI_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_CIDOFHZI
)
NV_A_HMCKRIXL_F_CIDOFHZI_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_CIDOFHZI_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_CIDOFHZI
)
NV_A_HMCKRIXL_F_CIDOFHZI_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_CIDOFHZI_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_CIDOFHZI
)

NV_A_HMCKRIXL_F_DKOWSWJN = FieldMetadata(
    name='NV_A_HMCKRIXL_F_DKOWSWJN',
    msb=6,
    lsb=6,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_DKOWSWJN_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_DKOWSWJN_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_DKOWSWJN
)
NV_A_HMCKRIXL_F_DKOWSWJN_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_DKOWSWJN_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_DKOWSWJN
)
NV_A_HMCKRIXL_F_DKOWSWJN_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_DKOWSWJN_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_DKOWSWJN
)

NV_A_HMCKRIXL_F_FYISUZNK = FieldMetadata(
    name='NV_A_HMCKRIXL_F_FYISUZNK',
    msb=3,
    lsb=3,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_FYISUZNK_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_FYISUZNK_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_FYISUZNK
)
NV_A_HMCKRIXL_F_FYISUZNK_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_FYISUZNK_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_FYISUZNK
)
NV_A_HMCKRIXL_F_FYISUZNK_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_FYISUZNK_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_FYISUZNK
)

NV_A_HMCKRIXL_F_EUUBLOKK = FieldMetadata(
    name='NV_A_HMCKRIXL_F_EUUBLOKK',
    msb=2,
    lsb=2,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_EUUBLOKK_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_EUUBLOKK_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_EUUBLOKK
)
NV_A_HMCKRIXL_F_EUUBLOKK_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_EUUBLOKK_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_EUUBLOKK
)
NV_A_HMCKRIXL_F_EUUBLOKK_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_EUUBLOKK_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_EUUBLOKK
)

NV_A_HMCKRIXL_F_RZMIXSZI = FieldMetadata(
    name='NV_A_HMCKRIXL_F_RZMIXSZI',
    msb=4,
    lsb=4,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_RZMIXSZI_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_RZMIXSZI_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_RZMIXSZI
)
NV_A_HMCKRIXL_F_RZMIXSZI_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_RZMIXSZI_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_RZMIXSZI
)
NV_A_HMCKRIXL_F_RZMIXSZI_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_RZMIXSZI_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_RZMIXSZI
)

NV_A_HMCKRIXL_F_QXRDFMTV = FieldMetadata(
    name='NV_A_HMCKRIXL_F_QXRDFMTV',
    msb=1,
    lsb=1,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_QXRDFMTV_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_QXRDFMTV_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_QXRDFMTV
)
NV_A_HMCKRIXL_F_QXRDFMTV_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_QXRDFMTV_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_QXRDFMTV
)
NV_A_HMCKRIXL_F_QXRDFMTV_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_QXRDFMTV_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_QXRDFMTV
)

NV_A_HMCKRIXL_F_SRVLVMQO = FieldMetadata(
    name='NV_A_HMCKRIXL_F_SRVLVMQO',
    msb=7,
    lsb=7,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_SRVLVMQO_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_SRVLVMQO_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_SRVLVMQO
)
NV_A_HMCKRIXL_F_SRVLVMQO_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_SRVLVMQO_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_SRVLVMQO
)
NV_A_HMCKRIXL_F_SRVLVMQO_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_SRVLVMQO_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_SRVLVMQO
)

NV_A_HMCKRIXL_F_KJBPOAVD = FieldMetadata(
    name='NV_A_HMCKRIXL_F_KJBPOAVD',
    msb=10,
    lsb=10,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_KJBPOAVD_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_KJBPOAVD_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_KJBPOAVD
)
NV_A_HMCKRIXL_F_KJBPOAVD_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_KJBPOAVD_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_KJBPOAVD
)
NV_A_HMCKRIXL_F_KJBPOAVD_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_KJBPOAVD_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_KJBPOAVD
)

NV_A_HMCKRIXL_F_ZCQBZQME = FieldMetadata(
    name='NV_A_HMCKRIXL_F_ZCQBZQME',
    msb=31,
    lsb=31,
    register=NV_A_HMCKRIXL
)

NV_A_HMCKRIXL_F_ZCQBZQME_V_DOGBFDTH = ValueMetadata(
    name='NV_A_HMCKRIXL_F_ZCQBZQME_V_DOGBFDTH',
    value=0,
    field=NV_A_HMCKRIXL_F_ZCQBZQME
)
NV_A_HMCKRIXL_F_ZCQBZQME_V_PIUJQBKV = ValueMetadata(
    name='NV_A_HMCKRIXL_F_ZCQBZQME_V_PIUJQBKV',
    value=1,
    field=NV_A_HMCKRIXL_F_ZCQBZQME
)
NV_A_HMCKRIXL_F_ZCQBZQME_V_MDOERWXC = ValueMetadata(
    name='NV_A_HMCKRIXL_F_ZCQBZQME_V_MDOERWXC',
    value=1,
    field=NV_A_HMCKRIXL_F_ZCQBZQME
)

NV_A_QAHBIIOQ = ArrayMetadata(
    name='NV_A_QAHBIIOQ',
    base_address=0x1050a0,
    stride=64,
    size=4,
    debug_dump={'tags': ['error', 'ecc'], 'interesting': {'rule': 'nonzero', 'reason': 'ECC status nonzero'}}
)

NV_A_QAHBIIOQ_F_FKFMZRZW = FieldMetadata(
    name='NV_A_QAHBIIOQ_F_FKFMZRZW',
    msb=0,
    lsb=0,
    register=NV_A_QAHBIIOQ
)

NV_A_QAHBIIOQ_F_FKFMZRZW_V_DOGBFDTH = ValueMetadata(
    name='NV_A_QAHBIIOQ_F_FKFMZRZW_V_DOGBFDTH',
    value=0,
    field=NV_A_QAHBIIOQ_F_FKFMZRZW
)
NV_A_QAHBIIOQ_F_FKFMZRZW_V_PIUJQBKV = ValueMetadata(
    name='NV_A_QAHBIIOQ_F_FKFMZRZW_V_PIUJQBKV',
    value=1,
    field=NV_A_QAHBIIOQ_F_FKFMZRZW
)

NV_A_QAHBIIOQ_F_OJXVVOEC = FieldMetadata(
    name='NV_A_QAHBIIOQ_F_OJXVVOEC',
    msb=2,
    lsb=2,
    register=NV_A_QAHBIIOQ
)

NV_A_QAHBIIOQ_F_OJXVVOEC_V_DOGBFDTH = ValueMetadata(
    name='NV_A_QAHBIIOQ_F_OJXVVOEC_V_DOGBFDTH',
    value=0,
    field=NV_A_QAHBIIOQ_F_OJXVVOEC
)
NV_A_QAHBIIOQ_F_OJXVVOEC_V_PIUJQBKV = ValueMetadata(
    name='NV_A_QAHBIIOQ_F_OJXVVOEC_V_PIUJQBKV',
    value=1,
    field=NV_A_QAHBIIOQ_F_OJXVVOEC
)

NV_A_QAHBIIOQ_F_VEOHPHHB = FieldMetadata(
    name='NV_A_QAHBIIOQ_F_VEOHPHHB',
    msb=3,
    lsb=3,
    register=NV_A_QAHBIIOQ
)

NV_A_QAHBIIOQ_F_VEOHPHHB_V_DOGBFDTH = ValueMetadata(
    name='NV_A_QAHBIIOQ_F_VEOHPHHB_V_DOGBFDTH',
    value=0,
    field=NV_A_QAHBIIOQ_F_VEOHPHHB
)
NV_A_QAHBIIOQ_F_VEOHPHHB_V_PIUJQBKV = ValueMetadata(
    name='NV_A_QAHBIIOQ_F_VEOHPHHB_V_PIUJQBKV',
    value=1,
    field=NV_A_QAHBIIOQ_F_VEOHPHHB
)

NV_A_QAHBIIOQ_F_KVYOKDXN = FieldMetadata(
    name='NV_A_QAHBIIOQ_F_KVYOKDXN',
    msb=30,
    lsb=30,
    register=NV_A_QAHBIIOQ
)

NV_A_QAHBIIOQ_F_KVYOKDXN_V_GQHYEKHS = ValueMetadata(
    name='NV_A_QAHBIIOQ_F_KVYOKDXN_V_GQHYEKHS',
    value=0,
    field=NV_A_QAHBIIOQ_F_KVYOKDXN
)
NV_A_QAHBIIOQ_F_KVYOKDXN_V_CIHFEZTE = ValueMetadata(
    name='NV_A_QAHBIIOQ_F_KVYOKDXN_V_CIHFEZTE',
    value=1,
    field=NV_A_QAHBIIOQ_F_KVYOKDXN
)

NV_A_QAHBIIOQ_F_GFSFBDQS = FieldMetadata(
    name='NV_A_QAHBIIOQ_F_GFSFBDQS',
    msb=1,
    lsb=1,
    register=NV_A_QAHBIIOQ
)

NV_A_QAHBIIOQ_F_GFSFBDQS_V_DOGBFDTH = ValueMetadata(
    name='NV_A_QAHBIIOQ_F_GFSFBDQS_V_DOGBFDTH',
    value=0,
    field=NV_A_QAHBIIOQ_F_GFSFBDQS
)
NV_A_QAHBIIOQ_F_GFSFBDQS_V_PIUJQBKV = ValueMetadata(
    name='NV_A_QAHBIIOQ_F_GFSFBDQS_V_PIUJQBKV',
    value=1,
    field=NV_A_QAHBIIOQ_F_GFSFBDQS
)

NV_A_QAHBIIOQ_F_WQYWMRVP = FieldMetadata(
    name='NV_A_QAHBIIOQ_F_WQYWMRVP',
    msb=4,
    lsb=4,
    register=NV_A_QAHBIIOQ
)

NV_A_QAHBIIOQ_F_WQYWMRVP_V_DOGBFDTH = ValueMetadata(
    name='NV_A_QAHBIIOQ_F_WQYWMRVP_V_DOGBFDTH',
    value=0,
    field=NV_A_QAHBIIOQ_F_WQYWMRVP
)
NV_A_QAHBIIOQ_F_WQYWMRVP_V_PIUJQBKV = ValueMetadata(
    name='NV_A_QAHBIIOQ_F_WQYWMRVP_V_PIUJQBKV',
    value=1,
    field=NV_A_QAHBIIOQ_F_WQYWMRVP
)

NV_A_QAHBIIOQ_F_MLEOLJIS = FieldMetadata(
    name='NV_A_QAHBIIOQ_F_MLEOLJIS',
    msb=5,
    lsb=5,
    register=NV_A_QAHBIIOQ
)

NV_A_QAHBIIOQ_F_MLEOLJIS_V_DOGBFDTH = ValueMetadata(
    name='NV_A_QAHBIIOQ_F_MLEOLJIS_V_DOGBFDTH',
    value=0,
    field=NV_A_QAHBIIOQ_F_MLEOLJIS
)
NV_A_QAHBIIOQ_F_MLEOLJIS_V_PIUJQBKV = ValueMetadata(
    name='NV_A_QAHBIIOQ_F_MLEOLJIS_V_PIUJQBKV',
    value=1,
    field=NV_A_QAHBIIOQ_F_MLEOLJIS
)

