#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata


# Registers identical to gb100
from gpu.regs.gb100.top_int import (
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_VIOLATION,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_ENABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_PQRSTPTC,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_VIOLATION,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR,
    NV_R_VZBTKBHD_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON,
    NV_R_MNANYSOW,
    NV_R_MNANYSOW_ENABLE,
    NV_R_MNANYSOW_ENABLE_FALSE,
    NV_R_MNANYSOW_ENABLE_TRUE,
    NV_R_PWZXFNWW,
    NV_R_PWZXFNWW_F_SDHCEVQG,
    NV_R_XUCNPTBX,
    NV_R_GQVBSDVG,
    NV_R_JTQKSVDA,
    NV_R_RDNJPILZ,
    NV_R_UDJLVDHF,
    NV_R_SZHFIVFO,
    NV_R_FEBLKDFN,
    NV_R_QHESAHFP,
    NV_R_PWZXFNWW_F_SDHCEVQG_V_ZRRJKDVX,
    NV_R_PWZXFNWW_F_SDHCEVQG_V_GQHYEKHS,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_VIOLATION,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_YVMXOYBP,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_VIOLATION,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR,
    NV_R_BDUHKVXL_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON,
)

# Registers identical to gh100
from gpu.regs.gh100.top_int import (
    NV_R_ZEZRECZW,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_ENABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_WZUSYRII,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR,
    NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON,
    NV_R_ZEZRECZW_VALUE,
    NV_R_ZEZRECZW_VALUE_V_ZRRJKDVX,
)

# Register definitions
NV_PTOP_DEVICE_INFO_CFG = RegisterMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG',
    address=0x224fc,
    priv_level_mask=NV_R_VZBTKBHD_PRIV_LEVEL_MASK
)

NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES',
    msb=15,
    lsb=4,
    register=NV_PTOP_DEVICE_INFO_CFG
)

NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES_INIT = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES_INIT',
    value=60,
    field=NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES
)

NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE',
    msb=19,
    lsb=16,
    register=NV_PTOP_DEVICE_INFO_CFG
)

NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE_INIT = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE_INIT',
    value=3,
    field=NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE
)

NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS',
    msb=31,
    lsb=20,
    register=NV_PTOP_DEVICE_INFO_CFG
)

NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS_INIT = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS_INIT',
    value=152,
    field=NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS
)

NV_PTOP_DEVICE_INFO_CFG_VERSION = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_VERSION',
    msb=3,
    lsb=0,
    register=NV_PTOP_DEVICE_INFO_CFG
)

NV_PTOP_DEVICE_INFO_CFG_VERSION_INIT = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_VERSION_INIT',
    value=2,
    field=NV_PTOP_DEVICE_INFO_CFG_VERSION
)

NV_R_CUYACIFH = RegisterMetadata(
    name='NV_R_CUYACIFH',
    address=0x22478
)

NV_R_CUYACIFH_VALUE = FieldMetadata(
    name='NV_R_CUYACIFH_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_CUYACIFH
)

NV_R_CUYACIFH_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_CUYACIFH_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_CUYACIFH_VALUE
)

NV_R_SXKEOIBW = RegisterMetadata(
    name='NV_R_SXKEOIBW',
    address=0x22474
)

NV_R_SXKEOIBW_VALUE = FieldMetadata(
    name='NV_R_SXKEOIBW_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_SXKEOIBW
)

NV_R_SXKEOIBW_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_SXKEOIBW_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_SXKEOIBW_VALUE
)

NV_R_AFPSKUZI = RegisterMetadata(
    name='NV_R_AFPSKUZI',
    address=0x2247c
)

NV_R_AFPSKUZI_VALUE = FieldMetadata(
    name='NV_R_AFPSKUZI_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_AFPSKUZI
)

NV_R_AFPSKUZI_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_AFPSKUZI_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_AFPSKUZI_VALUE
)

NV_R_HMQJWADN = RegisterMetadata(
    name='NV_R_HMQJWADN',
    address=0x22444
)

NV_R_HMQJWADN_VALUE = FieldMetadata(
    name='NV_R_HMQJWADN_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_HMQJWADN
)

NV_R_HMQJWADN_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_HMQJWADN_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_HMQJWADN_VALUE
)

NV_R_WTQAYGOT = RegisterMetadata(
    name='NV_R_WTQAYGOT',
    address=0x2243c
)

NV_R_WTQAYGOT_VALUE = FieldMetadata(
    name='NV_R_WTQAYGOT_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_WTQAYGOT
)

NV_R_WTQAYGOT_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_WTQAYGOT_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_WTQAYGOT_VALUE
)

NV_R_MALHPZWJ = RegisterMetadata(
    name='NV_R_MALHPZWJ',
    address=0x22458
)

NV_R_MALHPZWJ_VALUE = FieldMetadata(
    name='NV_R_MALHPZWJ_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_MALHPZWJ
)

NV_R_MALHPZWJ_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_MALHPZWJ_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_MALHPZWJ_VALUE
)

NV_R_JVHVALTL = RegisterMetadata(
    name='NV_R_JVHVALTL',
    address=0x22438
)

NV_R_JVHVALTL_VALUE = FieldMetadata(
    name='NV_R_JVHVALTL_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_JVHVALTL
)

NV_R_JVHVALTL_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_JVHVALTL_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_JVHVALTL_VALUE
)

NV_R_GMOCCARV = RegisterMetadata(
    name='NV_R_GMOCCARV',
    address=0x22430
)

NV_R_GMOCCARV_VALUE = FieldMetadata(
    name='NV_R_GMOCCARV_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_GMOCCARV
)

NV_R_GMOCCARV_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_GMOCCARV_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_GMOCCARV_VALUE
)

NV_R_RLGXXLDD = RegisterMetadata(
    name='NV_R_RLGXXLDD',
    address=0x22454
)

NV_R_RLGXXLDD_VALUE = FieldMetadata(
    name='NV_R_RLGXXLDD_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_RLGXXLDD
)

NV_R_RLGXXLDD_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_RLGXXLDD_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_RLGXXLDD_VALUE
)

NV_R_MGENATIB = RegisterMetadata(
    name='NV_R_MGENATIB',
    address=0x22450
)

NV_R_MGENATIB_VALUE = FieldMetadata(
    name='NV_R_MGENATIB_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_MGENATIB
)

NV_R_MGENATIB_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_MGENATIB_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_MGENATIB_VALUE
)

NV_R_FXMSYJMF = RegisterMetadata(
    name='NV_R_FXMSYJMF',
    address=0x22464
)

NV_R_FXMSYJMF_VALUE = FieldMetadata(
    name='NV_R_FXMSYJMF_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_FXMSYJMF
)

NV_R_FXMSYJMF_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_FXMSYJMF_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_FXMSYJMF_VALUE
)

NV_R_QIDNGOVJ = RegisterMetadata(
    name='NV_R_QIDNGOVJ',
    address=0x2244c
)

NV_R_QIDNGOVJ_VALUE = FieldMetadata(
    name='NV_R_QIDNGOVJ_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_QIDNGOVJ
)

NV_R_QIDNGOVJ_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_QIDNGOVJ_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_QIDNGOVJ_VALUE
)

NV_R_UKNWXHHW = RegisterMetadata(
    name='NV_R_UKNWXHHW',
    address=0x22468
)

NV_R_UKNWXHHW_VALUE = FieldMetadata(
    name='NV_R_UKNWXHHW_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_UKNWXHHW
)

NV_R_UKNWXHHW_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_UKNWXHHW_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_UKNWXHHW_VALUE
)

NV_R_MUMMKQCM = RegisterMetadata(
    name='NV_R_MUMMKQCM',
    address=0x2246c
)

NV_R_MUMMKQCM_VALUE = FieldMetadata(
    name='NV_R_MUMMKQCM_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_MUMMKQCM
)

NV_R_MUMMKQCM_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_MUMMKQCM_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_MUMMKQCM_VALUE
)

NV_R_ZNEWYGRA = RegisterMetadata(
    name='NV_R_ZNEWYGRA',
    address=0x22470
)

NV_R_ZNEWYGRA_VALUE = FieldMetadata(
    name='NV_R_ZNEWYGRA_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_ZNEWYGRA
)

NV_R_ZNEWYGRA_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_ZNEWYGRA_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_ZNEWYGRA_VALUE
)

NV_R_KYKLMRFE = RegisterMetadata(
    name='NV_R_KYKLMRFE',
    address=0x22460
)

NV_R_KYKLMRFE_VALUE = FieldMetadata(
    name='NV_R_KYKLMRFE_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_KYKLMRFE
)

NV_R_KYKLMRFE_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_KYKLMRFE_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_KYKLMRFE_VALUE
)

NV_R_TWHJUYMI = RegisterMetadata(
    name='NV_R_TWHJUYMI',
    address=0x22480
)

NV_R_TWHJUYMI_VALUE = FieldMetadata(
    name='NV_R_TWHJUYMI_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_TWHJUYMI
)

NV_R_TWHJUYMI_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_TWHJUYMI_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_TWHJUYMI_VALUE
)

NV_R_KMZTDFMK = RegisterMetadata(
    name='NV_R_KMZTDFMK',
    address=0x2245c
)

NV_R_KMZTDFMK_VALUE = FieldMetadata(
    name='NV_R_KMZTDFMK_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_KMZTDFMK
)

NV_R_KMZTDFMK_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_KMZTDFMK_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_KMZTDFMK_VALUE
)

NV_R_VNLAJASY = RegisterMetadata(
    name='NV_R_VNLAJASY',
    address=0x22488
)

NV_R_VNLAJASY_VALUE = FieldMetadata(
    name='NV_R_VNLAJASY_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_VNLAJASY
)

NV_R_VNLAJASY_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_VNLAJASY_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_VNLAJASY_VALUE
)

NV_R_LMSCCKQD = RegisterMetadata(
    name='NV_R_LMSCCKQD',
    address=0x2248c
)

NV_R_LMSCCKQD_VALUE = FieldMetadata(
    name='NV_R_LMSCCKQD_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_LMSCCKQD
)

NV_R_LMSCCKQD_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_LMSCCKQD_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_LMSCCKQD_VALUE
)

NV_R_UTWVFXBK = RegisterMetadata(
    name='NV_R_UTWVFXBK',
    address=0x22434
)

NV_R_UTWVFXBK_VALUE = FieldMetadata(
    name='NV_R_UTWVFXBK_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_UTWVFXBK
)

NV_R_UTWVFXBK_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_UTWVFXBK_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_UTWVFXBK_VALUE
)

NV_R_HTYAWCIU = RegisterMetadata(
    name='NV_R_HTYAWCIU',
    address=0x22440
)

NV_R_HTYAWCIU_VALUE = FieldMetadata(
    name='NV_R_HTYAWCIU_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_HTYAWCIU
)

NV_R_HTYAWCIU_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_HTYAWCIU_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_HTYAWCIU_VALUE
)

# Array definitions
NV_A_KOIOESYK = ArrayMetadata(
    name='NV_A_KOIOESYK',
    base_address=0x22800,
    stride=4,
    size=152
)

NV_A_KOIOESYK_DEV_DEVICE_BROADCAST_PRI_BASE = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_DEVICE_BROADCAST_PRI_BASE',
    msb=89,
    lsb=66,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_DEVICE_PRI_BASE = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_DEVICE_PRI_BASE',
    msb=57,
    lsb=40,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_FAULT_ID = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_FAULT_ID',
    msb=10,
    lsb=0,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_FAULT_ID_INVALID = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_FAULT_ID_INVALID',
    value=0,
    field=NV_A_KOIOESYK_DEV_FAULT_ID
)

NV_A_KOIOESYK_DEV_GIN_TARGET_ID = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_GIN_TARGET_ID',
    msb=39,
    lsb=32,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_GIN_TARGET_ID_INVALID = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_GIN_TARGET_ID_INVALID',
    value=255,
    field=NV_A_KOIOESYK_DEV_GIN_TARGET_ID
)

NV_A_KOIOESYK_DEV_GROUP_ID = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_GROUP_ID',
    msb=15,
    lsb=11,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_INSTANCE_ID = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_INSTANCE_ID',
    msb=23,
    lsb=16,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_IS_ENGINE = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_IS_ENGINE',
    msb=62,
    lsb=62,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_IS_ENGINE_FALSE = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_IS_ENGINE_FALSE',
    value=0,
    field=NV_A_KOIOESYK_DEV_IS_ENGINE
)
NV_A_KOIOESYK_DEV_IS_ENGINE_TRUE = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_IS_ENGINE_TRUE',
    value=1,
    field=NV_A_KOIOESYK_DEV_IS_ENGINE
)

NV_A_KOIOESYK_DEV_RLENG_ID = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_RLENG_ID',
    msb=65,
    lsb=64,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_RUNLIST_PRI_BASE = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_RUNLIST_PRI_BASE',
    msb=89,
    lsb=74,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_TYPE_ENUM = FieldMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM',
    msb=30,
    lsb=24,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_DEV_TYPE_ENUM_V_HCWXSYBM = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_HCWXSYBM',
    value=43,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_RVLKEJWH = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_RVLKEJWH',
    value=25,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ZFTDRKPW = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ZFTDRKPW',
    value=47,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_CZFXNUUF = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_CZFXNUUF',
    value=64,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_HMOVKBYF = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_HMOVKBYF',
    value=33,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ESQECSMQ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ESQECSMQ',
    value=55,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_DKSQOGZB = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_DKSQOGZB',
    value=63,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_AUMDBSXC = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_AUMDBSXC',
    value=27,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_UOZWLQWO = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_UOZWLQWO',
    value=23,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_UDSNKUFQ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_UDSNKUFQ',
    value=26,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_LXZKRGMA = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_LXZKRGMA',
    value=34,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_TCNOOWJU = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_TCNOOWJU',
    value=41,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_PZLHMKFG = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_PZLHMKFG',
    value=30,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_GOCSCMKA = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_GOCSCMKA',
    value=0,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_LWBHHXKA = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_LWBHHXKA',
    value=20,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_WTHDKXVG = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_WTHDKXVG',
    value=57,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_GFNCQPKZ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_GFNCQPKZ',
    value=56,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_YPWVVQTV = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_YPWVVQTV',
    value=24,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_KKNDLMWG = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_KKNDLMWG',
    value=32,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_WVIQLUWD = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_WVIQLUWD',
    value=53,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_EHKYSREA = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_EHKYSREA',
    value=18,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_LXGHDGQH = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_LXGHDGQH',
    value=54,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_JJKKDWDQ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_JJKKDWDQ',
    value=44,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ADOFRLBI = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ADOFRLBI',
    value=19,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_JPNCPYGI = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_JPNCPYGI',
    value=58,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_STKTDZMV = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_STKTDZMV',
    value=59,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_GIUXYEQN = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_GIUXYEQN',
    value=16,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_NVYOLSKM = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_NVYOLSKM',
    value=14,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_NIPQQHPC = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_NIPQQHPC',
    value=21,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_DMQZBYEC = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_DMQZBYEC',
    value=29,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_EFTKKQKC = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_EFTKKQKC',
    value=28,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BNYIUTBN = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BNYIUTBN',
    value=22,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BBVOGXOS = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BBVOGXOS',
    value=51,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_RYWEOWVQ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_RYWEOWVQ',
    value=46,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_YKLTYEHD = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_YKLTYEHD',
    value=50,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_KKZDHCFZ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_KKZDHCFZ',
    value=35,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_VNQBIHKN = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_VNQBIHKN',
    value=39,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_MFPBDEFG = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_MFPBDEFG',
    value=38,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BGCAQFFS = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_BGCAQFFS',
    value=52,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_MDOERWXC = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_MDOERWXC',
    value=42,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_NSDPVTAV = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_NSDPVTAV',
    value=13,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_AIWIVARW = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_AIWIVARW',
    value=40,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_JKGYEQWV = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_JKGYEQWV',
    value=62,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ATROBEKO = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ATROBEKO',
    value=48,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_MYUKYXBZ = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_MYUKYXBZ',
    value=49,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_WJJRMTCR = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_WJJRMTCR',
    value=36,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_YMDFXFXY = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_YMDFXFXY',
    value=37,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_SUSAAJOW = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_SUSAAJOW',
    value=31,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ZWVVJCGH = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_ZWVVJCGH',
    value=60,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_OFTXTTMK = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_OFTXTTMK',
    value=61,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)
NV_A_KOIOESYK_DEV_TYPE_ENUM_V_TTMFZHQP = ValueMetadata(
    name='NV_A_KOIOESYK_DEV_TYPE_ENUM_V_TTMFZHQP',
    value=45,
    field=NV_A_KOIOESYK_DEV_TYPE_ENUM
)

NV_A_KOIOESYK_F_VGTHJYYV = FieldMetadata(
    name='NV_A_KOIOESYK_F_VGTHJYYV',
    msb=12,
    lsb=12,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_GPKNHHOE = FieldMetadata(
    name='NV_A_KOIOESYK_F_GPKNHHOE',
    msb=1,
    lsb=1,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_AOEQKJKF = FieldMetadata(
    name='NV_A_KOIOESYK_F_AOEQKJKF',
    msb=2,
    lsb=2,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_HNUWFWPY = FieldMetadata(
    name='NV_A_KOIOESYK_F_HNUWFWPY',
    msb=3,
    lsb=3,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_BCYQUURF = FieldMetadata(
    name='NV_A_KOIOESYK_F_BCYQUURF',
    msb=8,
    lsb=8,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_BYSEHLIN = FieldMetadata(
    name='NV_A_KOIOESYK_F_BYSEHLIN',
    msb=9,
    lsb=9,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_XNSVGZGK = FieldMetadata(
    name='NV_A_KOIOESYK_F_XNSVGZGK',
    msb=10,
    lsb=10,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_NEANYYQE = FieldMetadata(
    name='NV_A_KOIOESYK_F_NEANYYQE',
    msb=11,
    lsb=11,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_EBFXUMTQ = FieldMetadata(
    name='NV_A_KOIOESYK_F_EBFXUMTQ',
    msb=13,
    lsb=13,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_HMWSOECA = FieldMetadata(
    name='NV_A_KOIOESYK_F_HMWSOECA',
    msb=14,
    lsb=14,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_DTZTCQNS = FieldMetadata(
    name='NV_A_KOIOESYK_F_DTZTCQNS',
    msb=21,
    lsb=21,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_BDMYBHZI = FieldMetadata(
    name='NV_A_KOIOESYK_F_BDMYBHZI',
    msb=22,
    lsb=22,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_ICKFFZGU = FieldMetadata(
    name='NV_A_KOIOESYK_F_ICKFFZGU',
    msb=15,
    lsb=15,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_NUZYYCSL = FieldMetadata(
    name='NV_A_KOIOESYK_F_NUZYYCSL',
    msb=16,
    lsb=16,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_URSYLRXS = FieldMetadata(
    name='NV_A_KOIOESYK_F_URSYLRXS',
    msb=20,
    lsb=20,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_LGUVZBLJ = FieldMetadata(
    name='NV_A_KOIOESYK_F_LGUVZBLJ',
    msb=4,
    lsb=4,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_QKBSROLO = FieldMetadata(
    name='NV_A_KOIOESYK_F_QKBSROLO',
    msb=18,
    lsb=18,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_FXNXGDDP = FieldMetadata(
    name='NV_A_KOIOESYK_F_FXNXGDDP',
    msb=19,
    lsb=19,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_UQIZOMPO = FieldMetadata(
    name='NV_A_KOIOESYK_F_UQIZOMPO',
    msb=6,
    lsb=6,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_JSOFFNHB = FieldMetadata(
    name='NV_A_KOIOESYK_F_JSOFFNHB',
    msb=7,
    lsb=7,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_GBKTMXWI = FieldMetadata(
    name='NV_A_KOIOESYK_F_GBKTMXWI',
    msb=31,
    lsb=31,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_PIIMYBCV = FieldMetadata(
    name='NV_A_KOIOESYK_F_PIIMYBCV',
    msb=23,
    lsb=23,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_JTLODZSJ = FieldMetadata(
    name='NV_A_KOIOESYK_F_JTLODZSJ',
    msb=32,
    lsb=32,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_SASCAQGY = FieldMetadata(
    name='NV_A_KOIOESYK_F_SASCAQGY',
    msb=33,
    lsb=33,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_JBALMHXM = FieldMetadata(
    name='NV_A_KOIOESYK_F_JBALMHXM',
    msb=17,
    lsb=17,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_F_LWJTNSWM = FieldMetadata(
    name='NV_A_KOIOESYK_F_LWJTNSWM',
    msb=5,
    lsb=5,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_ROW_CHAIN = FieldMetadata(
    name='NV_A_KOIOESYK_ROW_CHAIN',
    msb=31,
    lsb=31,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_ROW_CHAIN_V_LIUXBPIS = ValueMetadata(
    name='NV_A_KOIOESYK_ROW_CHAIN_V_LIUXBPIS',
    value=0,
    field=NV_A_KOIOESYK_ROW_CHAIN
)
NV_A_KOIOESYK_ROW_CHAIN_V_MELZQZNJ = ValueMetadata(
    name='NV_A_KOIOESYK_ROW_CHAIN_V_MELZQZNJ',
    value=1,
    field=NV_A_KOIOESYK_ROW_CHAIN
)

NV_A_KOIOESYK_ROW_VALUE = FieldMetadata(
    name='NV_A_KOIOESYK_ROW_VALUE',
    msb=31,
    lsb=0,
    register=NV_A_KOIOESYK
)

NV_A_KOIOESYK_ROW_VALUE_INVALID = ValueMetadata(
    name='NV_A_KOIOESYK_ROW_VALUE_INVALID',
    value=0,
    field=NV_A_KOIOESYK_ROW_VALUE
)

NV_PTOP_DEVICE_INFO2 = ArrayMetadata(
    name='NV_PTOP_DEVICE_INFO2',
    base_address=0x22800,
    stride=4,
    size=152
)

NV_PTOP_DEVICE_INFO2_DEV_DEVICE_PRI_BASE = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_DEVICE_PRI_BASE',
    msb=57,
    lsb=40,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_FAULT_ID = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_FAULT_ID',
    msb=10,
    lsb=0,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_FAULT_ID_INVALID = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_FAULT_ID_INVALID',
    value=0,
    field=NV_PTOP_DEVICE_INFO2_DEV_FAULT_ID
)

NV_PTOP_DEVICE_INFO2_DEV_GROUP_ID = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_GROUP_ID',
    msb=15,
    lsb=11,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_INSTANCE_ID = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_INSTANCE_ID',
    msb=23,
    lsb=16,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE',
    msb=62,
    lsb=62,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE_FALSE = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE_FALSE',
    value=0,
    field=NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE
)
NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE_TRUE = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE_TRUE',
    value=1,
    field=NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE
)

NV_PTOP_DEVICE_INFO2_DEV_RESET_ID = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_RESET_ID',
    msb=39,
    lsb=32,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_RESET_ID_INVALID = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_RESET_ID_INVALID',
    value=255,
    field=NV_PTOP_DEVICE_INFO2_DEV_RESET_ID
)

NV_PTOP_DEVICE_INFO2_DEV_RLENG_ID = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_RLENG_ID',
    msb=65,
    lsb=64,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_RUNLIST_PRI_BASE = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_RUNLIST_PRI_BASE',
    msb=89,
    lsb=74,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM',
    msb=30,
    lsb=24,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_HCWXSYBM = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_HCWXSYBM',
    value=43,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_RVLKEJWH = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_RVLKEJWH',
    value=25,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_ZFTDRKPW = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_ZFTDRKPW',
    value=47,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_CZFXNUUF = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_CZFXNUUF',
    value=64,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_HMOVKBYF = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_HMOVKBYF',
    value=33,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_ESQECSMQ = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_ESQECSMQ',
    value=55,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_DKSQOGZB = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_DKSQOGZB',
    value=63,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_FBHUB = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_FBHUB',
    value=27,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_UOZWLQWO = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_UOZWLQWO',
    value=23,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_UDSNKUFQ = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_UDSNKUFQ',
    value=26,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_LXZKRGMA = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_LXZKRGMA',
    value=34,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_TCNOOWJU = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_TCNOOWJU',
    value=41,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_PZLHMKFG = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_PZLHMKFG',
    value=30,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_GOCSCMKA = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_GOCSCMKA',
    value=0,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_LWBHHXKA = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_LWBHHXKA',
    value=20,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_WTHDKXVG = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_WTHDKXVG',
    value=57,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_GFNCQPKZ = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_GFNCQPKZ',
    value=56,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_HSHUB = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_HSHUB',
    value=24,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_HSHUBMMU = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_HSHUBMMU',
    value=32,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_HUBMMU = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_HUBMMU',
    value=53,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_EHKYSREA = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_EHKYSREA',
    value=18,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_LXGHDGQH = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_LXGHDGQH',
    value=54,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_JJKKDWDQ = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_JJKKDWDQ',
    value=44,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_ADOFRLBI = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_ADOFRLBI',
    value=19,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_JPNCPYGI = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_JPNCPYGI',
    value=58,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_STKTDZMV = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_STKTDZMV',
    value=59,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_GIUXYEQN = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_GIUXYEQN',
    value=16,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_NVYOLSKM = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_NVYOLSKM',
    value=14,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_NIPQQHPC = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_NIPQQHPC',
    value=21,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_DMQZBYEC = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_DMQZBYEC',
    value=29,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_NVLPW = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_NVLPW',
    value=28,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_BNYIUTBN = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_BNYIUTBN',
    value=22,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_BBVOGXOS = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_BBVOGXOS',
    value=51,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_RYWEOWVQ = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_RYWEOWVQ',
    value=46,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_YKLTYEHD = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_YKLTYEHD',
    value=50,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_KKZDHCFZ = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_KKZDHCFZ',
    value=35,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_VNQBIHKN = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_VNQBIHKN',
    value=39,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_MFPBDEFG = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_MFPBDEFG',
    value=38,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_BGCAQFFS = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_BGCAQFFS',
    value=52,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_MDOERWXC = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_MDOERWXC',
    value=42,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_NSDPVTAV = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_NSDPVTAV',
    value=13,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_AIWIVARW = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_AIWIVARW',
    value=40,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_JKGYEQWV = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_JKGYEQWV',
    value=62,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_ATROBEKO = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_ATROBEKO',
    value=48,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_SYSLTC = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_SYSLTC',
    value=49,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_WJJRMTCR = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_WJJRMTCR',
    value=36,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_YMDFXFXY = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_YMDFXFXY',
    value=37,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_SUSAAJOW = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_SUSAAJOW',
    value=31,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_ZWVVJCGH = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_ZWVVJCGH',
    value=60,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_OFTXTTMK = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_OFTXTTMK',
    value=61,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_TTMFZHQP = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_TTMFZHQP',
    value=45,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)

NV_PTOP_DEVICE_INFO2_ROW_CHAIN = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_ROW_CHAIN',
    msb=31,
    lsb=31,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_ROW_CHAIN_LAST = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_ROW_CHAIN_LAST',
    value=0,
    field=NV_PTOP_DEVICE_INFO2_ROW_CHAIN
)
NV_PTOP_DEVICE_INFO2_ROW_CHAIN_MORE = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_ROW_CHAIN_MORE',
    value=1,
    field=NV_PTOP_DEVICE_INFO2_ROW_CHAIN
)

NV_PTOP_DEVICE_INFO2_ROW_VALUE = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_ROW_VALUE',
    msb=31,
    lsb=0,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_ROW_VALUE_INVALID = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_ROW_VALUE_INVALID',
    value=0,
    field=NV_PTOP_DEVICE_INFO2_ROW_VALUE
)

