#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata


# Registers identical to gb100
from gpu.regs.gb100.xal_int import (
    NV_R_AGXHZVDW,
    NV_R_AGXHZVDW_F_CSXZWYIM,
    NV_R_AGXHZVDW_F_CSXZWYIM_V_GQHYEKHS,
    NV_R_AGXHZVDW_F_OIGWNDTI,
    NV_R_AGXHZVDW_F_OIGWNDTI_V_GQHYEKHS,
    NV_R_AGXHZVDW_F_JGDYKRTC,
    NV_R_AGXHZVDW_F_JGDYKRTC_V_YIYDETAJ,
    NV_R_AGXHZVDW_F_JGDYKRTC_V_PFJFQFSM,
    NV_R_AGXHZVDW_F_JGDYKRTC_V_CRFJBTNJ,
    NV_R_CTSRXRJA,
    NV_R_CTSRXRJA_F_XZCIOFTX,
    NV_R_CTSRXRJA_F_XZCIOFTX_V_WDAOZBUG,
    NV_R_CTSRXRJA_F_XZCIOFTX_V_OLQLFEZG,
    NV_R_CTSRXRJA_F_XZCIOFTX_V_JTQCCLDC,
    NV_R_CTSRXRJA_F_XZCIOFTX_V_SMHGBZYZ,
    NV_R_CTSRXRJA_F_CSXZWYIM,
    NV_R_CTSRXRJA_F_CSXZWYIM_V_GQHYEKHS,
    NV_R_CTSRXRJA_F_OIGWNDTI,
    NV_R_CTSRXRJA_F_OIGWNDTI_V_GQHYEKHS,
    NV_R_CTSRXRJA_F_JGDYKRTC,
    NV_R_CTSRXRJA_F_JGDYKRTC_V_PFJFQFSM,
    NV_R_CTSRXRJA_F_JGDYKRTC_V_CRFJBTNJ,
)

# Registers identical to gh100
from gpu.regs.gh100.xal_int import (
    NV_R_RTXEVWIZ,
    NV_R_RTXEVWIZ_F_FMDCUIAD,
    NV_R_RTXEVWIZ_F_FMDCUIAD_V_GQHYEKHS,
    NV_R_LZSOUPVS,
    NV_R_LZSOUPVS_F_OJYQBJXU,
    NV_R_WLBKDJZT,
    NV_R_WLBKDJZT_F_CTBCFRUB,
    NV_R_WLBKDJZT_F_CTBCFRUB_V_GQHYEKHS,
    NV_R_WLBKDJZT_F_QVYAARWP,
    NV_R_WLBKDJZT_F_QVYAARWP_V_GQHYEKHS,
    NV_R_ICINMFYU,
    NV_R_ICINMFYU_F_DBYSWVHB,
    NV_R_ICINMFYU_F_DBYSWVHB_V_DOGBFDTH,
    NV_R_ICINMFYU_F_DBYSWVHB_V_PIUJQBKV,
    NV_R_ICINMFYU_F_OJXVVOEC,
    NV_R_ICINMFYU_F_OJXVVOEC_V_DOGBFDTH,
    NV_R_ICINMFYU_F_OJXVVOEC_V_PIUJQBKV,
    NV_R_ICINMFYU_F_VEOHPHHB,
    NV_R_ICINMFYU_F_VEOHPHHB_V_DOGBFDTH,
    NV_R_ICINMFYU_F_VEOHPHHB_V_PIUJQBKV,
    NV_R_ICINMFYU_F_UURIHQGO,
    NV_R_ICINMFYU_F_UURIHQGO_V_DOGBFDTH,
    NV_R_ICINMFYU_F_UURIHQGO_V_PIUJQBKV,
    NV_R_ICINMFYU_F_WQYWMRVP,
    NV_R_ICINMFYU_F_WQYWMRVP_V_DOGBFDTH,
    NV_R_ICINMFYU_F_WQYWMRVP_V_PIUJQBKV,
    NV_R_ICINMFYU_F_MLEOLJIS,
    NV_R_ICINMFYU_F_MLEOLJIS_V_DOGBFDTH,
    NV_R_ICINMFYU_F_MLEOLJIS_V_PIUJQBKV,
    NV_R_VLTEGMKD,
    NV_R_VLTEGMKD_F_CTBCFRUB,
    NV_R_VLTEGMKD_F_CTBCFRUB_V_GQHYEKHS,
    NV_R_VLTEGMKD_F_QVYAARWP,
    NV_R_VLTEGMKD_F_QVYAARWP_V_GQHYEKHS,
    NV_R_SXUEHZYB,
    NV_R_SXUEHZYB_F_FJYCNPHP,
    NV_R_SXUEHZYB_F_FJYCNPHP_V_GQHYEKHS,
    NV_R_NYYRIQPJ,
    NV_R_NYYRIQPJ_F_JEHSTEUR,
    NV_R_NYYRIQPJ_F_JEHSTEUR_V_GQHYEKHS,
    NV_R_LPJIOAEO,
    NV_R_LPJIOAEO_F_FJYCNPHP,
    NV_R_LPJIOAEO_F_FJYCNPHP_V_GQHYEKHS,
    NV_R_TOZOZAJX,
    NV_R_TOZOZAJX_F_JEHSTEUR,
    NV_R_TOZOZAJX_F_JEHSTEUR_V_GQHYEKHS,
    NV_R_GEBSVJCV,
    NV_R_GEBSVJCV_F_OJYQBJXU,
    NV_R_YERYFYZX,
    NV_R_YERYFYZX_F_CTBCFRUB,
    NV_R_YERYFYZX_F_CTBCFRUB_V_GQHYEKHS,
    NV_R_YERYFYZX_F_QVYAARWP,
    NV_R_YERYFYZX_F_QVYAARWP_V_GQHYEKHS,
    NV_R_OBIKYNEA,
    NV_R_OBIKYNEA_F_DBYSWVHB,
    NV_R_OBIKYNEA_F_DBYSWVHB_V_DOGBFDTH,
    NV_R_OBIKYNEA_F_DBYSWVHB_V_PIUJQBKV,
    NV_R_OBIKYNEA_F_OJXVVOEC,
    NV_R_OBIKYNEA_F_OJXVVOEC_V_DOGBFDTH,
    NV_R_OBIKYNEA_F_OJXVVOEC_V_PIUJQBKV,
    NV_R_OBIKYNEA_F_VEOHPHHB,
    NV_R_OBIKYNEA_F_VEOHPHHB_V_DOGBFDTH,
    NV_R_OBIKYNEA_F_VEOHPHHB_V_PIUJQBKV,
    NV_R_OBIKYNEA_F_UURIHQGO,
    NV_R_OBIKYNEA_F_UURIHQGO_V_DOGBFDTH,
    NV_R_OBIKYNEA_F_UURIHQGO_V_PIUJQBKV,
    NV_R_OBIKYNEA_F_WQYWMRVP,
    NV_R_OBIKYNEA_F_WQYWMRVP_V_DOGBFDTH,
    NV_R_OBIKYNEA_F_WQYWMRVP_V_PIUJQBKV,
    NV_R_OBIKYNEA_F_MLEOLJIS,
    NV_R_OBIKYNEA_F_MLEOLJIS_V_DOGBFDTH,
    NV_R_OBIKYNEA_F_MLEOLJIS_V_PIUJQBKV,
    NV_R_DBTSDKNU,
    NV_R_DBTSDKNU_F_CTBCFRUB,
    NV_R_DBTSDKNU_F_CTBCFRUB_V_GQHYEKHS,
    NV_R_DBTSDKNU_F_QVYAARWP,
    NV_R_DBTSDKNU_F_QVYAARWP_V_GQHYEKHS,
)

