#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata


# Registers identical to gh100
from gpu.regs.gh100.xpl_int import (
    NV_R_BNNSDDXF,
    NV_R_BNNSDDXF_F_AKTRDZCQ,
    NV_R_BNNSDDXF_F_AKTRDZCQ_V_GQHYEKHS,
    NV_R_BNNSDDXF_F_ANILTANB,
    NV_R_BNNSDDXF_F_ANILTANB_V_GQHYEKHS,
    NV_R_XZFMHPDU,
    NV_R_XZFMHPDU_F_AKTRDZCQ,
    NV_R_XZFMHPDU_F_AKTRDZCQ_V_GQHYEKHS,
    NV_R_XZFMHPDU_F_ANILTANB,
    NV_R_XZFMHPDU_F_ANILTANB_V_GQHYEKHS,
    NV_R_NWMGSRVP,
    NV_R_NWMGSRVP_F_MSZTXVYR,
    NV_R_NWMGSRVP_F_MSZTXVYR_V_AABSSBNA,
    NV_R_NWMGSRVP_F_MSZTXVYR_V_DDVZAPYQ,
    NV_R_NWMGSRVP_F_IRNMTOGK,
    NV_R_NWMGSRVP_F_IRNMTOGK_V_AABSSBNA,
    NV_R_NWMGSRVP_F_IRNMTOGK_V_DDVZAPYQ,
    NV_R_NWMGSRVP_F_HLOPLUKX,
    NV_R_NWMGSRVP_F_HLOPLUKX_V_AABSSBNA,
    NV_R_NWMGSRVP_F_HLOPLUKX_V_DDVZAPYQ,
    NV_R_NWMGSRVP_F_IXIMDEIL,
    NV_R_NWMGSRVP_F_IXIMDEIL_V_AABSSBNA,
    NV_R_NWMGSRVP_F_IXIMDEIL_V_DDVZAPYQ,
    NV_R_TJDJJXDH,
    NV_R_TJDJJXDH_F_AHLCMKXX,
    NV_R_TJDJJXDH_F_AHLCMKXX_V_AABSSBNA,
    NV_R_TJDJJXDH_F_AHLCMKXX_V_DDVZAPYQ,
    NV_R_TJDJJXDH_F_YAKCLFUX,
    NV_R_TJDJJXDH_F_YAKCLFUX_V_AABSSBNA,
    NV_R_TJDJJXDH_F_YAKCLFUX_V_DDVZAPYQ,
    NV_R_TJDJJXDH_F_ZCZOCUFJ,
    NV_R_TJDJJXDH_F_ZCZOCUFJ_V_AABSSBNA,
    NV_R_TJDJJXDH_F_ZCZOCUFJ_V_DDVZAPYQ,
    NV_R_TLULSDNR,
    NV_R_TLULSDNR_F_JHGJMNYQ,
    NV_R_TLULSDNR_F_JHGJMNYQ_V_TYLKUYOV,
    NV_R_TLULSDNR_F_JHGJMNYQ_V_SQJQPVVW,
    NV_R_TLULSDNR_F_TWVSOJZO,
    NV_R_TLULSDNR_F_TWVSOJZO_V_TYLKUYOV,
    NV_R_TLULSDNR_F_TWVSOJZO_V_SQJQPVVW,
    NV_R_TLULSDNR_F_VWSCRVRH,
    NV_R_TLULSDNR_F_VWSCRVRH_V_TYLKUYOV,
    NV_R_TLULSDNR_F_VWSCRVRH_V_SQJQPVVW,
    NV_R_TLULSDNR_F_THIGODWY,
    NV_R_TLULSDNR_F_THIGODWY_V_TYLKUYOV,
    NV_R_TLULSDNR_F_THIGODWY_V_SQJQPVVW,
    NV_R_TLULSDNR_F_SQRXFRHZ,
    NV_R_TLULSDNR_F_SQRXFRHZ_V_TYLKUYOV,
    NV_R_TLULSDNR_F_SQRXFRHZ_V_SQJQPVVW,
    NV_R_TLULSDNR_F_NMTHBTXS,
    NV_R_TLULSDNR_F_NMTHBTXS_V_TYLKUYOV,
    NV_R_TLULSDNR_F_NMTHBTXS_V_SQJQPVVW,
    NV_R_TLULSDNR_F_DSYFNOVJ,
    NV_R_TLULSDNR_F_DSYFNOVJ_V_TYLKUYOV,
    NV_R_TLULSDNR_F_DSYFNOVJ_V_SQJQPVVW,
    NV_R_TLULSDNR_F_OQDTLZES,
    NV_R_TLULSDNR_F_OQDTLZES_V_TYLKUYOV,
    NV_R_TLULSDNR_F_OQDTLZES_V_SQJQPVVW,
    NV_R_TLULSDNR_F_IXDOHJET,
    NV_R_TLULSDNR_F_IXDOHJET_V_TYLKUYOV,
    NV_R_TLULSDNR_F_IXDOHJET_V_SQJQPVVW,
    NV_R_TLULSDNR_F_RNQUIIKV,
    NV_R_TLULSDNR_F_RNQUIIKV_V_TYLKUYOV,
    NV_R_TLULSDNR_F_RNQUIIKV_V_SQJQPVVW,
    NV_R_TLULSDNR_F_WYFDZNYR,
    NV_R_TLULSDNR_F_WYFDZNYR_V_TYLKUYOV,
    NV_R_TLULSDNR_F_WYFDZNYR_V_SQJQPVVW,
    NV_R_TLULSDNR_F_PEZFMQOX,
    NV_R_TLULSDNR_F_PEZFMQOX_V_TYLKUYOV,
    NV_R_TLULSDNR_F_PEZFMQOX_V_SQJQPVVW,
    NV_R_TLULSDNR_F_NSKTUIIC,
    NV_R_TLULSDNR_F_NSKTUIIC_V_TYLKUYOV,
    NV_R_TLULSDNR_F_NSKTUIIC_V_SQJQPVVW,
    NV_R_TLULSDNR_F_ASYSFFPX,
    NV_R_TLULSDNR_F_ASYSFFPX_V_TYLKUYOV,
    NV_R_TLULSDNR_F_ASYSFFPX_V_SQJQPVVW,
    NV_R_TLULSDNR_F_CUYZXDTI,
    NV_R_TLULSDNR_F_CUYZXDTI_V_TYLKUYOV,
    NV_R_TLULSDNR_F_CUYZXDTI_V_SQJQPVVW,
    NV_R_TLULSDNR_F_PWTBFXDT,
    NV_R_TLULSDNR_F_PWTBFXDT_V_TYLKUYOV,
    NV_R_TLULSDNR_F_PWTBFXDT_V_SQJQPVVW,
)

