#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata


# Registers identical to gb100
from gpu.regs.gb100.gfw_subset_int import (
    NV_R_URHLCNAU,
    NV_R_URHLCNAU_F_STVXDWPW,
    NV_R_URHLCNAU_F_JSOMDIEJ,
    NV_R_URHLCNAU_F_FOEUOQKS,
    NV_R_URHLCNAU_F_FOEUOQKS_V_LCSGGZZT,
    NV_R_URHLCNAU_F_FOEUOQKS_V_IYUGIXGA,
    NV_R_URHLCNAU_F_FOEUOQKS_V_PDKADLYJ,
    NV_R_URHLCNAU_F_FOEUOQKS_V_UUKUCAVT,
    NV_R_URHLCNAU_F_FOEUOQKS_V_ZJDXZEIQ,
    NV_R_URHLCNAU_F_FOEUOQKS_V_BEERCADZ,
    NV_R_URHLCNAU_F_FOEUOQKS_V_YMXUXRCP,
    NV_R_URHLCNAU_F_FOEUOQKS_V_LHIDWHYH,
    NV_R_URHLCNAU_F_FOEUOQKS_V_XFPXHKPK,
    NV_R_URHLCNAU_F_FOEUOQKS_V_MORUVMAI,
    NV_R_URHLCNAU_F_FOEUOQKS_V_KDKGQAAM,
    NV_R_URHLCNAU_F_FOEUOQKS_V_JFYGAVQY,
    NV_R_URHLCNAU_F_FOEUOQKS_V_SBOTVQUW,
    NV_R_URHLCNAU_F_FOEUOQKS_V_XUNVIIPU,
    NV_R_URHLCNAU_F_FOEUOQKS_V_GXXQFJOX,
    NV_R_URHLCNAU_F_FOEUOQKS_V_SSAQAUYP,
    NV_R_URHLCNAU_F_FOEUOQKS_V_MSQWSOOD,
    NV_R_URHLCNAU_F_FOEUOQKS_V_KIGXAQWE,
    NV_R_URHLCNAU_F_FOEUOQKS_V_FZTPJZXY,
    NV_R_URHLCNAU_F_FOEUOQKS_V_ZXLJTQRZ,
    NV_R_URHLCNAU_F_FOEUOQKS_V_FOPDMXPN,
    NV_R_URHLCNAU_F_FOEUOQKS_V_VLSXKBSW,
    NV_R_URHLCNAU_F_FOEUOQKS_V_IQFPOAMQ,
    NV_R_URHLCNAU_F_FOEUOQKS_V_IYSAZGZP,
    NV_R_LPKLJSFO,
    NV_R_URHLCNAU_STATUS,
    NV_R_URHLCNAU_STATUS_V_UUXHHBHV,
    NV_R_URHLCNAU_STATUS_V_KISGFKTQ,
    NV_R_URHLCNAU_STATUS_V_XRYTKQIA,
    NV_R_URHLCNAU_STATUS_V_BUEAUWOT,
    NV_R_URHLCNAU_STATUS_V_SWQGTAHD,
    NV_R_URHLCNAU_STATUS_V_ELFPBSDW,
    NV_R_URHLCNAU_STATUS_V_DEGLMMQM,
    NV_R_URHLCNAU_STATUS_V_LLJYZPOG,
    NV_R_URHLCNAU_STATUS_V_HRBAPKJH,
    NV_R_URHLCNAU_STATUS_V_ZIXPEGCF,
    NV_R_URHLCNAU_STATUS_V_ZAVHFCMQ,
    NV_R_URHLCNAU_STATUS_V_MHLMLFZA,
    NV_R_URHLCNAU_STATUS_V_NLLQALRD,
    NV_R_URHLCNAU_STATUS_V_CLOEANJZ,
    NV_R_URHLCNAU_STATUS_V_LVDKOIRS,
)

