#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata


# Registers identical to gb100
from gpu.regs.gb100.lrcc_int import (
    NV_R_CAPNLTRH,
    NV_R_CAPNLTRH_F_OJYQBJXU,
    NV_R_LNTDDVZE,
    NV_R_LNTDDVZE_F_CTBCFRUB,
    NV_R_LNTDDVZE_F_CTBCFRUB_V_GQHYEKHS,
    NV_R_LNTDDVZE_F_QVYAARWP,
    NV_R_LNTDDVZE_F_QVYAARWP_V_GQHYEKHS,
    NV_R_YFQGGFSX,
    NV_R_YFQGGFSX_F_DBYSWVHB,
    NV_R_YFQGGFSX_F_DBYSWVHB_V_DOGBFDTH,
    NV_R_YFQGGFSX_F_DBYSWVHB_V_PIUJQBKV,
    NV_R_YFQGGFSX_F_UURIHQGO,
    NV_R_YFQGGFSX_F_UURIHQGO_V_DOGBFDTH,
    NV_R_YFQGGFSX_F_UURIHQGO_V_PIUJQBKV,
    NV_R_QLKCSVDV,
    NV_R_QLKCSVDV_F_SFBPPWLV,
    NV_R_QLKCSVDV_F_SFBPPWLV_V_DOGBFDTH,
    NV_R_QLKCSVDV_F_SFBPPWLV_V_PIUJQBKV,
    NV_R_QLKCSVDV_F_NFYIVCEN,
    NV_R_QLKCSVDV_F_NFYIVCEN_V_DOGBFDTH,
    NV_R_QLKCSVDV_F_NFYIVCEN_V_PIUJQBKV,
    NV_R_QLKCSVDV_F_QMOEAKCW,
    NV_R_QLKCSVDV_F_QMOEAKCW_V_DOGBFDTH,
    NV_R_QLKCSVDV_F_QMOEAKCW_V_PIUJQBKV,
    NV_R_QLKCSVDV_F_NYJNHHJQ,
    NV_R_QLKCSVDV_F_NYJNHHJQ_V_DOGBFDTH,
    NV_R_QLKCSVDV_F_NYJNHHJQ_V_PIUJQBKV,
    NV_R_QLKCSVDV_F_OJXVVOEC,
    NV_R_QLKCSVDV_F_OJXVVOEC_V_DOGBFDTH,
    NV_R_QLKCSVDV_F_OJXVVOEC_V_PIUJQBKV,
    NV_R_QLKCSVDV_F_VEOHPHHB,
    NV_R_QLKCSVDV_F_VEOHPHHB_V_DOGBFDTH,
    NV_R_QLKCSVDV_F_VEOHPHHB_V_PIUJQBKV,
    NV_R_QLKCSVDV_F_KVYOKDXN,
    NV_R_QLKCSVDV_F_KVYOKDXN_V_ACRDDIMM,
    NV_R_QLKCSVDV_F_KVYOKDXN_V_GQHYEKHS,
    NV_R_QLKCSVDV_F_KVYOKDXN_V_CIHFEZTE,
    NV_R_QLKCSVDV_F_GAFICVXX,
    NV_R_QLKCSVDV_F_GAFICVXX_V_DOGBFDTH,
    NV_R_QLKCSVDV_F_GAFICVXX_V_PIUJQBKV,
    NV_R_QLKCSVDV_F_UQVLNUJK,
    NV_R_QLKCSVDV_F_UQVLNUJK_V_DOGBFDTH,
    NV_R_QLKCSVDV_F_UQVLNUJK_V_PIUJQBKV,
    NV_R_QLKCSVDV_F_LDTFOZKB,
    NV_R_QLKCSVDV_F_LDTFOZKB_V_DOGBFDTH,
    NV_R_QLKCSVDV_F_LDTFOZKB_V_PIUJQBKV,
    NV_R_QLKCSVDV_F_EIMZUTEV,
    NV_R_QLKCSVDV_F_EIMZUTEV_V_DOGBFDTH,
    NV_R_QLKCSVDV_F_EIMZUTEV_V_PIUJQBKV,
    NV_R_QLKCSVDV_F_WQYWMRVP,
    NV_R_QLKCSVDV_F_WQYWMRVP_V_DOGBFDTH,
    NV_R_QLKCSVDV_F_WQYWMRVP_V_PIUJQBKV,
    NV_R_QLKCSVDV_F_MLEOLJIS,
    NV_R_QLKCSVDV_F_MLEOLJIS_V_DOGBFDTH,
    NV_R_QLKCSVDV_F_MLEOLJIS_V_PIUJQBKV,
    NV_R_QKOOTAJF,
    NV_R_QKOOTAJF_F_CTBCFRUB,
    NV_R_QKOOTAJF_F_CTBCFRUB_V_GQHYEKHS,
    NV_R_QKOOTAJF_F_QVYAARWP,
    NV_R_QKOOTAJF_F_QVYAARWP_V_GQHYEKHS,
)

