#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata

# Registers identical to gb100
from gpu.regs.gb100.top import (
    NV_PTOP_DEVICE_INFO2,
    NV_PTOP_DEVICE_INFO2_DEV_DEVICE_PRI_BASE,
    NV_PTOP_DEVICE_INFO2_DEV_FAULT_ID,
    NV_PTOP_DEVICE_INFO2_DEV_FAULT_ID_INVALID,
    NV_PTOP_DEVICE_INFO2_DEV_GROUP_ID,
    NV_PTOP_DEVICE_INFO2_DEV_INSTANCE_ID,
    NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE,
    NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE_FALSE,
    NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE_TRUE,
    NV_PTOP_DEVICE_INFO2_DEV_RESET_ID,
    NV_PTOP_DEVICE_INFO2_DEV_RESET_ID_INVALID,
    NV_PTOP_DEVICE_INFO2_DEV_RLENG_ID,
    NV_PTOP_DEVICE_INFO2_DEV_RUNLIST_PRI_BASE,
    NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM,
    NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_FBHUB,
    NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_HSHUB,
    NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_HSHUBMMU,
    NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_HUBMMU,
    NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_NVLPW,
    NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_SYSLTC,
    NV_PTOP_DEVICE_INFO2_ROW_CHAIN,
    NV_PTOP_DEVICE_INFO2_ROW_CHAIN_LAST,
    NV_PTOP_DEVICE_INFO2_ROW_CHAIN_MORE,
    NV_PTOP_DEVICE_INFO2_ROW_VALUE,
    NV_PTOP_DEVICE_INFO2_ROW_VALUE_INVALID,
    NV_PTOP_DEVICE_INFO_CFG,
    NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES,
    NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES_INIT,
    NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE,
    NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE_INIT,
    NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS,
    NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS_INIT,
    NV_PTOP_DEVICE_INFO_CFG_VERSION,
    NV_PTOP_DEVICE_INFO_CFG_VERSION_INIT,
)

