#
# SPDX-FileCopyrightText: Copyright (c) 2025-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata

# Register definitions
NV_R_NRELBYZA = RegisterMetadata(
    name='NV_R_NRELBYZA',
    address=0x20120
)

NV_R_NRELBYZA_F_UIZAVLDE = FieldMetadata(
    name='NV_R_NRELBYZA_F_UIZAVLDE',
    msb=30,
    lsb=30,
    register=NV_R_NRELBYZA
)

NV_R_NRELBYZA_F_UIZAVLDE_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_NRELBYZA_F_UIZAVLDE_WRITE_VIOLATION',
    value=1,
    field=NV_R_NRELBYZA_F_UIZAVLDE
)
NV_R_NRELBYZA_F_UIZAVLDE_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_NRELBYZA_F_UIZAVLDE_WRITE_VIOLATION',
    value=0,
    field=NV_R_NRELBYZA_F_UIZAVLDE
)

NV_R_NRELBYZA_F_QVFZOXLJ = FieldMetadata(
    name='NV_R_NRELBYZA_F_QVFZOXLJ',
    msb=29,
    lsb=0,
    register=NV_R_NRELBYZA
)

NV_R_NRELBYZA_F_QVFZOXLJ_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_NRELBYZA_F_QVFZOXLJ_WRITE_VIOLATION',
    value=0,
    field=NV_R_NRELBYZA_F_QVFZOXLJ
)

NV_R_NRELBYZA_F_LFGRYOZH = FieldMetadata(
    name='NV_R_NRELBYZA_F_LFGRYOZH',
    msb=31,
    lsb=31,
    register=NV_R_NRELBYZA
)

NV_R_NRELBYZA_F_LFGRYOZH_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_NRELBYZA_F_LFGRYOZH_WRITE_VIOLATION',
    value=0,
    field=NV_R_NRELBYZA_F_LFGRYOZH
)
NV_R_NRELBYZA_F_LFGRYOZH_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_NRELBYZA_F_LFGRYOZH_WRITE_VIOLATION',
    value=1,
    field=NV_R_NRELBYZA_F_LFGRYOZH
)

NV_THERM_I2CS_SCRATCH = RegisterMetadata(
    name='NV_THERM_I2CS_SCRATCH',
    address=0x200bc
)

NV_THERM_I2CS_SCRATCH_DATA = FieldMetadata(
    name='NV_THERM_I2CS_SCRATCH_DATA',
    msb=31,
    lsb=0,
    register=NV_THERM_I2CS_SCRATCH
)

NV_THERM_I2CS_SCRATCH_DATA_INIT = ValueMetadata(
    name='NV_THERM_I2CS_SCRATCH_DATA_INIT',
    value=0,
    field=NV_THERM_I2CS_SCRATCH_DATA
)

# Array definitions
NV_R_HFXMPEPY_PRIV_LEVEL_MASK = ArrayMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK',
    base_address=0x20800,
    stride=4,
    size=8
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION',
    msb=3,
    lsb=0,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_WRITE_VIOLATION',
    value=12,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_WRITE_VIOLATION',
    value=8,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0 = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0',
    msb=0,
    lsb=0,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_WRITE_VIOLATION',
    value=0,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0
)
NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_WRITE_VIOLATION',
    value=1,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1 = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1',
    msb=1,
    lsb=1,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_WRITE_VIOLATION',
    value=0,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1
)
NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_WRITE_VIOLATION',
    value=1,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2 = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2',
    msb=2,
    lsb=2,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_WRITE_VIOLATION',
    value=0,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2
)
NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_WRITE_VIOLATION',
    value=1,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3 = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3',
    msb=3,
    lsb=3,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_WRITE_VIOLATION',
    value=0,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3
)
NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_WRITE_VIOLATION',
    value=1,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_VIOLATION = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_VIOLATION',
    msb=8,
    lsb=8,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_VIOLATION_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_VIOLATION_WRITE_VIOLATION',
    value=1,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_VIOLATION
)
NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_VIOLATION_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_VIOLATION_WRITE_VIOLATION',
    value=0,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_READ_VIOLATION
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_ENABLE = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_ENABLE',
    msb=31,
    lsb=12,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_ENABLE_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_ENABLE_WRITE_VIOLATION',
    value=1048575,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_ENABLE
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL',
    msb=10,
    lsb=10,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_WRITE_VIOLATION',
    value=1,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)
NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_WRITE_VIOLATION',
    value=0,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL',
    msb=11,
    lsb=11,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_WRITE_VIOLATION',
    value=1,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)
NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_WRITE_VIOLATION',
    value=0,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION',
    msb=7,
    lsb=4,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_WRITE_VIOLATION',
    value=12,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_WRITE_VIOLATION',
    value=8,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0 = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0',
    msb=4,
    lsb=4,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_WRITE_VIOLATION',
    value=0,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0
)
NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_WRITE_VIOLATION',
    value=1,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1 = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1',
    msb=5,
    lsb=5,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_WRITE_VIOLATION',
    value=0,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1
)
NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_WRITE_VIOLATION',
    value=1,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2 = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2',
    msb=6,
    lsb=6,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_WRITE_VIOLATION',
    value=0,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2
)
NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_WRITE_VIOLATION',
    value=1,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3 = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3',
    msb=7,
    lsb=7,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_WRITE_VIOLATION',
    value=0,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3
)
NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_WRITE_VIOLATION',
    value=1,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_VIOLATION = FieldMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_VIOLATION',
    msb=9,
    lsb=9,
    register=NV_R_HFXMPEPY_PRIV_LEVEL_MASK
)

NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_VIOLATION_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_VIOLATION_WRITE_VIOLATION',
    value=1,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_VIOLATION
)
NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_VIOLATION_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_VIOLATION_WRITE_VIOLATION',
    value=0,
    field=NV_R_HFXMPEPY_PRIV_LEVEL_MASK_WRITE_VIOLATION
)

NV_R_ETSFYALG = ArrayMetadata(
    name='NV_R_ETSFYALG',
    base_address=0x205b8,
    stride=4,
    size=8
)

NV_R_ETSFYALG_F_FDJGTZTF = FieldMetadata(
    name='NV_R_ETSFYALG_F_FDJGTZTF',
    msb=31,
    lsb=0,
    register=NV_R_ETSFYALG
)

NV_R_ETSFYALG_F_FDJGTZTF_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_ETSFYALG_F_FDJGTZTF_WRITE_VIOLATION',
    value=0,
    field=NV_R_ETSFYALG_F_FDJGTZTF
)

NV_R_PIRHWHMC = ArrayMetadata(
    name='NV_R_PIRHWHMC',
    base_address=0x205d8,
    stride=4,
    size=8
)

NV_R_PIRHWHMC_F_FDJGTZTF = FieldMetadata(
    name='NV_R_PIRHWHMC_F_FDJGTZTF',
    msb=31,
    lsb=0,
    register=NV_R_PIRHWHMC
)

NV_R_PIRHWHMC_F_FDJGTZTF_WRITE_VIOLATION = ValueMetadata(
    name='NV_R_PIRHWHMC_F_FDJGTZTF_WRITE_VIOLATION',
    value=0,
    field=NV_R_PIRHWHMC_F_FDJGTZTF
)

