#
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

from gpu.regs.core import RegisterMetadata, FieldMetadata, ValueMetadata, ArrayMetadata, DeviceMetadata


# Register definitions
NV_R_RLQLWEHM_PRIV_LEVEL_MASK = RegisterMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK',
    address=0x22404
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION',
    msb=3,
    lsb=0,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED',
    value=15,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL',
    value=15,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_V_TECBDROR',
    value=8,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0',
    msb=0,
    lsb=0,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1',
    msb=1,
    lsb=1,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2',
    msb=2,
    lsb=2,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3',
    msb=3,
    lsb=3,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION',
    msb=8,
    lsb=8,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_READ_VIOLATION
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_ENABLE = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_ENABLE',
    msb=31,
    lsb=12,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_WZUSYRII = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_ENABLE_V_WZUSYRII',
    value=65,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_ENABLE
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL',
    msb=10,
    lsb=10,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL',
    msb=11,
    lsb=11,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION',
    msb=7,
    lsb=4,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED',
    value=15,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_DEFAULT_PRIV_LEVEL',
    value=15,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_V_TECBDROR',
    value=8,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0',
    msb=4,
    lsb=4,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1',
    msb=5,
    lsb=5,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2',
    msb=6,
    lsb=6,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3 = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3',
    msb=7,
    lsb=7,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION = FieldMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION',
    msb=9,
    lsb=9,
    register=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR',
    value=1,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION
)
NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON = ValueMetadata(
    name='NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON',
    value=0,
    field=NV_R_RLQLWEHM_PRIV_LEVEL_MASK_WRITE_VIOLATION
)

NV_PTOP_DEVICE_INFO_CFG = RegisterMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG',
    address=0x224fc
)

NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES',
    msb=15,
    lsb=4,
    register=NV_PTOP_DEVICE_INFO_CFG
)

NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES_INIT = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES_INIT',
    value=49,
    field=NV_PTOP_DEVICE_INFO_CFG_MAX_DEVICES
)

NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE',
    msb=19,
    lsb=16,
    register=NV_PTOP_DEVICE_INFO_CFG
)

NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE_INIT = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE_INIT',
    value=3,
    field=NV_PTOP_DEVICE_INFO_CFG_MAX_ROWS_PER_DEVICE
)

NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS',
    msb=31,
    lsb=20,
    register=NV_PTOP_DEVICE_INFO_CFG
)

NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS_INIT = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS_INIT',
    value=134,
    field=NV_PTOP_DEVICE_INFO_CFG_NUM_ROWS
)

NV_PTOP_DEVICE_INFO_CFG_VERSION = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_VERSION',
    msb=3,
    lsb=0,
    register=NV_PTOP_DEVICE_INFO_CFG
)

NV_PTOP_DEVICE_INFO_CFG_VERSION_INIT = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO_CFG_VERSION_INIT',
    value=2,
    field=NV_PTOP_DEVICE_INFO_CFG_VERSION
)

NV_R_PWZXFNWW = RegisterMetadata(
    name='NV_R_PWZXFNWW',
    address=0x22608
)

NV_R_PWZXFNWW_F_SDHCEVQG = FieldMetadata(
    name='NV_R_PWZXFNWW_F_SDHCEVQG',
    msb=31,
    lsb=0,
    register=NV_R_PWZXFNWW
)

NV_R_PWZXFNWW_F_SDHCEVQG_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_PWZXFNWW_F_SDHCEVQG_V_ZRRJKDVX',
    value=0,
    field=NV_R_PWZXFNWW_F_SDHCEVQG
)
NV_R_PWZXFNWW_F_SDHCEVQG_V_GQHYEKHS = ValueMetadata(
    name='NV_R_PWZXFNWW_F_SDHCEVQG_V_GQHYEKHS',
    value=0,
    field=NV_R_PWZXFNWW_F_SDHCEVQG
)

NV_R_CUYACIFH = RegisterMetadata(
    name='NV_R_CUYACIFH',
    address=0x22478
)

NV_R_CUYACIFH_VALUE = FieldMetadata(
    name='NV_R_CUYACIFH_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_CUYACIFH
)

NV_R_CUYACIFH_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_CUYACIFH_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_CUYACIFH_VALUE
)

NV_R_SXKEOIBW = RegisterMetadata(
    name='NV_R_SXKEOIBW',
    address=0x22474
)

NV_R_SXKEOIBW_VALUE = FieldMetadata(
    name='NV_R_SXKEOIBW_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_SXKEOIBW
)

NV_R_SXKEOIBW_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_SXKEOIBW_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_SXKEOIBW_VALUE
)

NV_R_AFPSKUZI = RegisterMetadata(
    name='NV_R_AFPSKUZI',
    address=0x2247c
)

NV_R_AFPSKUZI_VALUE = FieldMetadata(
    name='NV_R_AFPSKUZI_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_AFPSKUZI
)

NV_R_AFPSKUZI_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_AFPSKUZI_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_AFPSKUZI_VALUE
)

NV_R_ZUPOMPFW = RegisterMetadata(
    name='NV_R_ZUPOMPFW',
    address=0x22484
)

NV_R_ZUPOMPFW_VALUE = FieldMetadata(
    name='NV_R_ZUPOMPFW_VALUE',
    msb=2,
    lsb=0,
    register=NV_R_ZUPOMPFW
)

NV_R_ZUPOMPFW_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_ZUPOMPFW_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_ZUPOMPFW_VALUE
)

NV_R_HMQJWADN = RegisterMetadata(
    name='NV_R_HMQJWADN',
    address=0x22444
)

NV_R_HMQJWADN_VALUE = FieldMetadata(
    name='NV_R_HMQJWADN_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_HMQJWADN
)

NV_R_HMQJWADN_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_HMQJWADN_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_HMQJWADN_VALUE
)

NV_R_MYRIQRHT = RegisterMetadata(
    name='NV_R_MYRIQRHT',
    address=0x22448
)

NV_R_MYRIQRHT_VALUE = FieldMetadata(
    name='NV_R_MYRIQRHT_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_MYRIQRHT
)

NV_R_MYRIQRHT_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_MYRIQRHT_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_MYRIQRHT_VALUE
)

NV_R_WTQAYGOT = RegisterMetadata(
    name='NV_R_WTQAYGOT',
    address=0x2243c
)

NV_R_WTQAYGOT_VALUE = FieldMetadata(
    name='NV_R_WTQAYGOT_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_WTQAYGOT
)

NV_R_WTQAYGOT_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_WTQAYGOT_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_WTQAYGOT_VALUE
)

NV_R_MALHPZWJ = RegisterMetadata(
    name='NV_R_MALHPZWJ',
    address=0x22458
)

NV_R_MALHPZWJ_VALUE = FieldMetadata(
    name='NV_R_MALHPZWJ_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_MALHPZWJ
)

NV_R_MALHPZWJ_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_MALHPZWJ_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_MALHPZWJ_VALUE
)

NV_R_JVHVALTL = RegisterMetadata(
    name='NV_R_JVHVALTL',
    address=0x22438
)

NV_R_JVHVALTL_VALUE = FieldMetadata(
    name='NV_R_JVHVALTL_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_JVHVALTL
)

NV_R_JVHVALTL_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_JVHVALTL_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_JVHVALTL_VALUE
)

NV_R_GMOCCARV = RegisterMetadata(
    name='NV_R_GMOCCARV',
    address=0x22430
)

NV_R_GMOCCARV_VALUE = FieldMetadata(
    name='NV_R_GMOCCARV_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_GMOCCARV
)

NV_R_GMOCCARV_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_GMOCCARV_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_GMOCCARV_VALUE
)

NV_R_RLGXXLDD = RegisterMetadata(
    name='NV_R_RLGXXLDD',
    address=0x22454
)

NV_R_RLGXXLDD_VALUE = FieldMetadata(
    name='NV_R_RLGXXLDD_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_RLGXXLDD
)

NV_R_RLGXXLDD_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_RLGXXLDD_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_RLGXXLDD_VALUE
)

NV_R_MGENATIB = RegisterMetadata(
    name='NV_R_MGENATIB',
    address=0x22450
)

NV_R_MGENATIB_VALUE = FieldMetadata(
    name='NV_R_MGENATIB_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_MGENATIB
)

NV_R_MGENATIB_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_MGENATIB_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_MGENATIB_VALUE
)

NV_R_FXMSYJMF = RegisterMetadata(
    name='NV_R_FXMSYJMF',
    address=0x22464
)

NV_R_FXMSYJMF_VALUE = FieldMetadata(
    name='NV_R_FXMSYJMF_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_FXMSYJMF
)

NV_R_FXMSYJMF_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_FXMSYJMF_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_FXMSYJMF_VALUE
)

NV_R_QIDNGOVJ = RegisterMetadata(
    name='NV_R_QIDNGOVJ',
    address=0x2244c
)

NV_R_QIDNGOVJ_VALUE = FieldMetadata(
    name='NV_R_QIDNGOVJ_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_QIDNGOVJ
)

NV_R_QIDNGOVJ_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_QIDNGOVJ_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_QIDNGOVJ_VALUE
)

NV_R_UKNWXHHW = RegisterMetadata(
    name='NV_R_UKNWXHHW',
    address=0x22468
)

NV_R_UKNWXHHW_VALUE = FieldMetadata(
    name='NV_R_UKNWXHHW_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_UKNWXHHW
)

NV_R_UKNWXHHW_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_UKNWXHHW_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_UKNWXHHW_VALUE
)

NV_R_MUMMKQCM = RegisterMetadata(
    name='NV_R_MUMMKQCM',
    address=0x2246c
)

NV_R_MUMMKQCM_VALUE = FieldMetadata(
    name='NV_R_MUMMKQCM_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_MUMMKQCM
)

NV_R_MUMMKQCM_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_MUMMKQCM_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_MUMMKQCM_VALUE
)

NV_R_ZNEWYGRA = RegisterMetadata(
    name='NV_R_ZNEWYGRA',
    address=0x22470
)

NV_R_ZNEWYGRA_VALUE = FieldMetadata(
    name='NV_R_ZNEWYGRA_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_ZNEWYGRA
)

NV_R_ZNEWYGRA_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_ZNEWYGRA_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_ZNEWYGRA_VALUE
)

NV_R_KYKLMRFE = RegisterMetadata(
    name='NV_R_KYKLMRFE',
    address=0x22460
)

NV_R_KYKLMRFE_VALUE = FieldMetadata(
    name='NV_R_KYKLMRFE_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_KYKLMRFE
)

NV_R_KYKLMRFE_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_KYKLMRFE_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_KYKLMRFE_VALUE
)

NV_R_TWHJUYMI = RegisterMetadata(
    name='NV_R_TWHJUYMI',
    address=0x22480
)

NV_R_TWHJUYMI_VALUE = FieldMetadata(
    name='NV_R_TWHJUYMI_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_TWHJUYMI
)

NV_R_TWHJUYMI_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_TWHJUYMI_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_TWHJUYMI_VALUE
)

NV_R_KMZTDFMK = RegisterMetadata(
    name='NV_R_KMZTDFMK',
    address=0x2245c
)

NV_R_KMZTDFMK_VALUE = FieldMetadata(
    name='NV_R_KMZTDFMK_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_KMZTDFMK
)

NV_R_KMZTDFMK_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_KMZTDFMK_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_KMZTDFMK_VALUE
)

NV_R_UTWVFXBK = RegisterMetadata(
    name='NV_R_UTWVFXBK',
    address=0x22434
)

NV_R_UTWVFXBK_VALUE = FieldMetadata(
    name='NV_R_UTWVFXBK_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_UTWVFXBK
)

NV_R_UTWVFXBK_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_UTWVFXBK_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_UTWVFXBK_VALUE
)

NV_R_HTYAWCIU = RegisterMetadata(
    name='NV_R_HTYAWCIU',
    address=0x22440
)

NV_R_HTYAWCIU_VALUE = FieldMetadata(
    name='NV_R_HTYAWCIU_VALUE',
    msb=4,
    lsb=0,
    register=NV_R_HTYAWCIU
)

NV_R_HTYAWCIU_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_HTYAWCIU_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_HTYAWCIU_VALUE
)

NV_R_ZEZRECZW = RegisterMetadata(
    name='NV_R_ZEZRECZW',
    address=0x22408,
    priv_level_mask=NV_R_RLQLWEHM_PRIV_LEVEL_MASK
)

NV_R_ZEZRECZW_VALUE = FieldMetadata(
    name='NV_R_ZEZRECZW_VALUE',
    msb=31,
    lsb=0,
    register=NV_R_ZEZRECZW
)

NV_R_ZEZRECZW_VALUE_V_ZRRJKDVX = ValueMetadata(
    name='NV_R_ZEZRECZW_VALUE_V_ZRRJKDVX',
    value=0,
    field=NV_R_ZEZRECZW_VALUE
)

# Array definitions
NV_PTOP_DEVICE_INFO2 = ArrayMetadata(
    name='NV_PTOP_DEVICE_INFO2',
    base_address=0x22800,
    stride=4,
    size=134
)

NV_PTOP_DEVICE_INFO2_DEV_DEVICE_PRI_BASE = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_DEVICE_PRI_BASE',
    msb=57,
    lsb=40,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_FAULT_ID = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_FAULT_ID',
    msb=10,
    lsb=0,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_FAULT_ID_INVALID = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_FAULT_ID_INVALID',
    value=0,
    field=NV_PTOP_DEVICE_INFO2_DEV_FAULT_ID
)

NV_PTOP_DEVICE_INFO2_DEV_INSTANCE_ID = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_INSTANCE_ID',
    msb=23,
    lsb=16,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE',
    msb=62,
    lsb=62,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE_FALSE = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE_FALSE',
    value=0,
    field=NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE
)
NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE_TRUE = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE_TRUE',
    value=1,
    field=NV_PTOP_DEVICE_INFO2_DEV_IS_ENGINE
)

NV_PTOP_DEVICE_INFO2_DEV_RESET_ID = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_RESET_ID',
    msb=39,
    lsb=32,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_RESET_ID_INVALID = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_RESET_ID_INVALID',
    value=0,
    field=NV_PTOP_DEVICE_INFO2_DEV_RESET_ID
)

NV_PTOP_DEVICE_INFO2_DEV_RLENG_ID = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_RLENG_ID',
    msb=65,
    lsb=64,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_RUNLIST_PRI_BASE = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_RUNLIST_PRI_BASE',
    msb=89,
    lsb=74,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM',
    msb=30,
    lsb=24,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_RVLKEJWH = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_RVLKEJWH',
    value=25,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_UOZWLQWO = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_UOZWLQWO',
    value=23,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_UDSNKUFQ = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_UDSNKUFQ',
    value=26,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_GOCSCMKA = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_GOCSCMKA',
    value=0,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_LWBHHXKA = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_LWBHHXKA',
    value=20,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_HSHUB = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_HSHUB',
    value=24,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_EHKYSREA = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_EHKYSREA',
    value=18,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_ADOFRLBI = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_ADOFRLBI',
    value=19,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_GIUXYEQN = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_GIUXYEQN',
    value=16,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_NVYOLSKM = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_NVYOLSKM',
    value=14,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_NIPQQHPC = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_NIPQQHPC',
    value=21,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_BNYIUTBN = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_BNYIUTBN',
    value=22,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)
NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_NSDPVTAV = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM_V_NSDPVTAV',
    value=13,
    field=NV_PTOP_DEVICE_INFO2_DEV_TYPE_ENUM
)

NV_PTOP_DEVICE_INFO2_ROW_CHAIN = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_ROW_CHAIN',
    msb=31,
    lsb=31,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_ROW_CHAIN_LAST = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_ROW_CHAIN_LAST',
    value=0,
    field=NV_PTOP_DEVICE_INFO2_ROW_CHAIN
)
NV_PTOP_DEVICE_INFO2_ROW_CHAIN_MORE = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_ROW_CHAIN_MORE',
    value=1,
    field=NV_PTOP_DEVICE_INFO2_ROW_CHAIN
)

NV_PTOP_DEVICE_INFO2_ROW_VALUE = FieldMetadata(
    name='NV_PTOP_DEVICE_INFO2_ROW_VALUE',
    msb=31,
    lsb=0,
    register=NV_PTOP_DEVICE_INFO2
)

NV_PTOP_DEVICE_INFO2_ROW_VALUE_INVALID = ValueMetadata(
    name='NV_PTOP_DEVICE_INFO2_ROW_VALUE_INVALID',
    value=0,
    field=NV_PTOP_DEVICE_INFO2_ROW_VALUE
)

